### PR TITLE
fix: Wrap `MAMBA_EXE` around double quotes in run shell script

### LINKED ISSUE #3057: micromamba errors when installed to a location with spaces in the path
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

"path space", "no such file or directory"

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I followed the micromamba manual installation instructions in a directory that contains spaces in the path. Some micromamba commands produce an error that appears to be caused by the path space not being handled correctly.
```bash
$ mkdir "with spaces"
$ cd "with spaces"
$ curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
$ eval "$(./bin/micromamba shell hook -s posix)"
$ micromamba create -n test python==3.11
$ micromamba run --name test python --version
/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu: line 2: /Users/emily/with: No such file or directory
/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu: line 3: micromamba: command not found
/var/folders/zh/dy02ljyd4mj5_nfm158hwcr00000gn/T/mambafAXk1Ko5alu: line 5: exec: python: not found
```
I think it is an issue with path handling because of the line `/Users/emily/with: No such file or directory`, the path is broken at the space.

### mamba info / micromamba info

```shell
libmamba version : 1.5.3
     micromamba version : 1.5.3
           curl version : libcurl/8.4.0 SecureTransport (OpenSSL/3.1.4) zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /Users/emily/micromamba/envs
          package cache : /Users/emily/micromamba/pkgs
                          /Users/emily/.mamba/pkgs
            environment : /Users/emily/mambaforge/envs/plugin (active)
           env location : /Users/emily/mambaforge/envs/plugin
      user config files : /Users/emily/.mambarc
 populated config files : /Users/emily/.condarc
       virtual packages : __unix=0=0
                          __osx=13.2.1=0
                          __archspec=1=x86_64-v4
               channels : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
       base environment : /Users/emily/micromamba
               platform : osx-64
```

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by luciorq**
## Description

This PR addresses an issue where the `$MAMBA_EXE` variable in `mamba run` and `micromamba run` shell scripts were not properly quoted, causing failures when the executable path contains spaces characters.

## Linked Issue

Closes #3057

### CODE REVIEW

File: libmamba/src/core/util.cpp [hunk 1]
```diff
@@ -1510,7 +1510,7 @@ namespace mamba
         {
             // Micromamba hook
             out << "export MAMBA_EXE=" << std::quoted(get_self_exe_path().string(), '\'') << "\n";
```
Comment (jjerphan) [inline libmamba/src/core/util.cpp:1512]: How about?
```suggestion
            out << "export MAMBA_EXE=\"" << std::quoted(get_self_exe_path().string(), '\'') << "\"\n";
```

**Review by jjerphan — APPROVED** [review]
Thank you, @luciorq!
