### PR TITLE
Fix authenticated downloading

### LINKED ISSUE #3864: mamba 2.0.7 fails with 401 auth error when downloading private package
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

401 auth error when downloading private package

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

When installing a package from a private package repo (i.e. `https://<user>:<pass>@<private-package-url>/pkgs`), micromamba 2.0.7 fails with a 401 auth error:

```
Transaction starting
error    libmamba Failed to download package from https://***:***@***/pkgs/noarch/***.tar.bz2 (status 401)
    If you see this message repeatedly, the state of your installation might be corrupted,
    in which case running `mamba clean --all` might fix it.
    
    If you continue to meet this problem, please search or report an issue
    on  mamba's issue tracker: https://github.com/mamba-org/mamba/issues/
```

This does not occur when using micromamba 2.0.5 or 2.0.6

### mamba info / micromamba info

```shell
       libmamba version : 2.0.7
     micromamba version : 2.0.7
           curl version : libcurl/8.12.1 OpenSSL/3.4.1 zlib/1.3.1 zstd/1.5.7 libssh2/1.11.1 nghttp2/1.64.0
     libarchive version : libarchive 3.7.7 zlib/1.3.1 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /home/vsts/micromamba/envs
          package cache : /home/vsts/micromamba/pkgs
                          /home/vsts/.mamba/pkgs
            environment : base
           env location : /home/vsts/micromamba
      user config files : /home/vsts/.mambarc
 populated config files : /home/vsts/.condarc
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64_v4
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /home/vsts/micromamba
               platform : linux-64
```

### PR DESCRIPTION
**Pull request by Hind-M**
Fix #3864

### CODE REVIEW

**Review by ghacme — COMMENTED** [review]
Downloaded linux-64 binary  from this build. auth fix works, tho version is 2.0.8.
Thanks.

File: libmamba/include/mamba/core/util.hpp [hunk 1]
```diff
@@ -26,6 +27,14 @@ namespace mamba
 {
     class Context;
 
+    namespace
```
Comment (JohanMabille) [inline libmamba/include/mamba/core/util.hpp:30]: We should avoid anonymous namespaces in headers, because all the anonymous namespaces of a compilation unit are collapsed into a single one, and this could lead to names clash.

**Review by JohanMabille — CHANGES_REQUESTED** [review]

File: libmamba/include/mamba/core/util.hpp (hunk 1 above)
Comment (JohanMabille) [reply libmamba/include/mamba/core/util.hpp:30]: Actually we may want to encapsulate these variables in functions now that they are to be used in different places and exposed in the API.

Comment (Hind-M) [reply libmamba/include/mamba/core/util.hpp:30]: Maybe just functions returning their values?

Comment (JohanMabille) [reply libmamba/include/mamba/core/util.hpp:30]: I meant functions encapsulating the definition, yes

**Review by JohanMabille — APPROVED** [review]

**Comment by pavelzw** [comment]
when have you planned your next release?

**Comment by Hind-M** [comment]
> when have you planned your next release?

Hopefully this week :)

File: libmamba/src/core/util.cpp [hunk 2]
```diff
@@ -1647,24 +1660,16 @@ namespace mamba
...
         std::string copy(str);
 
         if (util::contains(str, "/t/"))
         {
-            copy = std::regex_replace(copy, token_regex, "/t/*****");
+            copy = std::regex_replace(copy, token_regex(), "/t/*****");
         }
 
-        copy = std::regex_replace(copy, http_basicauth_regex, "$1$2:*****@");
+        copy = std::regex_replace(copy, http_basicauth_regex(), "$1$2:*****@");
```
Comment (mbestipa) [inline libmamba/src/core/util.cpp:1672]: here
