### PR TITLE
Fix constructor invalid `repodata_record`

### LINKED ISSUE #993: Found corrupted repodata_record file warning
I'm trying to use `boa` / `mamba` to debug requirement conflicts over in https://github.com/conda-forge/qt-feedstock/pull/194 
and seeing some strange errors, like 

```
WARNING Found corrupted repodata_record file "/Users/runner/miniforge3/pkgs/libcxx-11.1.0-habf9029_0/info/repodata_record.json"
```
~~and
Encountered problems while solving:
package clangxx_osx-64-11.0.0-hc3ec130_0 requires clang_osx-64 11.0.0 h05bbb7f_0, but none of the providers can be installed~~

Unfortunately I don't have a Mac and so can't reproduce or investigate locally, but let me know if there is any other useful information I can provide.

### PR DESCRIPTION
**Pull request by adriendelsalle**
Description
---

Fix constructor invalid `repodata_record`: missing `size` and `sha256` for validation
Improve logging

Closes #993

### CODE REVIEW

File: src/micromamba/constructor.cpp [hunk 1]
```diff
@@ -82,7 +82,9 @@ construct(const fs::path& prefix, bool extract_conda_pkgs, bool extract_tarball)
         {
             if (is_package_file(entry.path().filename().string()))
             {
+                LOG_TRACE << "Extracting " << entry.path().filename() << std::endl;
```
Comment (wolfv) [inline src/micromamba/constructor.cpp:85]: we shoudl keep cout here. it's good to see the progress.

File: src/core/package_handling.cpp [hunk 2]
```diff
@@ -481,10 +480,10 @@ namespace mamba
         }
         catch (...)
         {
-            LOG_WARNING << "Could not read paths.json from " << pkg_folder << std::endl;
```
Comment (wolfv) [inline src/core/package_handling.cpp:484]: not sure that trace is the correct replacement for WARNING

File: src/core/package_handling.cpp [hunk 3]
```diff
@@ -446,7 +446,7 @@ namespace mamba
                 {
                     if (is_warn || is_fail)
                     {
-                        LOG_WARNING << "Missing file from package cache: " << full_path;
+                        LOG_TRACE << "Missing file from package cache: " << full_path;
```
Comment (wolfv) [inline src/core/package_handling.cpp:449]: Here I'd keep the warning as it could be a hacker :)

File: src/micromamba/constructor.cpp (hunk 1 above)
Comment (adriendelsalle) [reply src/micromamba/constructor.cpp:85]: I didn't removed it, just added the same info in the logs

File: src/core/package_handling.cpp (hunk 2 above)
Comment (adriendelsalle) [reply src/core/package_handling.cpp:484]: this method is called here https://github.com/mamba-org/mamba/blob/42475c057869356f6652e9ef9ba7f94f520567fc/src/core/package_cache.cpp#L226 and the warning will be emitted.
This is not necessary to emit 2 warnings for the same invalid cache, so I put the details in `trace`

File: src/micromamba/constructor.cpp (hunk 1 above)
Comment (wolfv) [reply src/micromamba/constructor.cpp:85]: But the miniforge / mambaforge users won't see anything or am I mistaken? Since the TRACE log is not going to be displayed.

File: src/core/package_handling.cpp (hunk 3 above)
Comment (adriendelsalle) [reply src/core/package_handling.cpp:449]: same as the other log, 2 warnings are not necessary for the same invalid cache, it's just flooding the logs

File: src/core/package_handling.cpp (hunk 2 above)
Comment (wolfv) [reply src/core/package_handling.cpp:484]: this stuff almost _never_ happens and when it happens it would help us to locate a bug more easily since the users would see the (more precise) warnings right away. So it could help us with future bugs

File: src/micromamba/constructor.cpp (hunk 1 above)
Comment (adriendelsalle) [reply src/micromamba/constructor.cpp:85]: have a look at line 86, it's still printed in `cout`

File: src/core/package_handling.cpp (hunk 3 above)
Comment (wolfv) [reply src/core/package_handling.cpp:449]: Again this should almost never happen, and I quite like to get this information when I (myself) changed the files in the package cache, just so that I can figure out bugs that I made myself quicker. In the second warning we're not printing which file has been changed.

File: src/micromamba/constructor.cpp (hunk 1 above)
Comment (wolfv) [reply src/micromamba/constructor.cpp:85]: then i don't know why we need the trace log :)

**Comment by wolfv** [comment]
AwEsOmE! :)
