### PR TITLE
fix: Environment removal confirmation

### LINKED ISSUE #3437: micromamba environment removal proceeds even after I interactively answered 'n'
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I launched that command (outside of any environment):

    micromamba env remove -n foo

Which prompted me for:

    Confirm changes: [Y/n]

to which I answered **`n`**.

It then showed:

    Aborted.
    Environment removed at prefix: /home/myusername/micromamba/envs/foo

And then `ls -a ~/micromamba/envs/` shows that this environment does not exist anymore.

### mamba info / micromamba info

```shell
libmamba version : 1.5.9
     micromamba version : 1.5.9
           curl version : libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /home/myusername/micromamba/envs
          package cache : /home/myusername/micromamba/pkgs
                          /home/myusername/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /home/myusername/.mambarc
 populated config files : /home/myusername/.condarc
       virtual packages : __unix=0=0
                          __linux=6.10.6=0
                          __glibc=2.40=0
                          __archspec=1=x86_64-v3
               channels : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/myusername/micromamba
               platform : linux-64
```

### Logs

```
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/_libgcc_mutex-0.1-conda_forge.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/ca-certificates-2024.8.30-hbcca054_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libgomp-14.1.0-h77fa898_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/_openmp_mutex-4.5-2_gnu.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libgcc-14.1.0-h77fa898_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libexpat-2.6.3-h5888daf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libstdcxx-14.1.0-hc0a3c3a_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libgcc-ng-14.1.0-h69a702a_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/expat-2.6.3-h5888daf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libstdcxx-ng-14.1.0-h4852527_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/ncurses-6.5-he02047a_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxdmcp-1.1.3-h7f98852_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/pthread-stubs-0.4-h36c2ea0_1001.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-xproto-7.0.31-h7f98852_1007.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-kbproto-1.0.7-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-renderproto-0.11.1-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-recordproto-1.14.2-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-inputproto-2.3.2-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libev-4.33-hd590300_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xz-5.2.6-h166bdaf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libwebp-base-1.4.0-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-xextproto-7.3.0-h0b41bf4_1003.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libice-1.1.1-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxau-1.0.11-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/jpeg-9e-h0b41bf4_3.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libuuid-2.38.1-h0b41bf4_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libiconv-1.17-hd590300_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libffi-3.4.2-h7f98852_5.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/bzip2-1.0.8-h4bc722e_7.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/giflib-5.2.2-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/alsa-lib-1.2.3.2-h166bdaf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/openssl-1.1.1w-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libzlib-1.2.13-h4ab18f5_6.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/pixman-0.43.2-h59595ed_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/icu-68.2-h9c3ff4c_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/graphite2-1.3.13-h59595ed_1003.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libedit-3.1.20191231-he28a2e2_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-fixesproto-5.0-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libxcb-1.16-hb9d3cd8_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libsm-1.2.4-h7391055_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/zstd-1.5.6-ha6fb4c9_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libpng-1.6.43-h2797004_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/pcre2-10.43-hcad00b1_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libssh2-1.10.0-haa6b8db_3.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/tk-8.6.13-noxft_h4845f30_101.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/zlib-1.2.13-h4ab18f5_6.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libx11-1.8.9-hb711507_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/freetype-2.12.1-h267a509_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libglib-2.80.2-hf974151_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/krb5-1.17.2-h926e7f8_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libtiff-4.2.0-hf544144_3.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxrender-0.9.11-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxfixes-5.0.3-h7f98852_1004.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxext-1.3.4-h0b41bf4_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/fontconfig-2.14.2-h14ed4e7_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/lcms2-2.12-hddcbb42_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxi-1.7.10-h4bc722e_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/cairo-1.16.0-h6cf1ce9_1008.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxtst-1.2.5-h4bc722e_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/harfbuzz-2.9.1-h83ec7ef_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/openjdk-11.0.9.1-h5cc2fde_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/coreutils-8.25-1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/c-ares-1.11.0-h470a237_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libnghttp2-1.41.0-hab1572f_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libcurl-7.71.1-hcdd3856_8.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/curl-7.71.1-he644dc0_8.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/nextflow-24.04.4-hdfd78af_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/_libgcc_mutex-0.1-conda_forge.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/ca-certificates-2024.8.30-hbcca054_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libgomp-14.1.0-h77fa898_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/_openmp_mutex-4.5-2_gnu.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libgcc-14.1.0-h77fa898_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libexpat-2.6.3-h5888daf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libstdcxx-14.1.0-hc0a3c3a_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libgcc-ng-14.1.0-h69a702a_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/expat-2.6.3-h5888daf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libstdcxx-ng-14.1.0-h4852527_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/ncurses-6.5-he02047a_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxdmcp-1.1.3-h7f98852_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/pthread-stubs-0.4-h36c2ea0_1001.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-xproto-7.0.31-h7f98852_1007.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-kbproto-1.0.7-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-renderproto-0.11.1-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-recordproto-1.14.2-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-inputproto-2.3.2-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libev-4.33-hd590300_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xz-5.2.6-h166bdaf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libwebp-base-1.4.0-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-xextproto-7.3.0-h0b41bf4_1003.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libice-1.1.1-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxau-1.0.11-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/jpeg-9e-h0b41bf4_3.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libuuid-2.38.1-h0b41bf4_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libiconv-1.17-hd590300_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libffi-3.4.2-h7f98852_5.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/bzip2-1.0.8-h4bc722e_7.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/giflib-5.2.2-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/alsa-lib-1.2.3.2-h166bdaf_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/openssl-1.1.1w-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libzlib-1.2.13-h4ab18f5_6.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/pixman-0.43.2-h59595ed_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/icu-68.2-h9c3ff4c_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/graphite2-1.3.13-h59595ed_1003.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libedit-3.1.20191231-he28a2e2_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-fixesproto-5.0-h7f98852_1002.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libxcb-1.16-hb9d3cd8_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libsm-1.2.4-h7391055_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/zstd-1.5.6-ha6fb4c9_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libpng-1.6.43-h2797004_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/pcre2-10.43-hcad00b1_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libssh2-1.10.0-haa6b8db_3.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/tk-8.6.13-noxft_h4845f30_101.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/zlib-1.2.13-h4ab18f5_6.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libx11-1.8.9-hb711507_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/freetype-2.12.1-h267a509_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libglib-2.80.2-hf974151_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/krb5-1.17.2-h926e7f8_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libtiff-4.2.0-hf544144_3.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxrender-0.9.11-hd590300_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxfixes-5.0.3-h7f98852_1004.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxext-1.3.4-h0b41bf4_2.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/fontconfig-2.14.2-h14ed4e7_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/lcms2-2.12-hddcbb42_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxi-1.7.10-h4bc722e_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/cairo-1.16.0-h6cf1ce9_1008.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/xorg-libxtst-1.2.5-h4bc722e_0.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/harfbuzz-2.9.1-h83ec7ef_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/openjdk-11.0.9.1-h5cc2fde_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/coreutils-8.25-1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/c-ares-1.11.0-h470a237_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libnghttp2-1.41.0-hab1572f_1.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/libcurl-7.71.1-hcdd3856_8.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/curl-7.71.1-he644dc0_8.json"
info     libmamba Loading single package record: "/home/myusername/micromamba/envs/foo/conda-meta/nextflow-24.04.4-hdfd78af_0.json"
info     libmamba Adding package record to repo _libgcc_mutex
info     libmamba Adding package record to repo _openmp_mutex
info     libmamba Adding package record to repo alsa-lib
info     libmamba Adding package record to repo bzip2
info     libmamba Adding package record to repo c-ares
info     libmamba Adding package record to repo ca-certificates
info     libmamba Adding package record to repo cairo
info     libmamba Adding package record to repo coreutils
info     libmamba Adding package record to repo curl
info     libmamba Adding package record to repo expat
info     libmamba Adding package record to repo fontconfig
info     libmamba Adding package record to repo freetype
info     libmamba Adding package record to repo giflib
info     libmamba Adding package record to repo graphite2
info     libmamba Adding package record to repo harfbuzz
info     libmamba Adding package record to repo icu
info     libmamba Adding package record to repo jpeg
info     libmamba Adding package record to repo krb5
info     libmamba Adding package record to repo lcms2
info     libmamba Adding package record to repo libcurl
info     libmamba Adding package record to repo libedit
info     libmamba Adding package record to repo libev
info     libmamba Adding package record to repo libexpat
info     libmamba Adding package record to repo libffi
info     libmamba Adding package record to repo libgcc
info     libmamba Adding package record to repo libgcc-ng
info     libmamba Adding package record to repo libglib
info     libmamba Adding package record to repo libgomp
info     libmamba Adding package record to repo libiconv
info     libmamba Adding package record to repo libnghttp2
info     libmamba Adding package record to repo libpng
info     libmamba Adding package record to repo libssh2
info     libmamba Adding package record to repo libstdcxx
info     libmamba Adding package record to repo libstdcxx-ng
info     libmamba Adding package record to repo libtiff
info     libmamba Adding package record to repo libuuid
info     libmamba Adding package record to repo libwebp-base
info     libmamba Adding package record to repo libxcb
info     libmamba Adding package record to repo libzlib
info     libmamba Adding package record to repo ncurses
info     libmamba Adding package record to repo nextflow
info     libmamba Adding package record to repo openjdk
info     libmamba Adding package record to repo openssl
info     libmamba Adding package record to repo pcre2
info     libmamba Adding package record to repo pixman
info     libmamba Adding package record to repo pthread-stubs
info     libmamba Adding package record to repo tk
info     libmamba Adding package record to repo xorg-fixesproto
info     libmamba Adding package record to repo xorg-inputproto
info     libmamba Adding package record to repo xorg-kbproto
info     libmamba Adding package record to repo xorg-libice
info     libmamba Adding package record to repo xorg-libsm
info     libmamba Adding package record to repo xorg-libx11
info     libmamba Adding package record to repo xorg-libxau
info     libmamba Adding package record to repo xorg-libxdmcp
info     libmamba Adding package record to repo xorg-libxext
info     libmamba Adding package record to repo xorg-libxfixes
info     libmamba Adding package record to repo xorg-libxi
info     libmamba Adding package record to repo xorg-libxrender
info     libmamba Adding package record to repo xorg-libxtst
info     libmamba Adding package record to repo xorg-recordproto
info     libmamba Adding package record to repo xorg-renderproto
info     libmamba Adding package record to repo xorg-xextproto
info     libmamba Adding package record to repo xorg-xproto
info     libmamba Adding package record to repo xz
info     libmamba Adding package record to repo zlib
info     libmamba Adding package record to repo zstd
info     libmamba parsing history: "/home/myusername/micromamba/envs/foo/conda-meta/history"
info     libmamba Parsing MatchSpec nextflow
info     libmamba Parsing MatchSpec nextflow
info     libmamba Adding job: nextflow
info     libmamba Parsing MatchSpec _libgcc_mutex
info     libmamba Parsing MatchSpec _libgcc_mutex
info     libmamba Adding job: _libgcc_mutex
info     libmamba Parsing MatchSpec _openmp_mutex
info     libmamba Parsing MatchSpec _openmp_mutex
info     libmamba Adding job: _openmp_mutex
info     libmamba Parsing MatchSpec alsa-lib
info     libmamba Parsing MatchSpec alsa-lib
info     libmamba Adding job: alsa-lib
info     libmamba Parsing MatchSpec bzip2
info     libmamba Parsing MatchSpec bzip2
info     libmamba Adding job: bzip2
info     libmamba Parsing MatchSpec c-ares
info     libmamba Parsing MatchSpec c-ares
info     libmamba Adding job: c-ares
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Parsing MatchSpec ca-certificates
info     libmamba Adding job: ca-certificates
info     libmamba Parsing MatchSpec cairo
info     libmamba Parsing MatchSpec cairo
info     libmamba Adding job: cairo
info     libmamba Parsing MatchSpec coreutils
info     libmamba Parsing MatchSpec coreutils
info     libmamba Adding job: coreutils
info     libmamba Parsing MatchSpec curl
info     libmamba Parsing MatchSpec curl
info     libmamba Adding job: curl
info     libmamba Parsing MatchSpec expat
info     libmamba Parsing MatchSpec expat
info     libmamba Adding job: expat
info     libmamba Parsing MatchSpec fontconfig
info     libmamba Parsing MatchSpec fontconfig
info     libmamba Adding job: fontconfig
info     libmamba Parsing MatchSpec freetype
info     libmamba Parsing MatchSpec freetype
info     libmamba Adding job: freetype
info     libmamba Parsing MatchSpec giflib
info     libmamba Parsing MatchSpec giflib
info     libmamba Adding job: giflib
info     libmamba Parsing MatchSpec graphite2
info     libmamba Parsing MatchSpec graphite2
info     libmamba Adding job: graphite2
info     libmamba Parsing MatchSpec harfbuzz
info     libmamba Parsing MatchSpec harfbuzz
info     libmamba Adding job: harfbuzz
info     libmamba Parsing MatchSpec icu
info     libmamba Parsing MatchSpec icu
info     libmamba Adding job: icu
info     libmamba Parsing MatchSpec jpeg
info     libmamba Parsing MatchSpec jpeg
info     libmamba Adding job: jpeg
info     libmamba Parsing MatchSpec krb5
info     libmamba Parsing MatchSpec krb5
info     libmamba Adding job: krb5
info     libmamba Parsing MatchSpec lcms2
info     libmamba Parsing MatchSpec lcms2
info     libmamba Adding job: lcms2
info     libmamba Parsing MatchSpec libcurl
info     libmamba Parsing MatchSpec libcurl
info     libmamba Adding job: libcurl
info     libmamba Parsing MatchSpec libedit
info     libmamba Parsing MatchSpec libedit
info     libmamba Adding job: libedit
info     libmamba Parsing MatchSpec libev
info     libmamba Parsing MatchSpec libev
info     libmamba Adding job: libev
info     libmamba Parsing MatchSpec libexpat
info     libmamba Parsing MatchSpec libexpat
info     libmamba Adding job: libexpat
info     libmamba Parsing MatchSpec libffi
info     libmamba Parsing MatchSpec libffi
info     libmamba Adding job: libffi
info     libmamba Parsing MatchSpec libgcc
info     libmamba Parsing MatchSpec libgcc
info     libmamba Adding job: libgcc
info     libmamba Parsing MatchSpec libgcc-ng
info     libmamba Parsing MatchSpec libgcc-ng
info     libmamba Adding job: libgcc-ng
info     libmamba Parsing MatchSpec libglib
info     libmamba Parsing MatchSpec libglib
info     libmamba Adding job: libglib
info     libmamba Parsing MatchSpec libgomp
info     libmamba Parsing MatchSpec libgomp
info     libmamba Adding job: libgomp
info     libmamba Parsing MatchSpec libiconv
info     libmamba Parsing MatchSpec libiconv
info     libmamba Adding job: libiconv
info     libmamba Parsing MatchSpec libnghttp2
info     libmamba Parsing MatchSpec libnghttp2
info     libmamba Adding job: libnghttp2
info     libmamba Parsing MatchSpec libpng
info     libmamba Parsing MatchSpec libpng
info     libmamba Adding job: libpng
info     libmamba Parsing MatchSpec libssh2
info     libmamba Parsing MatchSpec libssh2
info     libmamba Adding job: libssh2
info     libmamba Parsing MatchSpec libstdcxx
info     libmamba Parsing MatchSpec libstdcxx
info     libmamba Adding job: libstdcxx
info     libmamba Parsing MatchSpec libstdcxx-ng
info     libmamba Parsing MatchSpec libstdcxx-ng
info     libmamba Adding job: libstdcxx-ng
info     libmamba Parsing MatchSpec libtiff
info     libmamba Parsing MatchSpec libtiff
info     libmamba Adding job: libtiff
info     libmamba Parsing MatchSpec libuuid
info     libmamba Parsing MatchSpec libuuid
info     libmamba Adding job: libuuid
info     libmamba Parsing MatchSpec libwebp-base
info     libmamba Parsing MatchSpec libwebp-base
info     libmamba Adding job: libwebp-base
info     libmamba Parsing MatchSpec libxcb
info     libmamba Parsing MatchSpec libxcb
info     libmamba Adding job: libxcb
info     libmamba Parsing MatchSpec libzlib
info     libmamba Parsing MatchSpec libzlib
info     libmamba Adding job: libzlib
info     libmamba Parsing MatchSpec ncurses
info     libmamba Parsing MatchSpec ncurses
info     libmamba Adding job: ncurses
info     libmamba Parsing MatchSpec nextflow
info     libmamba Parsing MatchSpec nextflow
info     libmamba Adding job: nextflow
info     libmamba Parsing MatchSpec openjdk
info     libmamba Parsing MatchSpec openjdk
info     libmamba Adding job: openjdk
info     libmamba Parsing MatchSpec openssl
info     libmamba Parsing MatchSpec openssl
info     libmamba Adding job: openssl
info     libmamba Parsing MatchSpec pcre2
info     libmamba Parsing MatchSpec pcre2
info     libmamba Adding job: pcre2
info     libmamba Parsing MatchSpec pixman
info     libmamba Parsing MatchSpec pixman
info     libmamba Adding job: pixman
info     libmamba Parsing MatchSpec pthread-stubs
info     libmamba Parsing MatchSpec pthread-stubs
info     libmamba Adding job: pthread-stubs
info     libmamba Parsing MatchSpec tk
info     libmamba Parsing MatchSpec tk
info     libmamba Adding job: tk
info     libmamba Parsing MatchSpec xorg-fixesproto
info     libmamba Parsing MatchSpec xorg-fixesproto
info     libmamba Adding job: xorg-fixesproto
info     libmamba Parsing MatchSpec xorg-inputproto
info     libmamba Parsing MatchSpec xorg-inputproto
info     libmamba Adding job: xorg-inputproto
info     libmamba Parsing MatchSpec xorg-kbproto
info     libmamba Parsing MatchSpec xorg-kbproto
info     libmamba Adding job: xorg-kbproto
info     libmamba Parsing MatchSpec xorg-libice
info     libmamba Parsing MatchSpec xorg-libice
info     libmamba Adding job: xorg-libice
info     libmamba Parsing MatchSpec xorg-libsm
info     libmamba Parsing MatchSpec xorg-libsm
info     libmamba Adding job: xorg-libsm
info     libmamba Parsing MatchSpec xorg-libx11
info     libmamba Parsing MatchSpec xorg-libx11
info     libmamba Adding job: xorg-libx11
info     libmamba Parsing MatchSpec xorg-libxau
info     libmamba Parsing MatchSpec xorg-libxau
info     libmamba Adding job: xorg-libxau
info     libmamba Parsing MatchSpec xorg-libxdmcp
info     libmamba Parsing MatchSpec xorg-libxdmcp
info     libmamba Adding job: xorg-libxdmcp
info     libmamba Parsing MatchSpec xorg-libxext
info     libmamba Parsing MatchSpec xorg-libxext
info     libmamba Adding job: xorg-libxext
info     libmamba Parsing MatchSpec xorg-libxfixes
info     libmamba Parsing MatchSpec xorg-libxfixes
info     libmamba Adding job: xorg-libxfixes
info     libmamba Parsing MatchSpec xorg-libxi
info     libmamba Parsing MatchSpec xorg-libxi
info     libmamba Adding job: xorg-libxi
info     libmamba Parsing MatchSpec xorg-libxrender
info     libmamba Parsing MatchSpec xorg-libxrender
info     libmamba Adding job: xorg-libxrender
info     libmamba Parsing MatchSpec xorg-libxtst
info     libmamba Parsing MatchSpec xorg-libxtst
info     libmamba Adding job: xorg-libxtst
info     libmamba Parsing MatchSpec xorg-recordproto
info     libmamba Parsing MatchSpec xorg-recordproto
info     libmamba Adding job: xorg-recordproto
info     libmamba Parsing MatchSpec xorg-renderproto
info     libmamba Parsing MatchSpec xorg-renderproto
info     libmamba Adding job: xorg-renderproto
info     libmamba Parsing MatchSpec xorg-xextproto
info     libmamba Parsing MatchSpec xorg-xextproto
info     libmamba Adding job: xorg-xextproto
info     libmamba Parsing MatchSpec xorg-xproto
info     libmamba Parsing MatchSpec xorg-xproto
info     libmamba Adding job: xorg-xproto
info     libmamba Parsing MatchSpec xz
info     libmamba Parsing MatchSpec xz
info     libmamba Adding job: xz
info     libmamba Parsing MatchSpec zlib
info     libmamba Parsing MatchSpec zlib
info     libmamba Adding job: zlib
info     libmamba Parsing MatchSpec zstd
info     libmamba Parsing MatchSpec zstd
info     libmamba Adding job: zstd
info     libmamba Problem count: 0
info     libmamba No python version given to TransactionContext, leaving it empty
Transaction

  Prefix: /home/myusername/micromamba/envs/foo

  Removing specs:

   - _libgcc_mutex
   - _openmp_mutex
   - alsa-lib
   - bzip2
   - c-ares
   - ca-certificates
   - cairo
   - coreutils
   - curl
   - expat
   - fontconfig
   - freetype
   - giflib
   - graphite2
   - harfbuzz
   - icu
   - jpeg
   - krb5
   - lcms2
   - libcurl
   - libedit
   - libev
   - libexpat
   - libffi
   - libgcc
   - libgcc-ng
   - libglib
   - libgomp
   - libiconv
   - libnghttp2
   - libpng
   - libssh2
   - libstdcxx
   - libstdcxx-ng
   - libtiff
   - libuuid
   - libwebp-base
   - libxcb
   - libzlib
   - ncurses
   - nextflow
   - openjdk
   - openssl
   - pcre2
   - pixman
   - pthread-stubs
   - tk
   - xorg-fixesproto
   - xorg-inputproto
   - xorg-kbproto
   - xorg-libice
   - xorg-libsm
   - xorg-libx11
   - xorg-libxau
   - xorg-libxdmcp
   - xorg-libxext
   - xorg-libxfixes
   - xorg-libxi
   - xorg-libxrender
   - xorg-libxtst
   - xorg-recordproto
   - xorg-renderproto
   - xorg-xextproto
   - xorg-xproto
   - xz
   - zlib
   - zstd


  Package                  Version  Build               Channel           Size
────────────────────────────────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────────────────────────────────

  - ncurses                    6.5  he02047a_1          conda-forge     Cached
  - nextflow               24.04.4  hdfd78af_0          bioconda        Cached
  - openjdk               11.0.9.1  h5cc2fde_1          conda-forge     Cached
  - curl                    7.71.1  he644dc0_8          conda-forge     Cached
  - coreutils                 8.25  1                   bioconda        Cached
  - xorg-libxtst             1.2.5  h4bc722e_0          conda-forge     Cached
  - lcms2                     2.12  hddcbb42_0          conda-forge     Cached
  - harfbuzz                 2.9.1  h83ec7ef_1          conda-forge     Cached
  - giflib                   5.2.2  hd590300_0          conda-forge     Cached
  - alsa-lib               1.2.3.2  h166bdaf_0          conda-forge     Cached
  - libcurl                 7.71.1  hcdd3856_8          conda-forge     Cached
  - xorg-recordproto        1.14.2  h7f98852_1002       conda-forge     Cached
  - xorg-libxi              1.7.10  h4bc722e_1          conda-forge     Cached
  - libtiff                  4.2.0  hf544144_3          conda-forge     Cached
  - graphite2               1.3.13  h59595ed_1003       conda-forge     Cached
  - cairo                   1.16.0  h6cf1ce9_1008       conda-forge     Cached
  - libssh2                 1.10.0  haa6b8db_3          conda-forge     Cached
  - libnghttp2              1.41.0  hab1572f_1          conda-forge     Cached
  - krb5                    1.17.2  h926e7f8_0          conda-forge     Cached
  - xorg-libxfixes           5.0.3  h7f98852_1004       conda-forge     Cached
  - xorg-inputproto          2.3.2  h7f98852_1002       conda-forge     Cached
  - zstd                     1.5.6  ha6fb4c9_0          conda-forge     Cached
  - xz                       5.2.6  h166bdaf_0          conda-forge     Cached
  - libwebp-base             1.4.0  hd590300_0          conda-forge     Cached
  - jpeg                        9e  h0b41bf4_3          conda-forge     Cached
  - xorg-libxrender         0.9.11  hd590300_0          conda-forge     Cached
  - xorg-libxext             1.3.4  h0b41bf4_2          conda-forge     Cached
  - xorg-libsm               1.2.4  h7391055_0          conda-forge     Cached
  - pixman                  0.43.2  h59595ed_0          conda-forge     Cached
  - libglib                 2.80.2  hf974151_0          conda-forge     Cached
  - icu                       68.2  h9c3ff4c_0          conda-forge     Cached
  - fontconfig              2.14.2  h14ed4e7_0          conda-forge     Cached
  - zlib                    1.2.13  h4ab18f5_6          conda-forge     Cached
  - libev                     4.33  hd590300_2          conda-forge     Cached
  - c-ares                  1.11.0  h470a237_1          bioconda        Cached
  - tk                      8.6.13  noxft_h4845f30_101  conda-forge     Cached
  - openssl                 1.1.1w  hd590300_0          conda-forge     Cached
  - libedit           3.1.20191231  he28a2e2_2          conda-forge     Cached
  - xorg-fixesproto            5.0  h7f98852_1002       conda-forge     Cached
  - xorg-renderproto        0.11.1  h7f98852_1002       conda-forge     Cached
  - xorg-libx11              1.8.9  hb711507_1          conda-forge     Cached
  - xorg-libice              1.1.1  hd590300_0          conda-forge     Cached
  - pcre2                    10.43  hcad00b1_0          conda-forge     Cached
  - libiconv                  1.17  hd590300_2          conda-forge     Cached
  - libffi                   3.4.2  h7f98852_5          conda-forge     Cached
  - libstdcxx-ng            14.1.0  h4852527_1          conda-forge     Cached
  - libuuid                 2.38.1  h0b41bf4_0          conda-forge     Cached
  - freetype                2.12.1  h267a509_2          conda-forge     Cached
  - expat                    2.6.3  h5888daf_0          conda-forge     Cached
  - ca-certificates      2024.8.30  hbcca054_0          conda-forge     Cached
  - xorg-xproto             7.0.31  h7f98852_1007       conda-forge     Cached
  - xorg-xextproto           7.3.0  h0b41bf4_1003       conda-forge     Cached
  - xorg-kbproto             1.0.7  h7f98852_1002       conda-forge     Cached
  - libxcb                    1.16  hb9d3cd8_1          conda-forge     Cached
  - bzip2                    1.0.8  h4bc722e_7          conda-forge     Cached
  - libstdcxx               14.1.0  hc0a3c3a_1          conda-forge     Cached
  - libpng                  1.6.43  h2797004_0          conda-forge     Cached
  - libexpat                 2.6.3  h5888daf_0          conda-forge     Cached
  - xorg-libxdmcp            1.1.3  h7f98852_0          conda-forge     Cached
  - xorg-libxau             1.0.11  hd590300_0          conda-forge     Cached
  - pthread-stubs              0.4  h36c2ea0_1001       conda-forge     Cached
  - libzlib                 1.2.13  h4ab18f5_6          conda-forge     Cached
  - libgcc-ng               14.1.0  h69a702a_1          conda-forge     Cached
  - libgcc                  14.1.0  h77fa898_1          conda-forge     Cached
  - _openmp_mutex              4.5  2_gnu               conda-forge     Cached
  - libgomp                 14.1.0  h77fa898_1          conda-forge     Cached
  - _libgcc_mutex              0.1  conda_forge         conda-forge     Cached

  Summary:

  Remove: 67 packages

  Total download: 0 B

────────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] n
Aborted.
Environment removed at prefix: /home/myusername/micromamba/envs/foo
```

### environment.yml

_No response_

### ~/.condarc

```yaml
channels:
  - bioconda
  - conda-forge
channel_priority: strict
auto_activate_base: false
```

### PR DESCRIPTION
**Pull request by jjerphan**
Fix #3437.

### CODE REVIEW

**Comment by Hind-M** [comment]
Can we add a test with the y/n answers and check removals?

**Review by SylvainCorlay — APPROVED** [review]

**Review by JohanMabille — APPROVED** [review]

File: libmamba/include/mamba/api/remove.hpp [hunk 1]
```diff
@@ -18,11 +18,18 @@ namespace mamba
     class ChannelContext;
     class Configuration;
 
-    void remove(Configuration& config, int flags = MAMBA_REMOVE_PRUNE);
+    enum RemoveResult
+    {
+        YES = 0,
+        NO = 1,
+        EMPTY = 2,
+    };
```
Comment (Hind-M) [inline libmamba/include/mamba/api/remove.hpp:26]: Prefer using:
```suggestion
    enum class RemoveResult : int
    {
        YES = 0,
        NO = 1,
        EMPTY = 2,
    };
```
to avoid implicit conversions.

**Comment by SylvainCorlay** [comment]
The test failure with pip & Numpy appears with other unrelated PRs and is unrelated to this change.

We are tracking this in a follow up PR.
