### PR TITLE
fix: Adapt root prefix' precedence for `envs_dirs`

### LINKED ISSUE #3806: `MAMBA_ROOT_PREFIX` has precedence over `-r` option
This issue was introduced by #3692:

In 2.0.5, `-r` took precedence over `MAMBA_ROOT_PREFIX`:

```
$ export MAMBA_ROOT_PREFIX=/tmp/envroot
$ mamba create  --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/envroot/envs"
]

$ mamba create -r /tmp/cliroot --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/cliroot/envs"
]
```

but in 2.0.6:
```
$ mamba create -r /tmp/cliroot --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/envroot/envs",
  "/tmp/cliroot/envs"
]
```

Note that this only is triggered if `/tmp/envroot/envs` already exists.

_Originally posted by @holzman in https://github.com/mamba-org/mamba/issues/3796#issuecomment-2637628296_

### PR DESCRIPTION
**Pull request by holzman**
Adds a new test and fixes #3806.  With this PR it now has the desired behavior:

```
$ mamba create -r /tmp/cliroot --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/cliroot/envs"
]

$ MAMBA_ROOT_PREFIX=/tmp/envroot mamba create --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/envroot/envs"
]

$ MAMBA_ROOT_PREFIX=/tmp/envroot mamba create -r /tmp/cliroot --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/cliroot/envs"
]

$ CONDA_ENVS_DIRS=/tmp/userdirs/envs MAMBA_ROOT_PREFIX=/tmp/envroot mamba create --debug -n foo --print-config-only | yq '. | .envs_dirs'
[
  "/tmp/userdirs/envs",
  "/tmp/envroot/envs"
]
```

One note - in order for this approach to work, I needed to ensure that the minimum vector size for configuration items was 1 so that `--print-config` didn't crash.  (Alternatively I could change the print-config code to ignore a zero-size vector, but this seemed like a more robust approach).

### CODE REVIEW

File: libmamba/include/mamba/api/configuration_impl.hpp
Comment (jjerphan) [inline libmamba/include/mamba/api/configuration_impl.hpp:1]:
```
pre-commit run --all
```

will reformat this file.

Comment (jjerphan) [inline libmamba/include/mamba/api/configuration_impl.hpp:1]:
```
pre-commit run --all
```

will reformat this file.

File: micromamba/tests/test_create.py
Comment (jjerphan) [inline micromamba/tests/test_create.py:1]: Can you add at least a test based on the outputs that you have given in the description of the PR?

**Review by jjerphan — COMMENTED** [review]
Thank you for your contribution, @holzman!

File: libmamba/include/mamba/api/configuration_impl.hpp
Comment (holzman) [reply libmamba/include/mamba/api/configuration_impl.hpp:1]: My bad - forgot to run the linters!

File: micromamba/tests/test_create.py
Comment (holzman) [reply micromamba/tests/test_create.py:1]: Done.

File: micromamba/tests/test_create.py [hunk 1]
```diff
@@ -661,6 +666,39 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+@pytest.mark.parametrize("cli_root_prefix", (False, True))
+@pytest.mark.parametrize("user_envs_dirs", (False, True))
+def test_root_prefix_precedence(monkeypatch, tmp_path, user_envs_dirs, cli_root_prefix):
+    """Test for root prefix precedence"""
+
+    envroot = tmp_path / "envroot"
+    cliroot = tmp_path / "cliroot"
+    userenv = tmp_path / "userenv" / "envs"
+
+    map(lambda p: os.makedirs(p), (envroot, cliroot, userenv))
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:678]: Is this required because of https://github.com/mamba-org/mamba/issues/3790?

```suggestion
    map(lambda p: os.makedirs(p, exist_ok=True), (envroot, cliroot, userenv))
```

File: micromamba/tests/test_create.py [hunk 2]
```diff
@@ -661,6 +666,39 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+
+    monkeypatch.setenv("MAMBA_ROOT_PREFIX", str(envroot))
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:680]: Can you set it at the really top of this test?

File: micromamba/tests/test_create.py [hunk 3]
```diff
@@ -661,6 +666,39 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+    cmd = ["mamba", "create", "-n", "foo", "--print-config-only", "--debug"]
+
+    if cli_root_prefix:
+        cmd += ["-r", cliroot]
+
+    if user_envs_dirs:
+        monkeypatch.setenv("CONDA_ENVS_DIRS", str(userenv))
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:687]: Identically, can you set it at the top of the test?

File: micromamba/tests/test_create.py [hunk 4]
```diff
@@ -661,6 +666,39 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
 
 
+@pytest.mark.parametrize("cli_root_prefix", (False, True))
+@pytest.mark.parametrize("user_envs_dirs", (False, True))
+def test_root_prefix_precedence(monkeypatch, tmp_path, user_envs_dirs, cli_root_prefix):
+    """Test for root prefix precedence"""
+
+    envroot = tmp_path / "envroot"
+    cliroot = tmp_path / "cliroot"
+    userenv = tmp_path / "userenv" / "envs"
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:676]: Can you distinguish the root prefix from their `envs` folders?

File: micromamba/tests/test_create.py [hunk 5]
```diff
@@ -661,6 +666,39 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+    monkeypatch.setenv("MAMBA_ROOT_PREFIX", str(envroot))
+    cmd = ["mamba", "create", "-n", "foo", "--print-config-only", "--debug"]
+
+    if cli_root_prefix:
+        cmd += ["-r", cliroot]
+
+    if user_envs_dirs:
+        monkeypatch.setenv("CONDA_ENVS_DIRS", str(userenv))
+
+    res = helpers.create(*cmd)
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:689]: Can you check that `foo` is successfully created and that, depending the test case, `foo` is created under `envroot/envs`, `cliroot/envs` or (after distinguishing prefixes from their `envs` folder) `userenv/envs`?

File: micromamba/tests/test_create.py [hunk 6]
```diff
@@ -277,6 +279,9 @@ def test_target_prefix(
     else:
         root_prefix = Path(os.environ["MAMBA_ROOT_PREFIX"])
 
+    if root_prefix_env_exists:
+        os.mkdir(Path(os.environ["MAMBA_ROOT_PREFIX"]) / "envs")
+
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:284]: Why is this needed?

Comment (jjerphan) [reply micromamba/tests/test_create.py:284]:
```suggestion
    # TODO: Remove once https://github.com/mamba-org/mamba/issues/3790 is fixed.
    if root_prefix_env_exists:
        os.mkdir(Path(os.environ["MAMBA_ROOT_PREFIX"]) / "envs", exist_ok=True)
```

File: micromamba/tests/test_create.py (hunk 4 above)
Comment (holzman) [reply micromamba/tests/test_create.py:676]: Sorry, I don't quite understand what you're asking.

File: micromamba/tests/test_create.py (hunk 5 above)
Comment (holzman) [reply micromamba/tests/test_create.py:689]: In addition to checking the output from `--print-config` or in addition to it?

File: micromamba/tests/test_create.py (hunk 1 above)
Comment (holzman) [reply micromamba/tests/test_create.py:678]: Yes

File: micromamba/tests/test_create.py (hunk 4 above)
Comment (jjerphan) [reply micromamba/tests/test_create.py:676]: I meant to have something like:
```suggestion
    envroot = tmp_path / "envroot"
    cliroot = tmp_path / "cliroot"
    userenv = tmp_path / "userenv"
    
    env_root_envs = envroot / "envs"
    cliroot_envs  = cliroot / "envs"
    userenv_envs  = userenv / "envs
```

File: micromamba/tests/test_create.py (hunk 5 above)
Comment (holzman) [reply micromamba/tests/test_create.py]: Ok, I did both.

**Comment by holzman** [comment]
Ok, I think I've addressed all of the issues, thanks for being so patient!

File: micromamba/tests/test_create.py [hunk 7]
```diff
@@ -661,6 +666,57 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+    monkeypatch, tmp_path, user_envs_dirs, cli_root_prefix, check_config
+):
+    """Test for root prefix precedence"""
+
+    envroot = tmp_path / "envroot"
+    envroot_envs = envroot / "envs"
+    cliroot = tmp_path / "cliroot"
+    cliroot_envs = cliroot / "envs"
+    userenv = tmp_path / "userenv"
+    userenv_envs = userenv / "envs"
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:682]: Actually, I think we need to properly clarify where those come from and their precedence, even if it is super verbose.

`CONDA_ENVS_DIR` directly points to the equivalent of an `envs` directory, so no need for a distinguishing for this one (my bad).

Also, the case of `envs_dir` from the configuration also needs to be treated I believe.

```suggestion
    # Environments can be created in several places depending, in this order:
    #   - 1. in the folder of `CONDA_ENVS_DIR` if it is set
    #   - 2. the root prefix given by the user's command (e.g. specified via the `-r` option)
    #   - 3. the usual root prefix (set generally by `MAMBA_ROOT_PREFIX`)

    # Given by `CONDA_ENVS_DIR`
    conda_envs_dir_envs = tmp_path / "conda_envs_dir_envs"

    # Given by `MAMBA_ROOT_PREFIX`
    mamba_root_prefix = tmp_path / "envroot"
    mamba_root_prefix_envs = envroot / "envs"

    # Given via the CLI
    cli_provided_root = tmp_path / "cliroot"
    cli_provided_root_envs = cli_provided_root / "envs"
```

If this suggestion is accepted, the rest of the test needs to be adapted accordingly.

**Review by jjerphan — COMMENTED** [review]
Thank you for your patience.

File: micromamba/tests/test_create.py (hunk 7 above)
Comment (holzman) [reply micromamba/tests/test_create.py]: I've made these changes, added a test for when `envs_dirs` is set in the .condarc file, and made the test a bit clearer (hopefully).

Comment (jjerphan) [reply micromamba/tests/test_create.py]: Thank you!

File: micromamba/tests/test_create.py [hunk 8]
```diff
@@ -277,6 +279,9 @@ def test_target_prefix(
     else:
         root_prefix = Path(os.environ["MAMBA_ROOT_PREFIX"])
 
+    if root_prefix_env_exists:
+        os.makedirs(Path(os.environ["MAMBA_ROOT_PREFIX"]) / "envs", exist_ok=True)
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:283]:
```suggestion
    # TODO: Remove this call to `os.makedirs` once
    # https://github.com/mamba-org/mamba/issues/3790 is fixed
    if root_prefix_env_exists:
        os.makedirs(Path(os.environ["MAMBA_ROOT_PREFIX"]) / "envs", exist_ok=True)
```

File: micromamba/tests/test_create.py [hunk 9]
```diff
@@ -661,6 +666,89 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+    env_name = "foo"
+    monkeypatch.setenv("MAMBA_ROOT_PREFIX", str(mamba_root_prefix))
+    if set_in_conda_envs_dirs:
+        monkeypatch.setenv("CONDA_ENVS_DIRS", str(conda_envs_dirs))
+
+    with open(tmp_home / ".condarc", "w+") as f:
+        if set_in_condarc:
+            f.write(f"envs_dirs: [{str(condarc_envs_dirs)}]")
+
+    for envs_folder in (condarc_envs_dirs, conda_envs_dirs, cli_provided_root, mamba_root_prefix):
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:712]:
```suggestion
    # TODO: Remove those calls to `os.makedirs` once
    # https://github.com/mamba-org/mamba/issues/3790 is fixed
    for envs_folder in (condarc_envs_dirs, conda_envs_dirs, cli_provided_root, mamba_root_prefix):
```

File: micromamba/tests/test_create.py [hunk 10]
```diff
@@ -661,6 +666,89 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+        assert envs_dirs == [str(env_dir) for env_dir in expected_envs_dirs]
+
+    elif set_in_conda_envs_dirs:
+        assert_env_exists(conda_envs_dirs)
+    elif set_in_condarc:
+        assert_env_exists(condarc_envs_dirs)
+    elif cli_root_prefix:
+        assert_env_exists(cli_provided_root_envs)
+    else:
+        assert_env_exists(mamba_root_prefix_envs)
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:749]: Way nicer. Thank you!

File: micromamba/tests/test_create.py [hunk 11]
```diff
@@ -661,6 +666,89 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+        if set_in_conda_envs_dirs:
+            expected_envs_dirs.append(conda_envs_dirs)
+        if set_in_condarc:
+            expected_envs_dirs.append(condarc_envs_dirs)
+        if cli_root_prefix:
+            expected_envs_dirs.append(cli_provided_root_envs)
+        else:
+            expected_envs_dirs.append(mamba_root_prefix_envs)
+        assert envs_dirs == [str(env_dir) for env_dir in expected_envs_dirs]
+
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:741]:
```suggestion
    # Otherwise, we check that `foo` has been created in the directory
    # based on precedence given above.
```

File: micromamba/tests/test_create.py [hunk 12]
```diff
@@ -661,6 +666,89 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+        if set_in_conda_envs_dirs:
+            expected_envs_dirs.append(conda_envs_dirs)
+        if set_in_condarc:
+            expected_envs_dirs.append(condarc_envs_dirs)
+        if cli_root_prefix:
+            expected_envs_dirs.append(cli_provided_root_envs)
+        else:
+            expected_envs_dirs.append(mamba_root_prefix_envs)
+        assert envs_dirs == [str(env_dir) for env_dir in expected_envs_dirs]
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:740]:
```suggestion
        expected_envs_dirs = []

        if set_in_conda_envs_dirs:
            expected_envs_dirs.append(str(conda_envs_dirs))
        if set_in_condarc:
            expected_envs_dirs.append(str(condarc_envs_dirs))
        
        if cli_root_prefix:
            expected_envs_dirs.append(str(cli_provided_root_envs))
        else:
            expected_envs_dirs.append(str(mamba_root_prefix_envs))

        effective_envs_dirs = res["envs_dirs"]
        assert effective_envs_dirs == expected_envs_dirs
```

File: micromamba/tests/test_create.py [hunk 13]
```diff
@@ -661,6 +666,89 @@ def test_create_envs_dirs(tmp_root_prefix: Path, tmp_path: Path):
...
+@pytest.mark.parametrize("cli_root_prefix", (False, True))
+@pytest.mark.parametrize("check_config", (False, True))
+def test_root_prefix_precedence(
+    tmp_path,
+    tmp_home,
+    monkeypatch,
+    set_in_condarc,
+    set_in_conda_envs_dirs,
+    cli_root_prefix,
+    check_config,
```
Comment (jjerphan) [inline micromamba/tests/test_create.py:680]: To be slightly more explicit and precise
```suggestion
    check_config_only,
```

**Review by jjerphan — APPROVED** [review]
Thank you, @holzman!

I just have a couple of nitpicks but apart from them, the test covers all the cases.

I would wait for another approval from someone in the team before merging this contribution.

**Comment by holzman** [comment]
Ok, I've added one more commit to address the nits.  (Now I'm off to write a better test for #3796).

**Review by Klaim — APPROVED** [review]
LGTM (didnt test locally though)

**Review by Hind-M — APPROVED** [review]
