### PR TITLE
Fix add missing pip PREREQ_MARKER

### LINKED ISSUE #2546: critical libmamba permissions: The system cannot find the path specified.: "testenv\Scripts\pip.exe"
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

critical libmamba permissions: The system cannot find the path specified

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

This command:
```
micromamba create -y -p ./testenv -c conda-forge pip
```
produces this error:
```
error    libmamba Error opening for writing "testenv\\Scripts\\pip-script.py": No such file or directory
error    libmamba Error opening for writing "testenv\\Scripts\\pip.exe": No such file or directory
critical libmamba permissions: The system cannot find the path specified.: "testenv\Scripts\pip.exe"
```

It appears to only occur with micromamba v1.4.3 (the latest version on conda-forge) on Windows.

I have observed it locally, in CI and I've had a couple of bug reports with the same issue on a package of mine which depends on micromamba.

### mamba info / micromamba info

```shell
__
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : None (not found)
           env location : -
      user config files : C:\Users\chris\.mambarc
 populated config files :
       libmamba version : 1.4.3
     micromamba version : 1.4.3
           curl version : libcurl/7.86.0-DEV Schannel zlib/1.2.13
     libarchive version : libarchive 3.6.1 zlib/1.2.13 liblzma/5.4.0 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __win=0=0
                          __archspec=1=x86_64
                          __cuda=10.1=0
               channels :
       base environment : C:\Users\chris\AppData\Local\micromamba\root
               platform : win-64
```

### Logs

```shell
__
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache

Transaction

  Prefix: testenv

  Updating specs:

   - pip


  Package                 Version  Build               Channel           Size
-------------------------------------------------------------------------------
  Install:
-------------------------------------------------------------------------------

  + bzip2                   1.0.8  h8ffe710_4          conda-forge     Cached
  + ca-certificates      2023.5.7  h56e8100_0          conda-forge     Cached
  + libexpat                2.5.0  h63175ca_1          conda-forge     Cached
  + libffi                  3.4.2  h8ffe710_5          conda-forge     Cached
  + libsqlite              3.42.0  hcfcfb64_0          conda-forge     Cached
  + libzlib                1.2.13  hcfcfb64_4          conda-forge     Cached
  + openssl                 3.1.0  hcfcfb64_3          conda-forge     Cached
  + pip                    23.1.2  pyhd8ed1ab_0        conda-forge     Cached
  + python                 3.11.3  h2628c8c_0_cpython  conda-forge     Cached
  + setuptools             67.7.2  pyhd8ed1ab_0        conda-forge     Cached
  + tk                     8.6.12  h8ffe710_0          conda-forge     Cached
  + tzdata                  2023c  h71feb2d_0          conda-forge     Cached
  + ucrt             10.0.22621.0  h57928b3_0          conda-forge     Cached
  + vc                       14.3  hb25d44b_16         conda-forge     Cached
  + vc14_runtime      14.34.31931  h5081d32_16         conda-forge     Cached
  + vs2015_runtime    14.34.31931  hed1258a_16         conda-forge     Cached
  + wheel                  0.40.0  pyhd8ed1ab_0        conda-forge     Cached
  + xz                      5.2.6  h8d14728_0          conda-forge     Cached

  Summary:

  Install: 18 packages

  Total download: 0 B

-------------------------------------------------------------------------------



Transaction starting
Linking libexpat-2.5.0-h63175ca_1
Linking ucrt-10.0.22621.0-h57928b3_0
Linking ca-certificates-2023.5.7-h56e8100_0
Linking vc14_runtime-14.34.31931-h5081d32_16
Linking vc-14.3-hb25d44b_16
Linking vs2015_runtime-14.34.31931-hed1258a_16
Linking libsqlite-3.42.0-hcfcfb64_0
Linking openssl-3.1.0-hcfcfb64_3
Linking libffi-3.4.2-h8ffe710_5
Linking bzip2-1.0.8-h8ffe710_4
Linking xz-5.2.6-h8d14728_0
Linking tk-8.6.12-h8ffe710_0
Linking libzlib-1.2.13-hcfcfb64_4
Linking tzdata-2023c-h71feb2d_0
Linking pip-23.1.2-pyhd8ed1ab_0
error    libmamba Error opening for writing "testenv\\Scripts\\pip-script.py": No such file or directory
error    libmamba Error opening for writing "testenv\\Scripts\\pip.exe": No such file or directory
critical libmamba permissions: The system cannot find the path specified.: "testenv\Scripts\pip.exe"
```

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by AntoinePrv**
Fix bug introduced in #2453
Close #2546

### CODE REVIEW

File: libmamba/src/solv-cpp/solvable.cpp [hunk 1]
```diff
@@ -349,37 +349,32 @@ namespace mamba::solv
...
 
     auto ObjSolvableViewConst::provides() const -> ObjQueue
     {
         auto q = ObjQueue{};
-        ::solvable_lookup_deparray(const_cast<::Solvable*>(raw()), SOLVABLE_PROVIDES, q.raw(), -1);
+        ::solvable_lookup_deparray(
+            const_cast<::Solvable*>(raw()),
+            SOLVABLE_PROVIDES,
+            q.raw(),
+            /* marker= */ -1
```
Comment (wolfv) [inline libmamba/src/solv-cpp/solvable.cpp:376]: Do we know why we need this magic number here?

Comment (AntoinePrv) [reply libmamba/src/solv-cpp/solvable.cpp:376]: This was only reformated by I believe this magic number was already present pre-refactoring.

The idea is that dep array can be split in to with a magic marker. When retrieving the dependencies, `-1` means first part, `1` means second and 0 means everything, including said marker (which is not a valid dependency).
That works if the default maker was used when setting the dependencies...
So yes, a bit of a mess.

See also the test case added in this PR. So far we have no need for markers in `provide` key so we keep sane defaults.

**Review by JohanMabille — APPROVED** [review]
