### PR TITLE
Simple logging fix

### LINKED ISSUE #3112: Trace and debug log levels don't work
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

log-level trace debug

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Providing `--log-level trace` to micromamba doesn't seem to get any trace or debug logs. I tried changing [this line](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/subdirdata.cpp#L581) to a `LOG_DEBUG` and `LOG_TRACE` just to make sure and the result is that nothing is logged.

### mamba info / micromamba info

_No response_

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by AntoinePrv**
Fix logging when libmamba is used as a lib without context.
The proper way would be to set logging sinks that get configured in micromamba or any other client code.

Close #2713
Close #3112

### CODE REVIEW

File: libmamba/include/mamba/core/output.hpp [hunk 1]
```diff
@@ -124,6 +124,7 @@ namespace mamba
         Console& operator=(Console&&) = delete;
 
         static Console& instance();
+        static bool has_instance();
```
Comment (Klaim) [inline libmamba/include/mamba/core/output.hpp:127]: I would prefer `is_available` as it would match better the functionality and would be less "I know it's a singleton..."

**Review by Klaim — APPROVED** [review]
