### PR TITLE
Fix #1386 and #1387 and remove dead code

### LINKED ISSUE #1386: Micromamba crashes with missing `CONDARC` file
```
$ CONDARC=bla micromamba
libc++abi: terminating with uncaught exception of type std::runtime_error: Aborting.
fish: Job 1, 'CONDARC=bla micromamba' terminated by signal SIGABRT (Abort)
```

### PR DESCRIPTION
**Pull request by jonashaag**
Smaller version of https://github.com/mamba-org/mamba/pull/1411

### CODE REVIEW

File: micromamba/src/main.cpp [hunk 1]
```diff
@@ -70,29 +70,28 @@ main(int argc, char** argv)
...
         set_sig_interrupted();
-        reset_console();
-        return 1;
-    }
-
-    if (app.get_subcommands().size() == 0)
-    {
-        Configuration::instance().load();
-        Console::print(app.help());
+        err = false;
```
Comment (jonashaag) [inline micromamba/src/main.cpp:93]:
```suggestion
        err = true;
```

**Comment by wolfv** [comment]
Awesome, thanks!
