### PR TITLE
Fix libsolv MatchSpec parsing

### LINKED ISSUE #4018: Solver error when combining wildcard python dependency and pinned test version
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

yes

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

Originally reported in https://github.com/conda/conda-libmamba-solver/issues/677

> requirements:
>   [...]
>   run:
>     - python *
> 
> test:
>   requires:
>     # test that we can still use python_min (i.e. haven't picked up too-tight constraint somehow)
>     - python {{ python_min }}.*
> 
> The overall constraint python * is correct (we need the asterisk to avoid building for several python versions when picking up the global pinning), and likewise, and this should not be in conflict with depending on a specific python version later.
> 
> However, this currently runs into
> 
> conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("python[version='*,=3.9.*']")}
> Encountered problems while solving:
>   - unsupported request
> 
> Could not solve for environment specs
> The following package could not be installed
> └─ python =*,=3.9 * does not exist (perhaps a typo or a missing channel).
> 

A reproducer using `micromamba`:

```
$ micromamba create --dry-run "python[version='*,=3.12.*']" -c conda-forge --platform=linux-64 -p /tmp
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.

warning  libmamba Please make sure you understand Anaconda Terms of Services.

warning  libmamba See: https://legal.anaconda.com/policies/en/
nodefaults/linux-64                                 ??.?MB @  ??.?MB/s  0.2s
nodefaults/noarch                                  116.0 B @ 593.0 B/s  0.2s

error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ python =*,=3.12 * does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

Same command using `micromamba-1.5.11`:
```
$ micromamba create --dry-run "python[version='*,=3.12.*']" -c conda-forge --platform=linux-64 -p /tmp
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
nodefaults/linux-64                                         Using cache
nodefaults/noarch                                           Using cache
pkgs/main/linux-64 (check zst)                      Checked  0.1s
pkgs/r/noarch (check zst)                          Checked  0.1s
pkgs/main/noarch (check zst)                        Checked  0.1s
pkgs/r/linux-64 (check zst)                        Checked  0.1s
pkgs/r/linux-64                                      1.6MB @  12.9MB/s  0.1s
pkgs/r/noarch                                        2.0MB @  13.1MB/s  0.2s
pkgs/main/noarch                                   770.2kB @   4.6MB/s  0.2s
pkgs/main/linux-64                                   7.9MB @  33.0MB/s  0.3s

Transaction

  Prefix: /tmp

  Updating specs:

   - python[version='*,=3.12.*']


  Package               Version  Build               Channel          Size
────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────

  + ld_impl_linux-64       2.44  h1423503_1          conda-forge     676kB
  + _libgcc_mutex           0.1  conda_forge         conda-forge       3kB
  + libgomp              15.1.0  h767d61c_3          conda-forge     447kB
  + _openmp_mutex           4.5  2_gnu               conda-forge      24kB
  + libgcc               15.1.0  h767d61c_3          conda-forge     825kB
  + libstdcxx            15.1.0  h8f9b012_3          conda-forge       4MB
  + ncurses                 6.5  h2d0b736_3          conda-forge     892kB
  + libzlib               1.3.1  hb9d3cd8_2          conda-forge      61kB
  + libnsl                2.0.1  hb9d3cd8_1          conda-forge      34kB
  + liblzma               5.8.1  hb9d3cd8_2          conda-forge     113kB
  + libgcc-ng            15.1.0  h69a702a_3          conda-forge      29kB
  + libffi                3.4.6  h2dba641_1          conda-forge      57kB
  + libexpat              2.7.1  hecca717_0          conda-forge      75kB
  + libstdcxx-ng         15.1.0  h4852527_3          conda-forge      29kB
  + readline                8.2  h8c095d6_2          conda-forge     282kB
  + tk                   8.6.13  noxft_hd72426e_102  conda-forge       3MB
  + libxcrypt            4.4.36  hd590300_1          conda-forge     100kB
  + bzip2                 1.0.8  h4bc722e_7          conda-forge     253kB
  + libuuid              2.38.1  h0b41bf4_0          conda-forge      34kB
  + icu                    75.1  he02047a_0          conda-forge      12MB
  + libsqlite            3.50.2  hee844dc_2          conda-forge     936kB
  + tzdata                2025b  h78e105d_0          conda-forge     123kB
  + ca-certificates   2025.7.14  hbd8a1cb_0          conda-forge     156kB
  + openssl               3.5.1  h7b32b05_0          conda-forge       3MB
  + python              3.12.11  h9e4cc4f_0_cpython  conda-forge      31MB
  + wheel                0.45.1  pyhd8ed1ab_1        conda-forge      63kB
  + setuptools           80.9.0  pyhff2d567_0        conda-forge     749kB
  + pip                  25.1.1  pyh8b19718_0        conda-forge       1MB

  Summary:

  Install: 28 packages

  Total download: 61MB

────────────────────────────────────────────────────────────────────────────


Dry run. Not executing the transaction.
```

### mamba info / micromamba info

```shell
$ micromamba info

       libmamba version : 2.3.0
     micromamba version : 2.3.0
           curl version : libcurl/8.14.1 OpenSSL/3.5.0 zlib/1.3.1 zstd/1.5.7 libssh2/1.11.1 nghttp2/1.64.0
     libarchive version : libarchive 3.8.1 zlib/1.3.1 bz2lib/1.0.8 libzstd/1.5.7 libb2/bundled
       envs directories : /home/jsmolic/micromamba/envs
          package cache : /home/jsmolic/micromamba/pkgs
                          /home/jsmolic/.mamba/pkgs
            environment : /home/jsmolic/miniforge3 (active)
           env location : /home/jsmolic/miniforge3
      user config files : /home/jsmolic/.mambarc
 populated config files : /home/jsmolic/miniforge3/.condarc
                          /home/jsmolic/.condarc
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.39=0
                          __archspec=1=x86_64_v3
                          __cuda=12.6=0
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /home/jsmolic/micromamba
               platform : linux-64
```

### Logs

```shell
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
trace    libmamba Configuration not found at '/home/jsmolic/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.mamba/mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.mamba/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.config/mamba/mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/mamba/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/miniforge3/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/miniforge3/condarc'
trace    libmamba Configuration found at '/home/jsmolic/miniforge3/.condarc'
trace    libmamba Configuration found at '/home/jsmolic/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.conda/condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.conda/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/conda/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.config/conda/condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/conda/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/condarc'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'envs_dirs'
trace    libmamba Compute configurable 'file_specs'
trace    libmamba Compute configurable 'spec_file_env_name'
trace    libmamba Compute configurable 'env_name'
trace    libmamba Compute configurable 'use_default_prefix_fallback'
trace    libmamba Compute configurable 'use_root_prefix_fallback'
trace    libmamba Compute configurable 'use_target_prefix_fallback'
trace    libmamba Compute configurable 'target_prefix'
trace    libmamba Get RC files configuration from locations up to TargetPrefix
trace    libmamba Configuration not found at '/tmp/.mambarc'
trace    libmamba Configuration not found at '/tmp/condarc.d'
trace    libmamba Configuration not found at '/tmp/condarc'
trace    libmamba Configuration not found at '/tmp/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.mamba/mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.mamba/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/mamba/mambarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.config/mamba/mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/mamba/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/miniforge3/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/miniforge3/condarc'
trace    libmamba Configuration found at '/home/jsmolic/miniforge3/.condarc'
trace    libmamba Configuration found at '/home/jsmolic/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.conda/condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.conda/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/conda/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/.config/conda/condarc'
trace    libmamba Configuration not found at '/home/jsmolic/.config/conda/.condarc'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/.mambarc'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/condarc.d'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/condarc'
trace    libmamba Configuration not found at '/home/jsmolic/micromamba/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'relocate_prefix'
trace    libmamba Compute configurable 'target_prefix_checks'
trace    libmamba Compute configurable 'pkgs_dirs'
trace    libmamba Compute configurable 'platform'
trace    libmamba Compute configurable 'spec_file_env_vars'
trace    libmamba Compute configurable 'specs'
trace    libmamba Compute configurable 'others_pkg_mgrs_specs'
trace    libmamba Compute configurable 'experimental'
trace    libmamba Compute configurable 'experimental_repodata_parsing'
trace    libmamba Compute configurable 'experimental_matchspec_parsing'
trace    libmamba Compute configurable 'debug'
trace    libmamba Compute configurable 'override_channels_enabled'
trace    libmamba Compute configurable 'override_channels'
trace    libmamba Compute configurable 'channels'
trace    libmamba Compute configurable 'channel_alias'
trace    libmamba Compute configurable 'default_channels'
trace    libmamba Compute configurable 'custom_channels'
trace    libmamba Compute configurable 'custom_multichannels'
trace    libmamba Compute configurable 'mirrored_channels'
trace    libmamba Compute configurable 'repodata_use_zst'
trace    libmamba Compute configurable 'repodata_has_zst'
trace    libmamba Compute configurable 'cacert_path'
trace    libmamba Compute configurable 'local_repodata_ttl'
trace    libmamba Compute configurable 'offline'
trace    libmamba Compute configurable 'ssl_no_revoke'
trace    libmamba Compute configurable 'ssl_verify'
trace    libmamba Compute configurable 'proxy_servers'
trace    libmamba Compute configurable 'remote_connect_timeout_secs'
trace    libmamba Compute configurable 'remote_backoff_factor'
trace    libmamba Compute configurable 'remote_max_retries'
trace    libmamba Compute configurable 'no_channel_priority'
trace    libmamba Compute configurable 'strict_channel_priority'
trace    libmamba Compute configurable 'channel_priority'
trace    libmamba Compute configurable 'explicit_install'
trace    libmamba Compute configurable 'no_pin'
trace    libmamba Compute configurable 'no_py_pin'
trace    libmamba Compute configurable 'add_pip_as_python_dependency'
trace    libmamba Compute configurable 'pinned_packages'
trace    libmamba Compute configurable 'freeze_installed'
trace    libmamba Compute configurable 'no_deps'
trace    libmamba Compute configurable 'only_deps'
trace    libmamba Compute configurable 'force_reinstall'
trace    libmamba Compute configurable 'allow_uninstall'
trace    libmamba Compute configurable 'allow_downgrade'
trace    libmamba Compute configurable 'order_solver_request'
trace    libmamba Compute configurable 'categories'
trace    libmamba Compute configurable 'retry_clean_cache'
trace    libmamba Compute configurable 'download_threads'
trace    libmamba Compute configurable 'extract_threads'
trace    libmamba Compute configurable 'allow_softlinks'
trace    libmamba Compute configurable 'always_copy'
trace    libmamba Compute configurable 'always_softlink'
trace    libmamba Compute configurable 'show_anaconda_channel_warnings'
trace    libmamba Compute configurable 'shortcuts'
trace    libmamba Compute configurable 'safety_checks'
trace    libmamba Compute configurable 'extra_safety_checks'
trace    libmamba Compute configurable 'verify_artifacts'
trace    libmamba Compute configurable 'trusted_channels'
trace    libmamba Compute configurable 'lock_timeout'
trace    libmamba Compute configurable 'use_lockfiles'
trace    libmamba Compute configurable 'compile_pyc'
trace    libmamba Compute configurable 'use_uv'
trace    libmamba Compute configurable 'always_yes'
trace    libmamba Compute configurable 'auto_activate_base'
trace    libmamba Compute configurable 'dry_run'
trace    libmamba Compute configurable 'download_only'
trace    libmamba Compute configurable 'print_config_only'
trace    libmamba Compute configurable 'print_context_only'
trace    libmamba Compute configurable 'json'
trace    libmamba Compute configurable 'verbose'
trace    libmamba Compute configurable 'log_level'
trace    libmamba Compute configurable 'log_backtrace'
trace    libmamba Compute configurable 'log_pattern'
trace    libmamba Compute configurable 'changeps1'
trace    libmamba Compute configurable 'shell_completion'
trace    libmamba Compute configurable 'env_prompt'
trace    libmamba Compute configurable 'show_all_configs'
trace    libmamba Compute configurable 'show_all_rc_configs'
trace    libmamba Compute configurable 'show_config_descriptions'
trace    libmamba Compute configurable 'show_config_groups'
trace    libmamba Compute configurable 'show_config_long_descriptions'
trace    libmamba Compute configurable 'show_config_sources'
trace    libmamba Compute configurable 'show_config_values'
trace    libmamba Compute configurable 'quiet'
trace    libmamba Compute configurable 'override_rc_files'
trace    libmamba Compute configurable 'shell_type'
trace    libmamba Compute configurable 'prefix_or_name'
trace    libmamba Compute configurable 'shell_stack'
trace    libmamba Compute configurable 'list_regex'
trace    libmamba Compute configurable 'full_name'
trace    libmamba Compute configurable 'no_pip'
trace    libmamba Compute configurable 'reverse'
trace    libmamba Compute configurable 'explicit'
trace    libmamba Compute configurable 'md5'
trace    libmamba Compute configurable 'sha256'
trace    libmamba Compute configurable 'canonical'
trace    libmamba Compute configurable 'export'
trace    libmamba Compute configurable 'revisions'
trace    libmamba Compute configurable 'clean_all'
trace    libmamba Compute configurable 'clean_index_cache'
trace    libmamba Compute configurable 'clean_packages'
trace    libmamba Compute configurable 'clean_tarballs'
trace    libmamba Compute configurable 'clean_locks'
trace    libmamba Compute configurable 'clean_trash'
trace    libmamba Compute configurable 'clean_force_pkgs_dirs'
trace    libmamba Compute configurable 'config_set_system_path'
trace    libmamba Compute configurable 'config_set_env_path'
trace    libmamba Compute configurable 'config_set_file_path'
trace    libmamba Compute configurable 'config_set_sequence_spec'
trace    libmamba Compute configurable 'remove_key'
trace    libmamba Compute configurable 'remove'
trace    libmamba Compute configurable 'set_value'
trace    libmamba Compute configurable 'get_value'
trace    libmamba Compute configurable 'print_licenses'
trace    libmamba Compute configurable 'base'
trace    libmamba Compute configurable 'environments'
trace    libmamba Compute configurable 'constructor_prefix'
trace    libmamba Compute configurable 'constructor_extract_conda_pkgs'
trace    libmamba Compute configurable 'constructor_extract_tarball'
debug    libmamba 132 configurables computed
debug    libmamba Checking if '/home/jsmolic/micromamba/pkgs' is writable
trace    libmamba '/home/jsmolic/micromamba/pkgs/urls.txt' exists, checking if writable
debug    libmamba '/home/jsmolic/micromamba/pkgs' writable
info     libmamba Searching index cache file for repo 'conda-forge/linux-64'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 111/1200s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 103s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'conda-forge/linux-64': 1
conda-forge/linux-64                                        Using cache
info     libmamba Searching index cache file for repo 'conda-forge/noarch'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 112/1200s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 100s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'conda-forge/noarch': 1
conda-forge/noarch                                          Using cache
warning  libmamba 'repo.anaconda.com', a commercial channel hosted by Anaconda.com, is used.
    
warning  libmamba Please make sure you understand Anaconda Terms of Services.
    
warning  libmamba See: https://legal.anaconda.com/policies/en/
info     libmamba Searching index cache file for repo 'pkgs/main/linux-64'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 22/30s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 22s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'pkgs/main/linux-64': 1
pkgs/main/linux-64                                          Using cache
info     libmamba Searching index cache file for repo 'pkgs/main/noarch'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 22/30s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 22s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'pkgs/main/noarch': 1
pkgs/main/noarch                                            Using cache
info     libmamba Searching index cache file for repo 'pkgs/r/linux-64'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 22/30s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 22s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'pkgs/r/linux-64': 1
pkgs/r/linux-64                                             Using cache
info     libmamba Searching index cache file for repo 'pkgs/r/noarch'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 22/30s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 22s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'pkgs/r/noarch': 1
pkgs/r/noarch                                               Using cache
info     libmamba Searching index cache file for repo 'nodefaults/linux-64'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 22/60s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 19s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'nodefaults/linux-64': 1
nodefaults/linux-64                                         Using cache
info     libmamba Searching index cache file for repo 'nodefaults/noarch'
debug    libmamba Locking directory '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
trace    libmamba Cache age: 22/60s
debug    libmamba Using SOLV cache
trace    libmamba Cache age: 19s
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cache.lock'
info     libmamba Valid cache found  for 'nodefaults/noarch': 1
nodefaults/noarch                                           Using cache
info     libmamba Using OpenSSL backend
trace    libmamba Using root prefix set in `MAMBA_ROOT_PREFIX`: "/home/jsmolic/micromamba"
info     libmamba Checking for CA certificates at the root prefix: "/home/jsmolic/micromamba/ssl/cacert.pem"
info     libmamba Using system CA certificates at: /etc/ssl/certs/ca-certificates.crt
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/88ec62ec.solv" for repo https://conda.anaconda.org/conda-forge/linux-64
info     libmamba Expecting solv metadata : {"etag":"\"f999f34cb21c539db34b83f3e0d38d79\"","mod":"Thu, 17 Jul 2025 15:44:35 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/conda-forge/linux-64"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/88ec62ec.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/88ec62ec.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"\"f999f34cb21c539db34b83f3e0d38d79\"","mod":"Thu, 17 Jul 2025 15:44:35 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/conda-forge/linux-64"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/88ec62ec.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/88ec62ec.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/eb045dd1.solv" for repo https://conda.anaconda.org/conda-forge/noarch
info     libmamba Expecting solv metadata : {"etag":"\"ac0fb74b8e2462bf40550531ca671b5b\"","mod":"Thu, 17 Jul 2025 15:45:50 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/conda-forge/noarch"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/eb045dd1.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/eb045dd1.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"\"ac0fb74b8e2462bf40550531ca671b5b\"","mod":"Thu, 17 Jul 2025 15:45:50 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/conda-forge/noarch"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/eb045dd1.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/eb045dd1.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/cbcb0f8c.solv" for repo https://repo.anaconda.com/pkgs/main/linux-64
info     libmamba Expecting solv metadata : {"etag":"\"29e53127f06c29ecf56644f4346db246\"","mod":"Thu, 17 Jul 2025 12:23:15 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/main/linux-64"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/cbcb0f8c.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/cbcb0f8c.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"\"29e53127f06c29ecf56644f4346db246\"","mod":"Thu, 17 Jul 2025 12:23:15 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/main/linux-64"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/cbcb0f8c.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/cbcb0f8c.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/45dad287.solv" for repo https://repo.anaconda.com/pkgs/main/noarch
info     libmamba Expecting solv metadata : {"etag":"\"1265d34d2114bd7e3848aace5373d3d5\"","mod":"Thu, 17 Jul 2025 12:55:18 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/main/noarch"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/45dad287.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/45dad287.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"\"1265d34d2114bd7e3848aace5373d3d5\"","mod":"Thu, 17 Jul 2025 12:55:18 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/main/noarch"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/45dad287.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/45dad287.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/26049a09.solv" for repo https://repo.anaconda.com/pkgs/r/linux-64
info     libmamba Expecting solv metadata : {"etag":"\"8de1fe9749e5c12890cf7b14945d4dc8\"","mod":"Wed, 30 Apr 2025 13:31:56 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/r/linux-64"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/26049a09.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/26049a09.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"\"8de1fe9749e5c12890cf7b14945d4dc8\"","mod":"Wed, 30 Apr 2025 13:31:56 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/r/linux-64"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/26049a09.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/26049a09.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/c150ef0f.solv" for repo https://repo.anaconda.com/pkgs/r/noarch
info     libmamba Expecting solv metadata : {"etag":"\"f83fff10217f204c49475b9031ba7e86\"","mod":"Thu, 06 Feb 2025 18:07:11 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/r/noarch"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/c150ef0f.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/c150ef0f.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"\"f83fff10217f204c49475b9031ba7e86\"","mod":"Thu, 06 Feb 2025 18:07:11 GMT","tool_version":"2.0_0.7.33","url":"https://repo.anaconda.com/pkgs/r/noarch"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/c150ef0f.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/c150ef0f.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/c7b05ae9.solv" for repo https://conda.anaconda.org/nodefaults/linux-64
info     libmamba Expecting solv metadata : {"etag":"","mod":"Thu, 17 Jul 2025 15:51:14 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/nodefaults/linux-64"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/c7b05ae9.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/c7b05ae9.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"","mod":"Thu, 17 Jul 2025 15:51:14 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/nodefaults/linux-64"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/c7b05ae9.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/c7b05ae9.solv.lock'
info     libmamba Attempting to read libsolv solv file "/home/jsmolic/micromamba/pkgs/cache/758dc0ed.solv" for repo https://conda.anaconda.org/nodefaults/noarch
info     libmamba Expecting solv metadata : {"etag":"","mod":"Thu, 17 Jul 2025 15:51:14 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/nodefaults/noarch"}
debug    libmamba Locking file '/home/jsmolic/micromamba/pkgs/cache/758dc0ed.solv'
trace    libmamba Lockfile created at '/home/jsmolic/micromamba/pkgs/cache/758dc0ed.solv.lock'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"","mod":"Thu, 17 Jul 2025 15:51:14 GMT","tool_version":"2.0_0.7.33","url":"https://conda.anaconda.org/nodefaults/noarch"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/home/jsmolic/micromamba/pkgs/cache/758dc0ed.solv'
trace    libmamba Removing file '/home/jsmolic/micromamba/pkgs/cache/758dc0ed.solv.lock'
info     libmamba Loading site packages
debug    libmamba `pip` not found
debug    libmamba Loading virtual packages
debug    libmamba Loading distribution virtual packages
debug    libmamba Loading CUDA virtual package
debug    libmamba CUDA version file found: /usr/local/cuda/version.json
debug    libmamba CUDA version found: 12.6.20241114
debug    libmamba CUDA version returned: 12.6

error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ python =*,=3.12 * does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

### environment.yml

```yaml

```

### ~/.condarc

```yaml
$ cat ~/.condarc
channels:
  - defaults
  - conda-forge
  - nodefaults
report_errors: false
solver: libmamba
channel_priority: strict
```

### PR DESCRIPTION
**Pull request by AntoinePrv**
# Description
Fix the detection of what MatchSpec we can pass to libsolv.
Close #4018

## Type of Change

- [x] Bugfix
- [ ] Feature / enhancement
- [ ] CI / Documentation
- [ ] Maintenance

## Checklist

- [x] My code follows the general style and conventions of the codebase, ensuring consistency
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have run `pre-commit run --all` locally in the source folder and confirmed that there are no linter errors.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

File: libmamba/include/mamba/specs/version_spec.hpp [hunk 1]
```diff
@@ -56,6 +56,13 @@ namespace mamba::specs
          */
         [[nodiscard]] auto has_glob() const -> bool;
 
+        /**
+         * True if the predicate is a simple operator.
+         *
+         * Simple operators are ``=``, ``!=``, ``<``, ``<=``, ``>``, ``>=``.
```
Comment (Klaim) [inline libmamba/include/mamba/specs/version_spec.hpp:62]: Why the double back-ticks? Doxygen handles Markdown so one backtick should be enough?

File: libmamba/include/mamba/specs/version_spec.hpp [hunk 2]
```diff
@@ -56,6 +56,13 @@ namespace mamba::specs
          */
         [[nodiscard]] auto has_glob() const -> bool;
 
+        /**
+         * True if the predicate is a simple operator.
```
Comment (Klaim) [inline libmamba/include/mamba/specs/version_spec.hpp:60]:
```suggestion
         * @returns `true` if the predicate is a simple operator.
```

File: libmamba/src/specs/version_spec.cpp [hunk 3]
```diff
@@ -451,6 +461,28 @@ namespace mamba::specs
...
 
+    auto VersionSpec::is_classic_operator_expression() const -> bool
+    {
+        if (expression_size() == 0)
+        {
+            return false;
+        }
+
+        auto only_operator = true;
+        m_tree.infix_for_each(
```
Comment (Klaim) [inline libmamba/src/specs/version_spec.cpp:472]: In this case, is this equivalent to `std::all_of`?

File: libmamba/include/mamba/specs/version_spec.hpp [hunk 4]
```diff
@@ -208,6 +215,14 @@ namespace mamba::specs
          * Does not return true for predicates that could be written as globs but are not.
          */
         [[nodiscard]] auto has_glob() const -> bool;
+
+        /**
+         * True if the version spec is an expression composed of simple operators.
```
Comment (Klaim) [inline libmamba/include/mamba/specs/version_spec.hpp:220]:
```suggestion
         * @returns `true` if the version spec is an expression composed of simple operators.
```

**Review by Klaim — APPROVED** [review]
Other than doc nitpicking and question for clarity, LGTM. Although I'm not very knowledgeable about matchspec details so I recommend waiting for another review before merging.

File: libmamba/include/mamba/specs/version_spec.hpp (hunk 1 above)
Comment (AntoinePrv) [reply libmamba/include/mamba/specs/version_spec.hpp:62]: In Sphinx/reStructured which we use in conjunction with Doxygen, it's double back-ticks for code snippets.
Since Markdown support arbitrary number of back-ticks, I often put two to make it universal.

File: libmamba/src/specs/version_spec.cpp (hunk 3 above)
Comment (AntoinePrv) [reply libmamba/src/specs/version_spec.cpp:472]: Yes, but:
- `infix_for_each` currently must not be called if size is zero;
- We do not have iterators there (code is pre C++20), so we cannot use the standard functions.

**Review by jjerphan — APPROVED** [review]
