### PR TITLE
Fix empty depends/constrains when installing explicit spec files

### LINKED ISSUE #4070: empty conda-meta "depends" when using a explicit lockfile
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

conda-meta depends

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

When I install an environment with micromamba using an explicit lockfile, I see `depends: []` in the conda-meta for packages that definitely have dependencies. This results in bugs later down the line where this package does not get affected when a dependency is changed from underneath it.

repro:
```
<write the env lockfile to disk as default_linux-64_conda_spec.txt>
docker run -ti --rm -v $PWD:$PWD -w $PWD mambaorg/micromamba:latest
micromamba create -n zeromq -f default_linux-64_conda_spec.txt -y
cat /opt/conda/envs/zeromq/conda-meta/zeromq-4.3.5-h387f397_9.json  | grep depends
```

I see `"depends": []` when I run this.

Interestingly, if you run this, it *does not reproduce*, suggesting there's some global state that micromamba is using to generate the conda-meta that gets properly generated when you don't use explicit lockfiles, and then works successfully when using explicit lockfiles later.

```
docker run -ti --rm -v $PWD:$PWD -w $PWD mambaorg/micromamba:latest
micromamba create -n wow -y zeromq==4.3.5=h387f397_9
cat /opt/conda/envs/wow/conda-meta/zeromq-4.3.5-h387f397_9.json |  grep depends -A6

micromamba create -n zeromq -f default_linux-64_conda_spec.txt -y
cat /opt/conda/envs/zeromq/conda-meta/zeromq-4.3.5-h387f397_9.json  | grep depends -A6
```

both of these `cat` calls show us that `depends` is correct now that we have run a regular non-lockfile `create` first:
```
    "depends": [
        "libstdcxx >=14",
        "libgcc >=14",
        "__glibc >=2.17,<3.0.a0",
        "libsodium >=1.0.20,<1.0.21.0a0",
        "krb5 >=1.21.3,<1.22.0a0"
    ],
```

### mamba info / micromamba info

```shell
libmamba version : 2.3.2
     micromamba version : 2.3.2
           curl version : libcurl/8.14.1 OpenSSL/3.5.2 zlib/1.3.1 zstd/1.5.7 libssh2/1.11.1 nghttp2/1.64.0
     libarchive version : libarchive 3.8.1 zlib/1.3.1 bz2lib/1.0.8 libzstd/1.5.7 libb2/bundled
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files :
       virtual packages : __unix=0=0
                          __linux=6.10.14=0
                          __glibc=2.41=0
                          __archspec=1=x86_64_v2
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-64
```

### Logs

```shell
info     libmamba Installing explicit specs for platform
info     libmamba Loading site packages
info     libmamba Cleaned 0 .mamba_trash files. 0 remaining.
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/_openmp_mutex-4.5-2_gnu.tar.bz2'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/_libgcc_mutex-0.1-conda_forge.tar.bz2'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libgomp-15.1.0-h767d61c_5.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libgcc-15.1.0-h767d61c_5.conda'
info     libmamba Extracting "/opt/conda/pkgs/_openmp_mutex-4.5-2_gnu.tar.bz2" to "/opt/conda/pkgs/_openmp_mutex-4.5-2_gnu"
error    libmamba Could not set lock (Resource temporarily unavailable)
warning  libmamba Cannot lock '/opt/conda/pkgs/_openmp_mutex-4.5-2_gnu.tar.bz2'
    Waiting for other mamba process to finish
info     libmamba Extracting "/opt/conda/pkgs/_libgcc_mutex-0.1-conda_forge.tar.bz2" to "/opt/conda/pkgs/_libgcc_mutex-0.1-conda_forge"
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libsodium-1.0.20-h4ab18f5_0.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libgcc-ng-15.1.0-h69a702a_5.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/ca-certificates-2025.8.3-hbd8a1cb_0.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libedit-3.1.20250104-pl5321h7949ede_0.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/openssl-3.5.3-h26f9b46_1.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/keyutils-1.6.3-hb9d3cd8_0.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libstdcxx-ng-15.1.0-h4852527_5.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/zeromq-4.3.5-h387f397_9.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/libstdcxx-15.1.0-h8f9b012_5.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/ncurses-6.5-h2d0b736_3.conda'
info     libmamba Download finished, tarball available at '/opt/conda/pkgs/krb5-1.21.3-h659f571_0.conda'
info     libmamba No python version given to TransactionContext, leaving it empty
info     libmamba Waiting for pyc compilation to finish
info     libmamba Opening history file: "/opt/conda/envs/zeromq/conda-meta/history"
```

### environment.yml

```yaml
# Generated by `pixi workspace export`
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/libgomp-15.1.0-h767d61c_5.conda#dcd5ff1940cd38f6df777cac86819d60
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2#d7c89558ba9fa0495403155b64376d81
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2#73aaf86a425cc6e73fcf236a5a46396d
https://conda.anaconda.org/conda-forge/linux-64/libgcc-15.1.0-h767d61c_5.conda#264fbfba7fb20acf3b29cde153e345ce
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-15.1.0-h8f9b012_5.conda#4e02a49aaa9d5190cb630fa43528fbe6
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-15.1.0-h69a702a_5.conda#069afdf8ea72504e48d23ae1171d951c
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.20-h4ab18f5_0.conda#a587892d3c13b6621a6091be690dbca2
https://conda.anaconda.org/conda-forge/noarch/ca-certificates-2025.8.3-hbd8a1cb_0.conda#74784ee3d225fc3dca89edb635b4e5cc
https://conda.anaconda.org/conda-forge/linux-64/openssl-3.5.3-h26f9b46_1.conda#4fc6c4c88da64c0219c0c6c0408cedd4
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-15.1.0-h4852527_5.conda#8bba50c7f4679f08c861b597ad2bda6b
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.5-h2d0b736_3.conda#47e340acb35de30501a76c7c799c41d7
https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20250104-pl5321h7949ede_0.conda#c277e0a4d549b03ac1e9d6cbbe3d017b
https://conda.anaconda.org/conda-forge/linux-64/keyutils-1.6.3-hb9d3cd8_0.conda#b38117a3c920364aff79f870c984b4a3
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.21.3-h659f571_0.conda#3f43953b7d3fb3aaa1d0d0723d91e368
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.3.5-h387f397_9.conda#8035e5b54c08429354d5d64027041cad
```

### ~/.condarc

```yaml
<empty>
```

### PR DESCRIPTION
**Pull request by benmoss**
# Description

This PR fixes a bug where empty dependencies and constraints were not properly handled when installing packages from explicit spec files. This fixes #4070 and #4052 

## Type of Change

- [x] Bugfix
- [ ] Feature / enhancement
- [ ] CI / Documentation
- [ ] Maintenance

## Checklist

- [x] My code follows the general style and conventions of the codebase, ensuring consistency
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have run `pre-commit run --all` locally in the source folder and confirmed that there are no linter errors.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

File: libmamba/tests/src/core/test_package_fetcher.cpp [hunk 1]
```diff
@@ -86,4 +92,101 @@ namespace
             REQUIRE(req.url_path == "linux-64/xtensor-0.25.0-h00ab1b0_0.conda");
         }
     }
+
+    TEST_CASE("extract_creates_repodata_record_with_dependencies")
+    {
+        // Test that PackageFetcher.extract() preserves dependencies in repodata_record.json
+#ifdef _WIN32
+        SKIP("Test not supported on Windows");
```
Comment (JohanMabille) [inline libmamba/tests/src/core/test_package_fetcher.cpp]: Can you add a comment that gives detail about the issue on Windows?

Comment (Klaim) [inline libmamba/tests/src/core/test_package_fetcher.cpp]: I would prefer if you made it work on windows too.

From the attempts you did I'm guessing the issue is that:
```
(info_dir / "index.json")
```
gives a `mamba::fs::u8path` instead of `std::filesytem::path`, but you can simply:
```
(info_dir / "index.json").std_path()
```

which will provide whatever is right for the current platform.

File: libmamba/src/core/package_fetcher.cpp [hunk 2]
```diff
@@ -436,6 +436,20 @@ namespace mamba
 
         nlohmann::json repodata_record = m_package_info;
 
+        // For explicit spec files (URLs), m_package_info has empty depends/constrains arrays
+        // that would overwrite the correct values from index.json. Remove these empty fields.
+        auto depends_it = repodata_record.find("depends");
+        auto constrains_it = repodata_record.find("constrains");
+
+        if (depends_it != repodata_record.end() && depends_it->empty())
```
Comment (JohanMabille) [inline libmamba/src/core/package_fetcher.cpp]: Since `depends_it`  is not used elsewhere, you can initialize it in the if statement to limit its scope.

File: libmamba/src/core/package_fetcher.cpp [hunk 3]
```diff
@@ -436,6 +436,20 @@ namespace mamba
...
+        {
+            repodata_record.erase("depends");
+        }
+        if (constrains_it != repodata_record.end() && constrains_it->empty())
```
Comment (JohanMabille) [inline libmamba/src/core/package_fetcher.cpp]: Same remark for `constrains_it`

**Review by JohanMabille — CHANGES_REQUESTED** [review]
