### PR TITLE
Move to Pybind 3.0

### LINKED ISSUE #4024: Error building libmambapy with pybind11 3.0
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (compiled from source on Arch Linux)

### Search tried in issue tracker

utils.cpp

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

trying to compile with pybind11 3.0, the below error happens

sadly the line numbers don’t match the main branch in the traceback below, the issue is in lines like this:

https://github.com/mamba-org/mamba/blob/14a94d379a9cbd0f89172bfd320124d947732dec/libmambapy/src/libmambapy/bindings/utils.cpp#L69

### Logs

```log
[129/167] Building CXX object libmambapy/CMakeFiles/bindings.dir/src/libmambapy/bindings/utils.cpp.o
FAILED: libmambapy/CMakeFiles/bindings.dir/src/libmambapy/bindings/utils.cpp.o 
/usr/bin/c++ -DFMT_SHARED -DMAMBA_USE_INSTALL_PREFIX_AS_BASE -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FWRITE_UNLOCKED -Dbindings_EXPORTS -I/build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings -I/build/micromamba/src/mamba-2.3.0/libmamba/include -isystem /usr/include/python3.13 -isystem /usr/share -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/micromamba/src=/usr/src/debug/micromamba -flto=auto -O3 -DNDEBUG -std=c++20 -fPIC -fvisibility=hidden -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wdouble-promotion -Wformat=2 -Wunreachable-code -Wuninitialized -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast -flto -fno-fat-lto-objects -MD -MT libmambapy/CMakeFiles/bindings.dir/src/libmambapy/bindings/utils.cpp.o -MF libmambapy/CMakeFiles/bindings.dir/src/libmambapy/bindings/utils.cpp.o.d -o libmambapy/CMakeFiles/bindings.dir/src/libmambapy/bindings/utils.cpp.o -c /build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings/utils.cpp
In file included from /usr/include/pybind11/attr.h:14,
                 from /usr/include/pybind11/detail/class.h:12,
                 from /usr/include/pybind11/pybind11.h:12,
                 from /build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings/utils.cpp:11:
/usr/include/pybind11/cast.h: In instantiation of ‘static pybind11::handle pybind11::type::handle_of() [with T = fmt::v11::emphasis]’:
/usr/include/pybind11/detail/../pytypes.h:1583:39:   required from ‘static pybind11::type pybind11::type::of() [with T = fmt::v11::emphasis]’
 1583 |         return type(type::handle_of<T>(), borrowed_t{});
      |                     ~~~~~~~~~~~~~~~~~~^~
/build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings/utils.cpp:33:26:   recursively required by substitution of ‘template<class Func, class Ret> Ret pybind11::init(Func&&) [with Func = fmt::v11::emphasis (*)(const pybind11::str&); Ret = pybind11::detail::initimpl::factory<fmt::v11::emphasis (*)(const pybind11::str&), pybind11::detail::void_type (*)(), fmt::v11::emphasis(const pybind11::str&), pybind11::detail::void_type()>]’
   33 |             .def(py::init(&enum_from_str<fmt::emphasis>));
      |                  ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings/utils.cpp:33:26:   required from here
/usr/include/pybind11/cast.h:2337:89: error: static assertion failed: py::type::of<T> only supports the case where T is a registered C++ types.
 2337 |     static_assert(std::is_base_of<detail::type_caster_generic, detail::make_caster<T>>::value,
      |                                                                                         ^~~~~
/usr/include/pybind11/cast.h:2337:89: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
/usr/include/pybind11/cast.h: In instantiation of ‘static pybind11::handle pybind11::type::handle_of() [with T = fmt::v11::terminal_color]’:
/usr/include/pybind11/detail/../pytypes.h:1583:39:   required from ‘static pybind11::type pybind11::type::of() [with T = fmt::v11::terminal_color]’
 1583 |         return type(type::handle_of<T>(), borrowed_t{});
      |                     ~~~~~~~~~~~~~~~~~~^~
/build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings/utils.cpp:53:26:   recursively required by substitution of ‘template<class Func, class Ret> Ret pybind11::init(Func&&) [with Func = fmt::v11::terminal_color (*)(const pybind11::str&); Ret = pybind11::detail::initimpl::factory<fmt::v11::terminal_color (*)(const pybind11::str&), pybind11::detail::void_type (*)(), fmt::v11::terminal_color(const pybind11::str&), pybind11::detail::void_type()>]’
   53 |             .def(py::init(&enum_from_str<fmt::terminal_color>));
      |                  ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/micromamba/src/mamba-2.3.0/libmambapy/src/libmambapy/bindings/utils.cpp:53:26:   required from here
/usr/include/pybind11/cast.h:2337:89: error: static assertion failed: py::type::of<T> only supports the case where T is a registered C++ types.
 2337 |     static_assert(std::is_base_of<detail::type_caster_generic, detail::make_caster<T>>::value,
      |                                                                                         ^~~~~
/usr/include/pybind11/cast.h:2337:89: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
```

### PR DESCRIPTION
**Pull request by AntoinePrv**
# Description
This new implementation actually works with Pybind 2 and 3.

## Type of Change

- [ ] Bugfix
- [ ] Feature / enhancement
- [ ] CI / Documentation
- [x] Maintenance

## Checklist

- [x] My code follows the general style and conventions of the codebase, ensuring consistency
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have run `pre-commit run --all` locally in the source folder and confirmed that there are no linter errors.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

Close #4024
Close #4030
Close #4056

### CODE REVIEW

File: libmambapy/bindings/bind_utils.hpp [hunk 1]
```diff
@@ -14,11 +14,45 @@
...
+            [name_values](std::string_view s)
+            {
+                for (const auto& [name, val] : name_values)
+                {
+                    if (name == s)
+                    {
+                        return val;
+                    }
+                }
+                throw pybind11::key_error(std::format("No member named {}", s));
```
Comment (shermansiu) [inline libmambapy/bindings/bind_utils.hpp:51]: You also need to add `#include <format>` at the top, right?

**Comment by shermansiu** [comment]
Anyways, after I add `#include <format>` to [libmambapy/bindings/bind_utils.hpp](https://github.com/mamba-org/mamba/pull/4059/files/7d00547f76157e2a23709049896c6711b38e6b5a#diff-5a30e1804ac2841513e413e74f415618b791fd0cf6a9b54694903a22feb817ea), all the `libmambapy` tests pass, except there is a segfault at the end:

```python
python -m pytest libmambapy/tests
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.11.13, pytest-8.4.1, pluggy-1.6.0
rootdir: /mnt/ubuntu_hdd/open_source/code/mamba
configfile: pyproject.toml
plugins: cov-6.2.1, xprocess-1.0.2, asyncio-1.1.0, rerunfailures-16.0.1, timeout-2.4.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 117 items                                                                                                                                                              

libmambapy/tests/test_legacy.py ...                                                                                                                                        [  2%]
libmambapy/tests/test_solver.py ..............................                                                                                                             [ 28%]
libmambapy/tests/test_solver_libsolv.py ............................................                                                                                       [ 65%]
libmambapy/tests/test_specs.py .................................                                                                                                           [ 94%]
libmambapy/tests/test_utils.py ......                                                                                                                                      [ 99%]
libmambapy/tests/test_version.py .                                                                                                                                         [100%]

============================================================================== 117 passed in 0.15s ===============================================================================

munmap_chunk(): invalid pointer
Aborted (core dumped)
```

**Comment by AntoinePrv** [comment]
Indeed, I believe I found it.

**Comment by shermansiu** [comment]
@jjerphan Ready for review!

File: libmambapy/bindings/bind_utils.hpp [hunk 2]
```diff
@@ -7,18 +7,53 @@
...
+     * parameters as strings (Python catnip).
+     * This function was added to avoid breaking that contract.
+     * ``pybind11::enum_`` was kept because ``pybind11::native_enum`` does not support
+     * to this day constructors needed for implicit conversion.
+     *
+     * Perhaps ``pybind11::native_enum`` will support string implicit conversion in the future,
+     * otherwise the implicit conversion could be broken in a major release.
+     */
+    template <typename Enum, std::size_t N, typename PyEnum>
+    auto make_str_enum(PyEnum&& pyenum, std::array<std::pair<const char*, Enum>, N> name_values)
```
Comment (jjerphan) [inline libmambapy/bindings/bind_utils.hpp:34]: Naive question: is there a reason not to use `std::string`?
```suggestion
    auto make_str_enum(PyEnum&& pyenum, std::array<std::pair<std::string, Enum>, N> name_values)
```

**Review by JohanMabille — APPROVED** [review]

File: dev/environment-dev.yml [hunk 3]
```diff
@@ -53,7 +53,7 @@ dependencies:
   - scikit-build-core
   # libmambapy dependencies
   - python
-  - pybind11<3.0.0
+  - pybind11>=3.0.0
```
Comment (jjerphan) [inline dev/environment-dev.yml:56]: Could we test it against using pybind11 2 (by pushing a commit and reverting it then) to verify that there's no regression for this version?
```suggestion
  - pybind11<3.0.0
```

File: libmambapy/bindings/bind_utils.hpp (hunk 2 above)
Comment (AntoinePrv) [reply libmambapy/bindings/bind_utils.hpp:34]: Yes, this is for a "compile time string" / string literal.

Comment (jjerphan) [reply libmambapy/bindings/bind_utils.hpp:34]: OK, I guess `constexpr`-ness of `std::string` cannot be used here.

**Comment by AntoinePrv** [comment]
Ok, not waiting for the integration tests on pybind 2.0 before reverting.

**Comment by AntoinePrv** [comment]
Also not waiting for this CI since it's the exact same commit as before.

**Comment by shermansiu** [comment]
> I guess we can now perform a pre-release of 2.4.0 (or 2.3.3) to test this PR and https://github.com/mamba-org/mamba/pull/3802.
>
> What do you think?

@AntoinePrv: so... are we going to get a pre-release?

**Comment by AntoinePrv** [comment]
Yes, even a release. It's coming in the next few days.

**Comment by shermansiu** [comment]
Looking forward to it! :smile:

**Comment by AntoinePrv** [comment]
@shermansiu the prerelease is out.

**Comment by shermansiu** [comment]
Thanks for letting me know! 😁
