### PR TITLE
Fix install using explicit url

### LINKED ISSUE #3304: Cannot install package by URL
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

Package cache error.

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

I am using mamba 2.x, commit 9300a6530cac4f5575e7f8aa4049fbb9c1150909.

Installing a package via URL or via a conda environment lockfile fails:

```
$ micromamba create --yes --no-rc --no-env --name=testenv --override-channels 'https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-main.conda'
...
  Package          Version  Build  Channel         Size
─────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────

  + _libgcc_mutex      0.1  main   conda-forge         

  Summary:

  Install: 1 packages

  Total download: 0 B

─────────────────────────────────────────────────────────



Transaction starting
[+] 0.0s
Downloading      ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /   0.0 B                            0.0s
Linking _libgcc_mutex-0.1-main
error    libmamba Cannot find a valid extracted directory cache for '_libgcc_mutex-0.1-main.conda'
critical libmamba Package cache error.
```

It appears that linking starts before downloading/extracting has finished.

The issue does not occur if the package is installed by name (`micromamba create --yes --no-rc --no-env --name=testenv --override-channels 'conda-forge::_libgcc_mutex=0.1=main'`).

### mamba info / micromamba info

```shell
libmamba version : 2.0.0
          mamba version : 2.0.0
           curl version : libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.3.0.zlib-ng brotli/1.1.0 libidn2/2.3.7 libpsl/0.21.5 libssh/0.10.6/openssl/zlib nghttp2/1.59.0 OpenLDAP/2.6.7
     libarchive version : libarchive 3.7.2 zlib/1.3.0.zlib-ng liblzma/5.4.6 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.6
       envs directories : /home/hristo/.local/share/mamba/envs
          package cache : /home/hristo/.local/share/mamba/pkgs
                          /home/hristo/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /home/hristo/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=6.8.6=0
                          __glibc=2.39=0
                          __archspec=1=x86_64-v4
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/hristo/.local/share/mamba
               platform : linux-64
```

### Logs

```shell
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
warning  libmamba You have not set the root prefix environment variable.
    To permanently modify the root prefix location, either:
      - set the 'MAMBA_ROOT_PREFIX' environment variable
      - use the '-r,--root-prefix' CLI option
      - use 'mamba shell init ...' to initialize your shell
        (then restart or source the contents of the shell init script)
    Continuing with default value: "/home/hristo/.local/share/mamba"
trace    libmamba Compute configurable 'envs_dirs'
trace    libmamba Compute configurable 'file_specs'
trace    libmamba Compute configurable 'spec_file_env_name'
trace    libmamba Compute configurable 'env_name'
trace    libmamba Compute configurable 'use_target_prefix_fallback'
trace    libmamba Compute configurable 'target_prefix'
trace    libmamba Compute configurable 'relocate_prefix'
trace    libmamba Compute configurable 'target_prefix_checks'
trace    libmamba Compute configurable 'pkgs_dirs'
trace    libmamba Compute configurable 'platform'
trace    libmamba Compute configurable 'specs'
trace    libmamba Compute configurable 'others_pkg_mgrs_specs'
trace    libmamba Compute configurable 'experimental'
trace    libmamba Compute configurable 'experimental_repodata_parsing'
trace    libmamba Compute configurable 'debug'
trace    libmamba Compute configurable 'override_channels_enabled'
trace    libmamba Compute configurable 'override_channels'
trace    libmamba Compute configurable 'channels'
trace    libmamba Compute configurable 'channel_alias'
trace    libmamba Compute configurable 'default_channels'
trace    libmamba Compute configurable 'custom_channels'
trace    libmamba Compute configurable 'custom_multichannels'
trace    libmamba Compute configurable 'mirrored_channels'
trace    libmamba Compute configurable 'repodata_use_zst'
trace    libmamba Compute configurable 'repodata_has_zst'
trace    libmamba Compute configurable 'cacert_path'
trace    libmamba Compute configurable 'local_repodata_ttl'
trace    libmamba Compute configurable 'offline'
trace    libmamba Compute configurable 'ssl_no_revoke'
trace    libmamba Compute configurable 'ssl_verify'
trace    libmamba Compute configurable 'proxy_servers'
trace    libmamba Compute configurable 'remote_connect_timeout_secs'
trace    libmamba Compute configurable 'remote_backoff_factor'
trace    libmamba Compute configurable 'remote_max_retries'
trace    libmamba Compute configurable 'no_channel_priority'
trace    libmamba Compute configurable 'strict_channel_priority'
trace    libmamba Compute configurable 'channel_priority'
trace    libmamba Compute configurable 'explicit_install'
trace    libmamba Compute configurable 'no_pin'
trace    libmamba Compute configurable 'no_py_pin'
trace    libmamba Compute configurable 'add_pip_as_python_dependency'
trace    libmamba Compute configurable 'pinned_packages'
trace    libmamba Compute configurable 'freeze_installed'
trace    libmamba Compute configurable 'no_deps'
trace    libmamba Compute configurable 'only_deps'
trace    libmamba Compute configurable 'force_reinstall'
trace    libmamba Compute configurable 'allow_uninstall'
trace    libmamba Compute configurable 'allow_downgrade'
trace    libmamba Compute configurable 'order_solver_request'
trace    libmamba Compute configurable 'categories'
trace    libmamba Compute configurable 'retry_clean_cache'
trace    libmamba Compute configurable 'download_threads'
trace    libmamba Compute configurable 'extract_threads'
trace    libmamba Compute configurable 'allow_softlinks'
trace    libmamba Compute configurable 'always_copy'
trace    libmamba Compute configurable 'always_softlink'
trace    libmamba Compute configurable 'shortcuts'
trace    libmamba Compute configurable 'safety_checks'
trace    libmamba Compute configurable 'extra_safety_checks'
trace    libmamba Compute configurable 'verify_artifacts'
trace    libmamba Compute configurable 'trusted_channels'
trace    libmamba Compute configurable 'lock_timeout'
trace    libmamba Compute configurable 'use_lockfiles'
trace    libmamba Compute configurable 'compile_pyc'
trace    libmamba Compute configurable 'always_yes'
trace    libmamba Compute configurable 'auto_activate_base'
trace    libmamba Compute configurable 'dry_run'
trace    libmamba Compute configurable 'download_only'
trace    libmamba Compute configurable 'print_config_only'
trace    libmamba Compute configurable 'print_context_only'
trace    libmamba Compute configurable 'json'
trace    libmamba Compute configurable 'verbose'
trace    libmamba Compute configurable 'log_level'
trace    libmamba Compute configurable 'log_backtrace'
trace    libmamba Compute configurable 'log_pattern'
trace    libmamba Compute configurable 'changeps1'
trace    libmamba Compute configurable 'shell_completion'
trace    libmamba Compute configurable 'env_prompt'
trace    libmamba Compute configurable 'show_all_configs'
trace    libmamba Compute configurable 'show_all_rc_configs'
trace    libmamba Compute configurable 'show_config_descriptions'
trace    libmamba Compute configurable 'show_config_groups'
trace    libmamba Compute configurable 'show_config_long_descriptions'
trace    libmamba Compute configurable 'show_config_sources'
trace    libmamba Compute configurable 'show_config_values'
trace    libmamba Compute configurable 'quiet'
trace    libmamba Compute configurable 'override_rc_files'
trace    libmamba Compute configurable 'shell_type'
trace    libmamba Compute configurable 'prefix_or_name'
trace    libmamba Compute configurable 'shell_stack'
trace    libmamba Compute configurable 'list_regex'
trace    libmamba Compute configurable 'clean_all'
trace    libmamba Compute configurable 'clean_index_cache'
trace    libmamba Compute configurable 'clean_packages'
trace    libmamba Compute configurable 'clean_tarballs'
trace    libmamba Compute configurable 'clean_locks'
trace    libmamba Compute configurable 'clean_trash'
trace    libmamba Compute configurable 'clean_force_pkgs_dirs'
trace    libmamba Compute configurable 'config_set_system_path'
trace    libmamba Compute configurable 'config_set_env_path'
trace    libmamba Compute configurable 'config_set_file_path'
trace    libmamba Compute configurable 'config_set_sequence_spec'
trace    libmamba Compute configurable 'remove_key'
trace    libmamba Compute configurable 'remove'
trace    libmamba Compute configurable 'set_value'
trace    libmamba Compute configurable 'get_value'
trace    libmamba Compute configurable 'constructor_prefix'
trace    libmamba Compute configurable 'constructor_extract_conda_pkgs'
trace    libmamba Compute configurable 'constructor_extract_tarball'
debug    libmamba 114 configurables computed
debug    libmamba Loading virtual packages
debug    libmamba Loading distribution virtual packages
debug    libmamba Loading CUDA virtual package
debug    libmamba Could not find CUDA version by calling 'nvidia-smi' (skipped)
    

debug    libsolv  number of solvables: 7, memory used: 0 K
debug    libsolv  number of ids: 218 + 6
debug    libsolv  string memory used: 0 K array + 3 K data,  rel memory used: 0 K array
debug    libsolv  string hash memory: 32 K, rel hash memory : 16 K
debug    libsolv  provide ids: 5
debug    libsolv  provide space needed: 14 + 256
debug    libsolv  shrunk whatprovidesdata from 14 to 14
debug    libsolv  shrunk whatprovidesauxdata from 14 to 6
debug    libsolv  whatprovides memory used: 4 K id array, 1 K data
debug    libsolv  whatprovidesaux memory used: 0 K id array, 0 K data
debug    libsolv  createwhatprovides took 0 ms
debug    libsolv  solver started
debug    libsolv  dosplitprovides=0, noupdateprovide=0, noinfarchcheck=0
debug    libsolv  allowuninstall=1, allowdowngrade=1, allownamechange=1, allowarchchange=0, allowvendorchange=0
debug    libsolv  dupallowdowngrade=1, dupallownamechange=1, dupallowarchchange=1, dupallowvendorchange=1
debug    libsolv  promoteepoch=0, forbidselfconflicts=0
debug    libsolv  obsoleteusesprovides=0, implicitobsoleteusesprovides=0, obsoleteusescolors=0, implicitobsoleteusescolors=1
debug    libsolv  dontinstallrecommended=0, addalreadyrecommended=0 onlynamespacerecommended=0
debug    libsolv  obsoletes data: 1 entries
debug    libsolv  added 0 pkg rules for installed solvables
debug    libsolv  added 0 pkg rules for updaters of installed solvables
debug    libsolv  added 0 pkg rules for packages involved in a job
debug    libsolv  added 0 pkg rules because of weak dependencies
debug    libsolv  6 of 6 installable solvables considered for solving
debug    libsolv  pkg rule memory used: 0 K
debug    libsolv  pkg rule creation took 1 ms
debug    libsolv    Add rule: debug    libsolv  Rule #1:debug    libsolv  
debug    libsolv      __unix-0-0 [3]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #2:debug    libsolv  
debug    libsolv      __linux-6.8.6-0 [4]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #3:debug    libsolv  
debug    libsolv      __glibc-2.39-0 [5]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #4:debug    libsolv  
debug    libsolv      __archspec-1-x86_64-v4 [6]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #5:debug    libsolv  
debug    libsolv      __unix-0-0 [3]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #6:debug    libsolv  
debug    libsolv      __linux-6.8.6-0 [4]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #7:debug    libsolv  
debug    libsolv      __glibc-2.39-0 [5]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    Add rule: debug    libsolv  Rule #8:debug    libsolv  
debug    libsolv      __archspec-1-x86_64-v4 [6]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  job: install unknown job select
debug    libsolv    Add rule: debug    libsolv  Rule #9:debug    libsolv  
debug    libsolv      _libgcc_mutex-0.1-main [2]debug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv    - job debug    libsolv  Rule #9:debug    libsolv  
debug    libsolv      _libgcc_mutex-0.1-main [2]debug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  0 pkg rules, 2 * 4 update rules, 1 job rules, 0 infarch rules, 0 dup rules, 0 choice rules, 0 best rules, 0 yumobs rules
debug    libsolv  0 black rules, 0 recommends rules, 0 repo priority rules
debug    libsolv  overall rule memory used: 0 K
debug    libsolv  number of rules: 10
debug    libsolv  FEATURE debug    libsolv  Rule #1:debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  FEATURE debug    libsolv  Rule #2:debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  FEATURE debug    libsolv  Rule #3:debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  FEATURE debug    libsolv  Rule #4:debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  UPDATE debug    libsolv  Rule #5:debug    libsolv  
debug    libsolv      __unix-0-0 [3]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  UPDATE debug    libsolv  Rule #6:debug    libsolv  
debug    libsolv      __linux-6.8.6-0 [4]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  UPDATE debug    libsolv  Rule #7:debug    libsolv  
debug    libsolv      __glibc-2.39-0 [5]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  UPDATE debug    libsolv  Rule #8:debug    libsolv  
debug    libsolv      __archspec-1-x86_64-v4 [6]debug    libsolv  Idebug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  JOB debug    libsolv  Rule #9:debug    libsolv  
debug    libsolv      _libgcc_mutex-0.1-main [2]debug    libsolv   (w1)debug    libsolv  
debug    libsolv      next rules: 0 0
debug    libsolv  solving...
debug    libsolv  installing  __unix-0-0 (assertion)
debug    libsolv  installing  __linux-6.8.6-0 (assertion)
debug    libsolv  installing  __glibc-2.39-0 (assertion)
debug    libsolv  installing  __archspec-1-x86_64-v4 (assertion)
debug    libsolv  installing  _libgcc_mutex-0.1-main (assertion)
debug    libsolv  initial propagate (propagate_index: 0;  size decisionq: 6)...
debug    libsolv  ----- propagate level 1 -----
debug    libsolv  propagate decision 1:debug    libsolv      system:system.any [1]debug    libsolv   Install.level1debug    libsolv  
debug    libsolv  propagate decision 3:debug    libsolv      __unix-0-0 [3]debug    libsolv  Idebug    libsolv   Install.level1debug    libsolv  
debug    libsolv  propagate decision 4:debug    libsolv      __linux-6.8.6-0 [4]debug    libsolv  Idebug    libsolv   Install.level1debug    libsolv  
debug    libsolv  propagate decision 5:debug    libsolv      __glibc-2.39-0 [5]debug    libsolv  Idebug    libsolv   Install.level1debug    libsolv  
debug    libsolv  propagate decision 6:debug    libsolv      __archspec-1-x86_64-v4 [6]debug    libsolv  Idebug    libsolv   Install.level1debug    libsolv  
debug    libsolv  propagate decision 2:debug    libsolv      _libgcc_mutex-0.1-main [2]debug    libsolv   Install.level1debug    libsolv  
debug    libsolv  ----- propagate end -----
debug    libsolv  resolving job rules
debug    libsolv  resolving installed packages
debug    libsolv  deciding unresolved rules
debug    libsolv  installing recommended packages
debug    libsolv  deciding orphaned packages
debug    libsolv  solver statistics: 0 learned rules, 0 unsolvable, 0 minimization steps
debug    libsolv  done solving.

debug    libsolv  solver took 1 ms
debug    libsolv  final solver statistics: 0 problems, 0 learned rules, 0 unsolvable
debug    libsolv  solver_solve took 2 ms
debug    libsolv  ordering transaction
debug    libsolv  transaction elements: 1
debug    libsolv  edges: 0, edge space: 0
debug    libsolv  edge creation took 0 ms
debug    libsolv  cycles broken: 0
debug    libsolv  cycle breaking took 0 ms
debug    libsolv  invedge space: 3
debug    libsolv  creating new transaction took 0 ms
debug    libsolv  transaction ordering took 0 ms
debug    libmamba Solution: Install _libgcc_mutex-0.1-main
error    libmamba Could not lock non-existing path '/home/hristo/.local/share/mamba/pkgs'
error    libmamba Could not lock non-existing path '/home/hristo/.mamba/pkgs'
info     libmamba No python version given to TransactionContext, leaving it empty

Transaction

  Prefix: /home/hristo/.local/share/mamba/envs/testenv

  Updating specs:

   - https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-main.conda


  Package          Version  Build  Channel         Size
─────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────

  + _libgcc_mutex      0.1  main   conda-forge         

  Summary:

  Install: 1 packages

  Total download: 0 B

─────────────────────────────────────────────────────────


debug    libmamba Locking directory '/home/hristo/.local/share/mamba/envs/testenv/conda-meta'
trace    libmamba Lockfile created at '/home/hristo/.local/share/mamba/envs/testenv/conda-meta/conda-meta.lock'
debug    libmamba Successfully locked
info     libmamba Cleaned 0 .mamba_trash files. 0 remaining.

Transaction starting
debug    libmamba Verify cache '/home/hristo/.local/share/mamba/pkgs' for package extracted directory '_libgcc_mutex-0.1-main'
debug    libmamba Extracted package cache '/home/hristo/.local/share/mamba/pkgs/_libgcc_mutex-0.1-main' not found
debug    libmamba '_libgcc_mutex-0.1-main' extracted directory cache is invalid
debug    libmamba Verify cache '/home/hristo/.mamba/pkgs' for package extracted directory '_libgcc_mutex-0.1-main'
debug    libmamba Extracted package cache '/home/hristo/.mamba/pkgs/_libgcc_mutex-0.1-main' not found
debug    libmamba '_libgcc_mutex-0.1-main' extracted directory cache is invalid
debug    libmamba Verify cache '/home/hristo/.local/share/mamba/pkgs' for package tarball '_libgcc_mutex-0.1-main'
debug    libmamba '_libgcc_mutex-0.1-main' tarball cache is invalid
debug    libmamba Verify cache '/home/hristo/.mamba/pkgs' for package tarball '_libgcc_mutex-0.1-main'
debug    libmamba '_libgcc_mutex-0.1-main' tarball cache is invalid
debug    libmamba Checking if '/home/hristo/.local/share/mamba/pkgs' is writable
trace    libmamba Cache path does not exists or is not writable
debug    libmamba '/home/hristo/.local/share/mamba/pkgs' writable
debug    libmamba Adding '_libgcc_mutex' to download targets from 'conda-forge/linux-64/_libgcc_mutex-0.1-main.conda'
[+] 0.0s
Downloading      ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /   0.0 B                            0.0s
Linking _libgcc_mutex-0.1-main
debug    libmamba Verify cache '/home/hristo/.local/share/mamba/pkgs' for package extracted directory '_libgcc_mutex-0.1-main'
debug    libmamba Extracted package cache '/home/hristo/.local/share/mamba/pkgs/_libgcc_mutex-0.1-main' not found
debug    libmamba '_libgcc_mutex-0.1-main' extracted directory cache is invalid
debug    libmamba Verify cache '/home/hristo/.mamba/pkgs' for package extracted directory '_libgcc_mutex-0.1-main'
debug    libmamba Extracted package cache '/home/hristo/.mamba/pkgs/_libgcc_mutex-0.1-main' not found
debug    libmamba '_libgcc_mutex-0.1-main' extracted directory cache is invalid
error    libmamba Cannot find a valid extracted directory cache for '_libgcc_mutex-0.1-main.conda'
debug    libmamba Unlocking '/home/hristo/.local/share/mamba/envs/testenv/conda-meta'
trace    libmamba Removing file '/home/hristo/.local/share/mamba/envs/testenv/conda-meta/conda-meta.lock'
critical libmamba Package cache error.
```

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by Hind-M**
Fix #3304

### CODE REVIEW

**Comment by Hind-M** [comment]
> Commit [ac3c921](https://github.com/mamba-org/mamba/commit/ac3c9210b21c9fc919f11f08efa1aef61225d1de) looks very suspicious to me. Assuming `util::contains` is roughly `strstr`, won't this match lots of package URLs simply because the path/channel/target/name/version/build happens to contain `ghcr`?

Yes, but that should be unlikely. I changed the condition though to something more robust.

File: libmamba/src/core/package_fetcher.cpp [hunk 1]
```diff
@@ -325,23 +325,45 @@ namespace mamba
...
+        // Note that in the oci case, the pkg url also implicitly starts with "https://"
+        // but should be included in the first case
+        // (with the url starting with "https://pkg-containers.githubusercontent.com/" condition)
+        // TODO We should maybe think of a cleaner way of differentiating all this
+        if (!util::starts_with(m_package_info.package_url, "file://")
+            && (!util::starts_with(m_package_info.package_url, "https://")
+                || util::starts_with(
+                    m_package_info.package_url,
+                    "https://pkg-containers.githubusercontent.com/"
+                )))
```
Comment (jjerphan) [inline libmamba/src/core/package_fetcher.cpp:337]: Can we come up with a private method for this condition testing OCI (from what I can understand) as well as some background in this PR?

File: libmamba/src/core/package_fetcher.cpp [hunk 2]
```diff
@@ -325,23 +325,45 @@ namespace mamba
...
-        if (!util::starts_with(m_package_info.package_url, "file://"))
+        // Note that in the oci case, the pkg url also implicitly starts with "https://"
+        // but should be included in the first case
+        // (with the url starting with "https://pkg-containers.githubusercontent.com/" condition)
+        // TODO We should maybe think of a cleaner way of differentiating all this
+        if (!util::starts_with(m_package_info.package_url, "file://")
+            && (!util::starts_with(m_package_info.package_url, "https://")
+                || util::starts_with(
+                    m_package_info.package_url,
+                    "https://pkg-containers.githubusercontent.com/"
```
Comment (JohanMabille) [inline libmamba/src/core/package_fetcher.cpp:336]: - We should not use a hard-coded URL here, but a constant initialized to that value.
- Capturing the diferent conditions in small functions would make the code easier to read.

**Review by JohanMabille — CHANGES_REQUESTED** [review]

File: libmamba/src/core/package_fetcher.cpp [hunk 3]
```diff
@@ -317,6 +317,19 @@ namespace mamba
     /*******************
      * Private methods *
      *******************/
+    bool PackageFetcher::is_local_package() const
+    {
+        return util::starts_with(m_package_info.package_url, "file://");
+    }
+
+    bool PackageFetcher::use_explicit_url() const
```
Comment (jjerphan) [inline libmamba/src/core/package_fetcher.cpp:325]: Nitpick.
```suggestion
    bool PackageFetcher::use_explicit_https_url() const
```

File: libmamba/src/core/package_fetcher.cpp [hunk 4]
```diff
@@ -325,23 +338,25 @@ namespace mamba
...
         {
             return m_package_info.channel;
         }
-        else  // local package case
+        // Use explicit url to fetch package and leave channel empty
+        else
         {
             return "";
         }
     }
```
Comment (jjerphan) [inline libmamba/src/core/package_fetcher.cpp:350]: How about?

```c++
    std::string PackageFetcher::channel() const
    {
        if (is_local_package() || use_explicit_url())
        {
            // Use explicit url or local package path
            // to fetch package, leaving the channel empty.
            return "";
        }
        return m_package_info.channel;
    }
```

File: libmamba/src/core/package_fetcher.cpp [hunk 5]
```diff
@@ -325,23 +338,25 @@ namespace mamba
...
+        if (!is_local_package() && !use_explicit_url())
         {
             return util::concat(m_package_info.platform, '/', m_package_info.filename);
         }
-        else  // local package case
+        // Use explicit url to fetch package
+        else
         {
             return m_package_info.package_url;
         }
```
Comment (jjerphan) [inline libmamba/src/core/package_fetcher.cpp:362]: How about?

```c++
    std::string PackageFetcher::url_path() const
    {
        if (is_local_package() || use_explicit_url())
        {
            // Use explicit url or local package path
            // to fetch package.
            return m_package_info.package_url;
        }
        return util::concat(m_package_info.platform, '/', m_package_info.filename);
    }
```

**Review by jjerphan — APPROVED** [review]
Thank you, @Hind-M.
