### PR TITLE
[micromamba] [mamba] Fix wrong download url for custom channels

### LINKED ISSUE #2553: Wrong download url for custom channels with labels
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

N/A

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

With condarc provided below, installing packages from a label channel fails, while conda works fine.

```
❯ micromamba install -c "nvidia/label/cuda-11.8.0" cuda-nvcc

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

nvidia/label/cuda-11.8.0/noarch                      3.4kB @   2.8kB/s 404 failed  1.2s
critical libmamba Multiple errors occured:
    Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/nvidia/label/label/cuda-11.8.0/noarch/repodata.json] 3366 bytes
    Subdir nvidia/label/cuda-11.8.0/noarch not loaded!
```

Obviously, the returned URL includes `label/label` but it should occur only once.

### mamba info / micromamba info

_No response_

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

```yaml
custom_channels:
  nvidia/label: https://conda.anaconda.org
```

### PR DESCRIPTION
**Pull request by Hind-M**
- [x] Fix #2553 (`micromamba`)
- [x] Fix the issue for `mamba`
- [x] Add tests

### CODE REVIEW

File: libmamba/tests/src/core/test_util_string.cpp [hunk 1]
```diff
@@ -385,6 +385,22 @@ namespace mamba
         {
             CHECK_EQ(concat("aa", std::string("bb"), std::string_view("cc"), 'd'), "aabbccd");
         }
+
+        TEST_CASE("get_common_substr")
+        {
+            CHECK_EQ(get_common_substr("", ""), "");
+            CHECK_EQ(get_common_substr("", "test"), "");
+            CHECK_EQ(get_common_substr("test", "test"), "test");
+            CHECK_EQ(get_common_substr("test/chan", "test/chan"), "test/chan");
```
Comment (AntoinePrv) [inline libmamba/tests/src/core/test_util_string.cpp:394]: Am I getting this correct?
```suggestion
            CHECK_EQ(get_common_substr("test/chan", "test/chan"), "test/chan");
            CHECK_EQ(get_common_substr("st/ch", "test/chan"), "");
            CHECK_EQ(get_common_substr("test/ch", "test/chan"), "test");
```

File: libmamba/src/core/util_string.cpp [hunk 2]
```diff
@@ -15,6 +15,27 @@
 
 namespace mamba
 {
+    /********************************************************
+     *  Implementation of Channels use case util function   *
+     *******************************************************/
```
Comment (AntoinePrv) [inline libmamba/src/core/util_string.cpp:20]:
```suggestion
     *******************************************************/

```

File: libmamba/src/core/util_string.cpp [hunk 3]
```diff
@@ -15,6 +15,27 @@
...
+    std::string get_common_substr(std::string_view str1, std::string_view str2)
```
Comment (AntoinePrv) [inline libmamba/src/core/util_string.cpp:21]: Three more nitpicking suggestions:
- Looking more into the function, maybe a more explicit name could be `get_common_parts`?
- `'/'` could then be a `delim` parameter
- Possibly, the function could return a `std::string_view` as well, avoiding the need to create a string when the user does not need it.

**Review by AntoinePrv — APPROVED** [review]
LGTM. I left a few more nitpicking suggestions if you think they are valuable.

File: libmamba/tests/src/core/test_util_string.cpp (hunk 1 above)
Comment (Hind-M) [reply libmamba/tests/src/core/test_util_string.cpp]: Good catch! I didn't think about this because I was focused on the use case but I added more constraints so that the tests pass, thanks!
