### PR TITLE
Handle `.tar.gz` in pkg url

### LINKED ISSUE #3589: Libmamba failed to parse PackageInfo URL error (regression)
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

PackageInfo URL error

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I'm trying to build a micromamba environment from a lock file with docker. The environment requires a pip package. Building the container succeeds with `mambaorg/micromamba:1.5.10` but fails with 2.0 and newer versions.

The error:
```
 > [5/5] RUN micromamba install -y -n base -f ./conda-lock.yml &&     micromamba clean --all --yes:
0.190 critical libmamba Fail to parse PackageInfo URL "https://files.pythonhosted.org/packages/e4/2f/b6ad927d467451a1b5872cce8e7204ec25d2a6cde8077cb28003ed35787d/Checkm-0.4.tar.gz"
```

The env the lock was created from:
```
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pip
  - pip:
    - checkm
```

The Dockerfile:
```
FROM  mambaorg/micromamba:2.0.3

WORKDIR /opt/app
USER root
RUN chown -R mambauser:mambauser /opt/app



COPY conda-lock.yml .
RUN micromamba install -y -n base -f ./conda-lock.yml && \
    micromamba clean --all --yes

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]
```

The command to generate the lock file from the env:
```
conda-lock lock  -f env.yml -k lock -p linux-64
```

The conda-lock file is attached (renamed to fit file upload rules).
[conda-lock.yml.txt](https://github.com/user-attachments/files/17684242/conda-lock.yml.txt)

### mamba info / micromamba info

```shell
libmamba version : 2.0.3
     micromamba version : 2.0.3
           curl version : libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.64.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.36=0
                          __archspec=1=x86_64_v3
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-64
```

### Logs

```shell
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 303B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/mambaorg/micromamba:latest
#2 DONE 1.3s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/mambaorg/micromamba:latest@sha256:85236af3a2ce605ece8bdd59b0074e0de93638970de16a6d2660c6e4068a5639
#4 DONE 0.0s

#5 [2/5] WORKDIR /opt/app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 36B done
#6 DONE 0.0s

#7 [3/5] RUN chown -R mambauser:mambauser /opt/app
#7 DONE 0.4s

#8 [4/5] COPY conda-lock.yml .
#8 DONE 0.0s

#9 [5/5] RUN micromamba install -y -n base -f ./conda-lock.yml &&     micromamba clean --all --yes
#9 0.150 critical libmamba Fail to parse PackageInfo URL "https://files.pythonhosted.org/packages/e4/2f/b6ad927d467451a1b5872cce8e7204ec25d2a6cde8077cb28003ed35787d/Checkm-0.4.tar.gz"
#9 ERROR: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f ./conda-lock.yml &&     micromamba clean --all --yes" did not complete successfully: exit code: 1
------
 > [5/5] RUN micromamba install -y -n base -f ./conda-lock.yml &&     micromamba clean --all --yes:
0.150 critical libmamba Fail to parse PackageInfo URL "https://files.pythonhosted.org/packages/e4/2f/b6ad927d467451a1b5872cce8e7204ec25d2a6cde8077cb28003ed35787d/Checkm-0.4.tar.gz"
------
Dockerfile:8
--------------------
   7 |     COPY conda-lock.yml .
   8 | >>> RUN micromamba install -y -n base -f ./conda-lock.yml && \
   9 | >>>     micromamba clean --all --yes
  10 |     
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f ./conda-lock.yml &&     micromamba clean --all --yes" did not complete successfully: exit code: 1
```

### environment.yml

```yaml
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pip
  - pip:
    - checkm
```

### ~/.condarc

```yaml
Not applicable
```

### PR DESCRIPTION
**Pull request by Hind-M**
Fix #3589

### CODE REVIEW

File: libmamba/include/mamba/specs/archive.hpp [hunk 1]
```diff
@@ -17,7 +17,8 @@ namespace mamba::specs
 {
     inline static constexpr auto ARCHIVE_EXTENSIONS = std::array{ std::string_view(".tar.bz2"),
                                                                   std::string_view(".conda"),
-                                                                  std::string_view(".whl") };
+                                                                  std::string_view(".whl"),
+                                                                  std::string_view(".tar.gz") };
```
Comment (wolfv) [inline libmamba/include/mamba/specs/archive.hpp:21]: there are a number of other potential formats: https://docs.python.org/3.10/distutils/sourcedist.html

Comment (Hind-M) [reply libmamba/include/mamba/specs/archive.hpp:21]: Cool! Thanks for the pointer :)

**Review by JohanMabille — APPROVED** [review]
