### PR TITLE
Windows menuinst

### LINKED ISSUE #3729: Menuinst shortcuts are not created when using micromamba
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

menuinst

### Latest version of Micromamba

- [X] My problem is not solved with the latest version of Micromamba

### Tried in Conda?

I do not have this problem with Conda, just with Micromamba

### Describe your issue

```
micromamba create -n test -c conda-forge --override-channels --yes -v python=3.12
```
This should create a shortcut for Spyder: `Spyder 6 (test).app` in the user's Application directory, but does not.

### mamba info / micromamba info

```shell
libmamba version : 2.0.5
     micromamba version : 2.0.5
           curl version : libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.63.0
     libarchive version : libarchive 3.7.7 zlib/1.2.12 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : /Users/rclary/.conda/envs
          package cache : /usr/local/Cellar/micromamba/2.0.5_2/pkgs
                          /Users/rclary/.mamba/pkgs
            environment : base
           env location : /usr/local/Cellar/micromamba/2.0.5_2
      user config files : /Users/rclary/.mambarc
 populated config files : /Users/rclary/.condarc
       virtual packages : __unix=0=0
                          __osx=15.2=0
                          __archspec=1=x86_64_v3
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/label/spyder_rc/noarch
                          https://conda.anaconda.org/conda-forge/label/spyder_rc/osx-64
                          https://conda.anaconda.org/conda-forge/label/spyder_kernels_rc/noarch
                          https://conda.anaconda.org/conda-forge/label/spyder_kernels_rc/osx-64
                          file:///Users/rclary/.conda/conda-bld/noarch
                          file:///Users/rclary/.conda/conda-bld/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
       base environment : /usr/local/Cellar/micromamba/2.0.5_2
               platform : osx-64
```

### Logs

<details><summary> Logs </summary>

```shell
>> micromamba create -n test -c conda-forge --override-channels --yes -v python=3.12 spyder=6.0.3
info     libmamba Searching index cache file for repo 'conda-forge/noarch'
conda-forge/noarch                                          Using cache
info     libmamba Searching index cache file for repo 'conda-forge/osx-64'
conda-forge/osx-64                                          Using cache
info     libmamba Attempting to read libsolv solv file "/usr/local/Cellar/micromamba/2.0.5_2/pkgs/cache/eb045dd1.solv" for repo https://conda.anaconda.org/conda-forge/noarch
info     libmamba Expecting solv metadata : {"etag":"\"7b3c3e701268f63ac64cda9de0281c10\"","mod":"Mon, 06 Jan 2025 19:19:32 GMT","tool_version":"2.0_0.7.31","url":"https://conda.anaconda.org/conda-forge/noarch"}
info     libmamba Loaded solv metadata : {"etag":"\"7b3c3e701268f63ac64cda9de0281c10\"","mod":"Mon, 06 Jan 2025 19:19:32 GMT","tool_version":"2.0_0.7.31","url":"https://conda.anaconda.org/conda-forge/noarch"}
info     libmamba Metadata from solv are valid, loading successful
info     libmamba Attempting to read libsolv solv file "/usr/local/Cellar/micromamba/2.0.5_2/pkgs/cache/cfe2df73.solv" for repo https://conda.anaconda.org/conda-forge/osx-64
info     libmamba Expecting solv metadata : {"etag":"\"acfc8818d22092dd4829c0c8365f586c\"","mod":"Mon, 06 Jan 2025 19:19:43 GMT","tool_version":"2.0_0.7.31","url":"https://conda.anaconda.org/conda-forge/osx-64"}
info     libmamba Loaded solv metadata : {"etag":"\"acfc8818d22092dd4829c0c8365f586c\"","mod":"Mon, 06 Jan 2025 19:19:43 GMT","tool_version":"2.0_0.7.31","url":"https://conda.anaconda.org/conda-forge/osx-64"}
info     libmamba Metadata from solv are valid, loading successful
info     libmamba Loading site packages


Transaction

  Prefix: /Users/rclary/.conda/envs/test

  Updating specs:

   - python=3.12
   - spyder=6.0.3


  Package                                 Version  Build               Channel           Size
───────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────

  + aiohappyeyeballs                        2.4.4  pyhd8ed1ab_1        conda-forge     Cached
  + aiohttp                               3.11.11  py312h3520af0_0     conda-forge     Cached
  + aiosignal                               1.3.2  pyhd8ed1ab_0        conda-forge     Cached
  + alabaster                               1.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + applaunchservices                       0.3.0  pyh534df25_4        conda-forge     Cached
  + appnope                                 0.1.4  pyhd8ed1ab_1        conda-forge     Cached
  + arrow                                   1.3.0  pyhd8ed1ab_1        conda-forge     Cached
  + astroid                                 3.3.8  py312hb401068_0     conda-forge     Cached
  + asttokens                               3.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + asyncssh                               2.19.0  pyhd8ed1ab_1        conda-forge     Cached
  + atomicwrites                            1.4.1  pyhd8ed1ab_1        conda-forge     Cached
  + attrs                                  24.3.0  pyh71513ae_0        conda-forge     Cached
  + autopep8                                2.0.4  pyhd8ed1ab_0        conda-forge     Cached
  + babel                                  2.16.0  pyhd8ed1ab_1        conda-forge     Cached
  + backports                                 1.0  pyhd8ed1ab_5        conda-forge     Cached
  + backports.tarfile                       1.2.0  pyhd8ed1ab_1        conda-forge     Cached
  + beautifulsoup4                         4.12.3  pyha770c72_1        conda-forge     Cached
  + binaryornot                             0.4.4  pyhd8ed1ab_2        conda-forge     Cached
  + black                                 24.10.0  py312hb401068_0     conda-forge     Cached
  + bleach                                  6.2.0  pyhd8ed1ab_3        conda-forge     Cached
  + brotli-python                           1.1.0  py312h5861a67_2     conda-forge     Cached
  + bzip2                                   1.0.8  hfdf4475_7          conda-forge     Cached
  + ca-certificates                    2024.12.14  h8857fd0_0          conda-forge     Cached
  + certifi                            2024.12.14  pyhd8ed1ab_0        conda-forge     Cached
  + cffi                                   1.17.1  py312hf857d28_0     conda-forge     Cached
  + chardet                                 5.2.0  py312hb401068_2     conda-forge     Cached
  + charset-normalizer                      3.4.1  pyhd8ed1ab_0        conda-forge     Cached
  + click                                   8.1.8  pyh707e725_0        conda-forge     Cached
  + cloudpickle                             3.1.0  pyhd8ed1ab_2        conda-forge     Cached
  + colorama                                0.4.6  pyhd8ed1ab_1        conda-forge     Cached
  + comm                                    0.2.2  pyhd8ed1ab_1        conda-forge     Cached
  + cookiecutter                            2.6.0  pyhd8ed1ab_1        conda-forge     Cached
  + cryptography                           44.0.0  py312h0995e51_0     conda-forge     Cached
  + cyrus-sasl                             2.1.27  hf9bab2b_7          conda-forge     Cached
  + debugpy                                1.8.11  py312haafddd8_0     conda-forge     Cached
  + decorator                               5.1.1  pyhd8ed1ab_1        conda-forge     Cached
  + defusedxml                              0.7.1  pyhd8ed1ab_0        conda-forge     Cached
  + deprecated                             1.2.15  pyhd8ed1ab_1        conda-forge     Cached
  + diff-match-patch                     20241021  pyhd8ed1ab_1        conda-forge     Cached
  + dill                                    0.3.9  pyhd8ed1ab_1        conda-forge     Cached
  + docstring-to-markdown                    0.15  pyhd8ed1ab_1        conda-forge     Cached
  + docutils                               0.21.2  pyhd8ed1ab_1        conda-forge     Cached
  + entrypoints                               0.4  pyhd8ed1ab_1        conda-forge     Cached
  + exceptiongroup                          1.2.2  pyhd8ed1ab_1        conda-forge     Cached
  + executing                               2.1.0  pyhd8ed1ab_1        conda-forge     Cached
  + flake8                                  7.1.1  pyhd8ed1ab_1        conda-forge     Cached
  + frozenlist                              1.5.0  py312h3d0f464_0     conda-forge     Cached
  + fzf                                    0.57.0  he954eb5_0          conda-forge     Cached
  + giflib                                  5.2.2  h10d778d_0          conda-forge     Cached
  + glib                                   2.82.2  hbe7352d_0          conda-forge     Cached
  + glib-tools                             2.82.2  h8a9f880_0          conda-forge     Cached
  + gst-plugins-base                       1.24.7  h0ee1d58_0          conda-forge     Cached
  + gstreamer                              1.24.7  h3271b85_0          conda-forge     Cached
  + h2                                      4.1.0  pyhd8ed1ab_1        conda-forge     Cached
  + hpack                                   4.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + hyperframe                              6.0.1  pyhd8ed1ab_1        conda-forge     Cached
  + icu                                      75.1  h120a0e1_0          conda-forge     Cached
  + idna                                     3.10  pyhd8ed1ab_1        conda-forge     Cached
  + imagesize                               1.4.1  pyhd8ed1ab_0        conda-forge     Cached
  + importlib-metadata                      8.5.0  pyha770c72_1        conda-forge     Cached
  + importlib_resources                     6.4.5  pyhd8ed1ab_1        conda-forge     Cached
  + inflection                              0.5.1  pyhd8ed1ab_1        conda-forge     Cached
  + intervaltree                            3.1.0  pyhd8ed1ab_1        conda-forge     Cached
  + ipykernel                              6.29.5  pyh57ce528_0        conda-forge     Cached
  + ipython                                8.31.0  pyh707e725_0        conda-forge     Cached
  + isort                                  5.13.2  pyhd8ed1ab_1        conda-forge     Cached
  + jaraco.classes                          3.4.0  pyhd8ed1ab_2        conda-forge     Cached
  + jaraco.context                          6.0.1  pyhd8ed1ab_0        conda-forge     Cached
  + jaraco.functools                        4.1.0  pyhd8ed1ab_0        conda-forge     Cached
  + jedi                                   0.19.2  pyhd8ed1ab_1        conda-forge     Cached
  + jellyfish                               1.1.3  py312h0d0de52_0     conda-forge     Cached
  + jinja2                                  3.1.5  pyhd8ed1ab_0        conda-forge     Cached
  + jsonschema                             4.23.0  pyhd8ed1ab_1        conda-forge     Cached
  + jsonschema-specifications           2024.10.1  pyhd8ed1ab_1        conda-forge     Cached
  + jupyter_client                          8.6.3  pyhd8ed1ab_1        conda-forge     Cached
  + jupyter_core                            5.7.2  pyh31011fe_1        conda-forge     Cached
  + jupyterlab_pygments                     0.3.0  pyhd8ed1ab_2        conda-forge     Cached
  + keyring                                25.6.0  pyh534df25_0        conda-forge     Cached
  + krb5                                   1.21.3  h37d8d59_0          conda-forge     Cached
  + lerc                                    4.0.0  hb486fe8_0          conda-forge     Cached
  + libclang-cpp17                         17.0.6  default_hb173f14_7  conda-forge     Cached
  + libclang13                             19.1.6  default_hf2b7afa_0  conda-forge     Cached
  + libcxx                                 19.1.6  hf95d169_1          conda-forge     Cached
  + libdeflate                               1.23  he65b83e_0          conda-forge     Cached
  + libedit                          3.1.20191231  hed1e85f_2          conda-forge     Cached
  + libexpat                                2.6.4  h240833e_0          conda-forge     Cached
  + libffi                                  3.4.2  h0d85af4_5          conda-forge     Cached
  + libglib                                2.82.2  hb6ef654_0          conda-forge     Cached
  + libiconv                                 1.17  hd75f5a5_2          conda-forge     Cached
  + libintl                                0.22.5  hdfe23c8_3          conda-forge     Cached
  + libintl-devel                          0.22.5  hdfe23c8_3          conda-forge     Cached
  + libjpeg-turbo                           3.0.0  h0dc2134_1          conda-forge     Cached
  + libllvm17                              17.0.6  hbedff68_1          conda-forge     Cached
  + libllvm19                              19.1.6  hc29ff6c_0          conda-forge     Cached
  + liblzma                                 5.6.3  hd471939_1          conda-forge     Cached
  + libntlm                                   1.8  h6e16a3a_0          conda-forge     Cached
  + libogg                                  1.3.5  hfdf4475_0          conda-forge     Cached
  + libopus                                 1.3.1  hc929b4f_1          conda-forge     Cached
  + libpng                                 1.6.44  h4b8f8c9_0          conda-forge     Cached
  + libpq                                    17.2  h639cf83_1          conda-forge     Cached
  + libsodium                              1.0.20  hfdf4475_0          conda-forge     Cached
  + libspatialindex                         2.1.0  h501a4e1_0          conda-forge     Cached
  + libsqlite                              3.47.2  hdb6dae5_0          conda-forge     Cached
  + libtiff                                 4.7.0  hb77a491_3          conda-forge     Cached
  + libvorbis                               1.3.7  h046ec9c_0          conda-forge     Cached
  + libwebp                                 1.5.0  h2bf92d2_0          conda-forge     Cached
  + libwebp-base                            1.5.0  h6cf52b4_0          conda-forge     Cached
  + libxml2                                2.13.5  hebb159f_1          conda-forge     Cached
  + libzlib                                 1.3.1  hd23fc13_2          conda-forge     Cached
  + markdown-it-py                          3.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + markupsafe                              3.0.2  py312h3520af0_1     conda-forge     Cached
  + matplotlib-inline                       0.1.7  pyhd8ed1ab_1        conda-forge     Cached
  + mccabe                                  0.7.0  pyhd8ed1ab_1        conda-forge     Cached
  + mdurl                                   0.1.2  pyhd8ed1ab_1        conda-forge     Cached
  + mistune                                 3.1.0  pyhd8ed1ab_0        conda-forge     Cached
  + more-itertools                         10.5.0  pyhd8ed1ab_1        conda-forge     Cached
  + multidict                               6.1.0  py312h6f3313d_1     conda-forge     Cached
  + mypy_extensions                         1.0.0  pyha770c72_1        conda-forge     Cached
  + mysql-common                            9.0.1  h4d37847_4          conda-forge     Cached
  + mysql-libs                              9.0.1  h2381dc1_4          conda-forge     Cached
  + nbclient                               0.10.2  pyhd8ed1ab_0        conda-forge     Cached
  + nbconvert                              7.16.5  hd8ed1ab_0          conda-forge     Cached
  + nbconvert-core                         7.16.5  pyhd8ed1ab_0        conda-forge     Cached
  + nbconvert-pandoc                       7.16.5  hd8ed1ab_0          conda-forge     Cached
  + nbformat                               5.10.4  pyhd8ed1ab_1        conda-forge     Cached
  + ncurses                                   6.5  hf036a51_1          conda-forge     Cached
  + nest-asyncio                            1.6.0  pyhd8ed1ab_1        conda-forge     Cached
  + nspr                                     4.36  h97d8b74_0          conda-forge     Cached
  + nss                                     3.107  h81a00e3_0          conda-forge     Cached
  + numpydoc                                1.8.0  pyhd8ed1ab_1        conda-forge     Cached
  + openldap                                2.6.9  hd8a590d_0          conda-forge     Cached
  + openssl                                 3.4.0  hc426f3f_1          conda-forge     Cached
  + packaging                                24.2  pyhd8ed1ab_2        conda-forge     Cached
  + pandoc                                  3.6.1  h694c41f_0          conda-forge     Cached
  + pandocfilters                           1.5.0  pyhd8ed1ab_0        conda-forge     Cached
  + parso                                   0.8.4  pyhd8ed1ab_1        conda-forge     Cached
  + pathspec                               0.12.1  pyhd8ed1ab_1        conda-forge     Cached
  + pcre2                                   10.44  h7634a1b_2          conda-forge     Cached
  + pexpect                                 4.9.0  pyhd8ed1ab_1        conda-forge     Cached
  + pickleshare                             0.7.5  pyhd8ed1ab_1004     conda-forge     Cached
  + pip                                    24.3.1  pyh8b19718_2        conda-forge     Cached
  + pkgutil-resolve-name                   1.3.10  pyhd8ed1ab_2        conda-forge     Cached
  + platformdirs                            4.3.6  pyhd8ed1ab_1        conda-forge     Cached
  + pluggy                                  1.5.0  pyhd8ed1ab_1        conda-forge     Cached
  + ply                                      3.11  pyhd8ed1ab_3        conda-forge     Cached
  + prompt-toolkit                         3.0.48  pyha770c72_1        conda-forge     Cached
  + propcache                               0.2.1  py312h01d7ebd_0     conda-forge     Cached
  + psutil                                  6.1.1  py312h01d7ebd_0     conda-forge     Cached
  + ptyprocess                              0.7.0  pyhd8ed1ab_1        conda-forge     Cached
  + pure_eval                               0.2.3  pyhd8ed1ab_1        conda-forge     Cached
  + pycodestyle                            2.12.1  pyhd8ed1ab_1        conda-forge     Cached
  + pyconify                                  0.2  pyhd8ed1ab_0        conda-forge     Cached
  + pycparser                                2.22  pyh29332c3_1        conda-forge     Cached
  + pydocstyle                              6.3.0  pyhd8ed1ab_1        conda-forge     Cached
  + pyflakes                                3.2.0  pyhd8ed1ab_1        conda-forge     Cached
  + pygithub                                2.5.0  pyhd8ed1ab_0        conda-forge     Cached
  + pygments                               2.18.0  pyhd8ed1ab_1        conda-forge     Cached
  + pyjwt                                  2.10.1  pyhd8ed1ab_0        conda-forge     Cached
  + pylint                                  3.3.3  pyhd8ed1ab_0        conda-forge     Cached
  + pylint-venv                             3.0.4  pyhd8ed1ab_1        conda-forge     Cached
  + pyls-spyder                             0.4.0  pyhd8ed1ab_1        conda-forge     Cached
  + pynacl                                  1.5.0  py312hb553811_4     conda-forge     Cached
  + pyobjc-core                            10.3.2  py312h2365019_0     conda-forge     Cached
  + pyobjc-framework-cocoa                 10.3.2  py312h2365019_0     conda-forge     Cached
  + pyobjc-framework-coreservices          10.3.2  py312h01d7ebd_0     conda-forge     Cached
  + pyobjc-framework-fsevents              10.3.2  py312hb401068_0     conda-forge     Cached
  + pyopenssl                              24.3.0  pyhd8ed1ab_0        conda-forge     Cached
  + pyqt                                   5.15.9  py312hd74d816_5     conda-forge     Cached
  + pyqt5-sip                             12.12.2  py312he36337a_5     conda-forge     Cached
  + pyqtwebengine                          5.15.9  py312ha74f711_5     conda-forge     Cached
  + pysocks                                 1.7.1  pyha55dd90_7        conda-forge     Cached
  + python                                 3.12.8  h9ccd52b_1_cpython  conda-forge     Cached
  + python-dateutil                   2.9.0.post0  pyhff2d567_1        conda-forge     Cached
  + python-fastjsonschema                  2.21.1  pyhd8ed1ab_0        conda-forge     Cached
  + python-gssapi                           1.9.0  py312h0919e98_1     conda-forge     Cached
  + python-lsp-black                        2.0.0  pyhff2d567_1        conda-forge     Cached
  + python-lsp-jsonrpc                      1.1.2  pyhff2d567_1        conda-forge     Cached
  + python-lsp-server                      1.12.0  pyhff2d567_1        conda-forge     Cached
  + python-lsp-server-base                 1.12.0  pyhd8ed1ab_1        conda-forge     Cached
  + python-slugify                          8.0.4  pyhd8ed1ab_1        conda-forge     Cached
  + python.app                                1.4  py312hb553811_4     conda-forge     Cached
  + python_abi                               3.12  5_cp312             conda-forge     Cached
  + pytoolconfig                            1.2.5  pyhd8ed1ab_1        conda-forge     Cached
  + pytz                                   2024.2  pyhd8ed1ab_1        conda-forge     Cached
  + pyuca                                     1.2  pyhd8ed1ab_2        conda-forge     Cached
  + pyxdg                                    0.28  pyhd8ed1ab_0        conda-forge     Cached
  + pyyaml                                  6.0.2  py312hb553811_1     conda-forge     Cached
  + pyzmq                                  26.2.0  py312h1060d5c_3     conda-forge     Cached
  + qdarkstyle                              3.2.3  pyhd8ed1ab_1        conda-forge     Cached
  + qstylizer                               0.2.4  pyhff2d567_0        conda-forge     Cached
  + qt-main                               5.15.15  h30a8c49_2          conda-forge     Cached
  + qt-webengine                          5.15.15  h46887bd_1          conda-forge     Cached
  + qtawesome                               1.3.1  pyh9208f05_1        conda-forge     Cached
  + qtconsole                               5.6.1  pyhd8ed1ab_1        conda-forge     Cached
  + qtconsole-base                          5.6.1  pyha770c72_1        conda-forge     Cached
  + qtpy                                    2.4.2  pyhd8ed1ab_1        conda-forge     Cached
  + readline                                  8.2  h9e318b2_1          conda-forge     Cached
  + referencing                            0.35.1  pyhd8ed1ab_1        conda-forge     Cached
  + requests                               2.32.3  pyhd8ed1ab_1        conda-forge     Cached
  + rich                                   13.9.4  pyhd8ed1ab_1        conda-forge     Cached
  + rope                                   1.13.0  pyhd8ed1ab_1        conda-forge     Cached
  + rpds-py                                0.22.3  py312h0d0de52_0     conda-forge     Cached
  + rtree                                   1.3.0  py312hf2eabd5_3     conda-forge     Cached
  + setuptools                             75.6.0  pyhff2d567_1        conda-forge     Cached
  + sip                                    6.7.12  py312h444b7ae_0     conda-forge     Cached
  + six                                    1.17.0  pyhd8ed1ab_0        conda-forge     Cached
  + snowballstemmer                         2.2.0  pyhd8ed1ab_0        conda-forge     Cached
  + sortedcontainers                        2.4.0  pyhd8ed1ab_0        conda-forge     Cached
  + soupsieve                                 2.5  pyhd8ed1ab_1        conda-forge     Cached
  + sphinx                                  8.1.3  pyhd8ed1ab_1        conda-forge     Cached
  + sphinxcontrib-applehelp                 2.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + sphinxcontrib-devhelp                   2.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + sphinxcontrib-htmlhelp                  2.1.0  pyhd8ed1ab_1        conda-forge     Cached
  + sphinxcontrib-jsmath                    1.0.1  pyhd8ed1ab_1        conda-forge     Cached
  + sphinxcontrib-qthelp                    2.0.0  pyhd8ed1ab_1        conda-forge     Cached
  + sphinxcontrib-serializinghtml          1.1.10  pyhd8ed1ab_1        conda-forge     Cached
  + spyder                                  6.0.3  osx_pyh1a5313d_1    conda-forge     Cached
  + spyder-kernels                          3.0.2  unix_pyh707e725_0   conda-forge     Cached
  + stack_data                              0.6.3  pyhd8ed1ab_1        conda-forge     Cached
  + superqt                                 0.7.0  pyhb6d5dde_0        conda-forge     Cached
  + tabulate                                0.9.0  pyhd8ed1ab_2        conda-forge     Cached
  + text-unidecode                            1.3  pyhd8ed1ab_2        conda-forge     Cached
  + textdistance                            4.6.3  pyhd8ed1ab_1        conda-forge     Cached
  + three-merge                             0.1.1  pyhd8ed1ab_1        conda-forge     Cached
  + tinycss2                                1.4.0  pyhd8ed1ab_0        conda-forge     Cached
  + tk                                     8.6.13  h1abcd95_1          conda-forge     Cached
  + toml                                   0.10.2  pyhd8ed1ab_1        conda-forge     Cached
  + tomli                                   2.2.1  pyhd8ed1ab_1        conda-forge     Cached
  + tomlkit                                0.13.2  pyha770c72_1        conda-forge     Cached
  + tornado                                 6.4.2  py312h01d7ebd_0     conda-forge     Cached
  + traitlets                              5.14.3  pyhd8ed1ab_1        conda-forge     Cached
  + types-python-dateutil          2.9.0.20241206  pyhd8ed1ab_0        conda-forge     Cached
  + typing-extensions                      4.12.2  hd8ed1ab_1          conda-forge     Cached
  + typing_extensions                      4.12.2  pyha770c72_1        conda-forge     Cached
  + tzdata                                  2024b  hc8b5060_0          conda-forge     Cached
  + ujson                                  5.10.0  py312h5861a67_1     conda-forge     Cached
  + urllib3                                 2.3.0  pyhd8ed1ab_0        conda-forge     Cached
  + watchdog                                6.0.0  py312h01d7ebd_0     conda-forge     Cached
  + wcwidth                                0.2.13  pyhd8ed1ab_1        conda-forge     Cached
  + webencodings                            0.5.1  pyhd8ed1ab_3        conda-forge     Cached
  + whatthepatch                            1.0.7  pyhd8ed1ab_1        conda-forge     Cached
  + wheel                                  0.45.1  pyhd8ed1ab_1        conda-forge     Cached
  + wrapt                                  1.17.0  py312h01d7ebd_0     conda-forge     Cached
  + wurlitzer                               3.1.1  pyhd8ed1ab_1        conda-forge     Cached
  + yaml                                    0.2.5  h0d85af4_2          conda-forge     Cached
  + yapf                                   0.40.1  pyhd8ed1ab_1        conda-forge     Cached
  + yarl                                   1.18.3  py312h01d7ebd_0     conda-forge     Cached
  + zeromq                                  4.3.5  h7130eaa_7          conda-forge     Cached
  + zipp                                   3.21.0  pyhd8ed1ab_1        conda-forge     Cached
  + zstandard                              0.23.0  py312h7122b0e_1     conda-forge     Cached
  + zstd                                    1.5.6  h915ae27_0          conda-forge     Cached

  Summary:

  Install: 251 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────────


info     libmamba Cleaned 0 .mamba_trash files. 0 remaining.

Transaction starting
Linking libexpat-2.6.4-h240833e_0
Linking ncurses-6.5-hf036a51_1
Linking bzip2-1.0.8-hfdf4475_7
Linking liblzma-5.6.3-hd471939_1
Linking libzlib-1.3.1-hd23fc13_2
Linking libffi-3.4.2-h0d85af4_5
Linking libcxx-19.1.6-hf95d169_1
Linking python_abi-3.12-5_cp312
Linking icu-75.1-h120a0e1_0
Linking libogg-1.3.5-hfdf4475_0
Linking ca-certificates-2024.12.14-h8857fd0_0
Linking libiconv-1.17-hd75f5a5_2
Linking libopus-1.3.1-hc929b4f_1
Linking libsodium-1.0.20-hfdf4475_0
Linking fzf-0.57.0-he954eb5_0
Linking pandoc-3.6.1-h694c41f_0
Linking libjpeg-turbo-3.0.0-h0dc2134_1
Linking giflib-5.2.2-h10d778d_0
Linking libwebp-base-1.5.0-h6cf52b4_0
Linking yaml-0.2.5-h0d85af4_2
Linking libdeflate-1.23-he65b83e_0
Linking libntlm-1.8-h6e16a3a_0
Linking libedit-3.1.20191231-hed1e85f_2
Linking readline-8.2-h9e318b2_1
Linking pcre2-10.44-h7634a1b_2
Linking zstd-1.5.6-h915ae27_0
Linking libpng-1.6.44-h4b8f8c9_0
Linking tk-8.6.13-h1abcd95_1
Linking libsqlite-3.47.2-hdb6dae5_0
Linking lerc-4.0.0-hb486fe8_0
Linking libspatialindex-2.1.0-h501a4e1_0
Linking nspr-4.36-h97d8b74_0
Linking libvorbis-1.3.7-h046ec9c_0
Linking openssl-3.4.0-hc426f3f_1
Linking libxml2-2.13.5-hebb159f_1
Linking libintl-0.22.5-hdfe23c8_3
Linking libtiff-4.7.0-hb77a491_3
Linking nss-3.107-h81a00e3_0
Linking mysql-common-9.0.1-h4d37847_4
Linking krb5-1.21.3-h37d8d59_0
Linking libllvm17-17.0.6-hbedff68_1
Linking libllvm19-19.1.6-hc29ff6c_0
Linking libintl-devel-0.22.5-hdfe23c8_3
Linking libglib-2.82.2-hb6ef654_0
Linking libwebp-1.5.0-h2bf92d2_0
Linking mysql-libs-9.0.1-h2381dc1_4
Linking zeromq-4.3.5-h7130eaa_7
Linking cyrus-sasl-2.1.27-hf9bab2b_7
Linking libclang-cpp17-17.0.6-default_hb173f14_7
Linking libclang13-19.1.6-default_hf2b7afa_0
Linking glib-tools-2.82.2-h8a9f880_0
Linking openldap-2.6.9-hd8a590d_0
Linking libpq-17.2-h639cf83_1
Linking tzdata-2024b-hc8b5060_0
Linking python-3.12.8-h9ccd52b_1_cpython
Linking wheel-0.45.1-pyhd8ed1ab_1
info     libmamba Running wrapped python compilation command /Users/rclary/.conda/envs/test/bin/python3.12 -Wi -u /var/folders/5v/28jqvwxs2cd5fj93gvwnykdrqc926z/T/mambaf2zybynxkjj
info     libmamba Compiling 28 files to pyc
Linking setuptools-75.6.0-pyhff2d567_1
info     libmamba Compiling 349 files to pyc
Linking pip-24.3.1-pyh8b19718_2
info     libmamba Compiling 411 files to pyc
Linking hyperframe-6.0.1-pyhd8ed1ab_1
info     libmamba Compiling 4 files to pyc
Linking hpack-4.0.0-pyhd8ed1ab_1
info     libmamba Compiling 8 files to pyc
Linking mdurl-0.1.2-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking python-fastjsonschema-2.21.1-pyhd8ed1ab_0
info     libmamba Compiling 10 files to pyc
Linking wcwidth-0.2.13-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking text-unidecode-1.3-pyhd8ed1ab_2
info     libmamba Compiling 1 files to pyc
Linking pure_eval-0.2.3-pyhd8ed1ab_1
info     libmamba Compiling 5 files to pyc
Linking executing-2.1.0-pyhd8ed1ab_1
info     libmamba Compiling 5 files to pyc
Linking asttokens-3.0.0-pyhd8ed1ab_1
info     libmamba Compiling 7 files to pyc
Linking pysocks-1.7.1-pyha55dd90_7
info     libmamba Compiling 2 files to pyc
Linking aiohappyeyeballs-2.4.4-pyhd8ed1ab_1
info     libmamba Compiling 5 files to pyc
Linking pathspec-0.12.1-pyhd8ed1ab_1
info     libmamba Compiling 8 files to pyc
Linking mypy_extensions-1.0.0-pyha770c72_1
info     libmamba Compiling 1 files to pyc
Linking pycparser-2.22-pyh29332c3_1
info     libmamba Compiling 17 files to pyc
Linking six-1.17.0-pyhd8ed1ab_0
info     libmamba Compiling 1 files to pyc
Linking ply-3.11-pyhd8ed1ab_3
info     libmamba Compiling 6 files to pyc
Linking types-python-dateutil-2.9.0.20241206-pyhd8ed1ab_0
Linking pytz-2024.2-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking backports-1.0-pyhd8ed1ab_5
info     libmamba Compiling 1 files to pyc
Linking soupsieve-2.5-pyhd8ed1ab_1
info     libmamba Compiling 7 files to pyc
Linking webencodings-0.5.1-pyhd8ed1ab_3
info     libmamba Compiling 5 files to pyc
Linking click-8.1.8-pyh707e725_0
info     libmamba Compiling 16 files to pyc
Linking zipp-3.21.0-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking sortedcontainers-2.4.0-pyhd8ed1ab_0
info     libmamba Compiling 4 files to pyc
Linking nest-asyncio-1.6.0-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking appnope-0.1.4-pyhd8ed1ab_1
info     libmamba Compiling 3 files to pyc
Linking exceptiongroup-1.2.2-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking decorator-5.1.1-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking more-itertools-10.5.0-pyhd8ed1ab_1
info     libmamba Compiling 3 files to pyc
Linking pkgutil-resolve-name-1.3.10-pyhd8ed1ab_2
info     libmamba Compiling 1 files to pyc
Linking attrs-24.3.0-pyh71513ae_0
info     libmamba Compiling 19 files to pyc
Linking pandocfilters-1.5.0-pyhd8ed1ab_0
info     libmamba Compiling 1 files to pyc
Linking defusedxml-0.7.1-pyhd8ed1ab_0
info     libmamba Compiling 11 files to pyc
Linking traitlets-5.14.3-pyhd8ed1ab_1
info     libmamba Compiling 24 files to pyc
Linking entrypoints-0.4-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking tabulate-0.9.0-pyhd8ed1ab_2
info     libmamba Compiling 2 files to pyc
Linking ptyprocess-0.7.0-pyhd8ed1ab_1
info     libmamba Compiling 4 files to pyc
Linking pyjwt-2.10.1-pyhd8ed1ab_0
info     libmamba Compiling 12 files to pyc
Linking typing_extensions-4.12.2-pyha770c72_1
info     libmamba Compiling 1 files to pyc
Linking tomlkit-0.13.2-pyha770c72_1
info     libmamba Compiling 13 files to pyc
Linking platformdirs-4.3.6-pyhd8ed1ab_1
info     libmamba Compiling 8 files to pyc
Linking isort-5.13.2-pyhd8ed1ab_1
info     libmamba Compiling 44 files to pyc
Linking dill-0.3.9-pyhd8ed1ab_1
info     libmamba Compiling 46 files to pyc
Linking whatthepatch-1.0.7-pyhd8ed1ab_1
info     libmamba Compiling 5 files to pyc
Linking pyflakes-3.2.0-pyhd8ed1ab_1
info     libmamba Compiling 21 files to pyc
Linking pycodestyle-2.12.1-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking mccabe-0.7.0-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking pluggy-1.5.0-pyhd8ed1ab_1
info     libmamba Compiling 8 files to pyc
Linking docstring-to-markdown-0.15-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking inflection-0.5.1-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking idna-3.10-pyhd8ed1ab_1
info     libmamba Compiling 8 files to pyc
Linking charset-normalizer-3.4.1-pyhd8ed1ab_0
info     libmamba Compiling 12 files to pyc
Linking certifi-2024.12.14-pyhd8ed1ab_0
info     libmamba Compiling 3 files to pyc
Linking imagesize-1.4.1-pyhd8ed1ab_0
info     libmamba Compiling 2 files to pyc
Linking tomli-2.2.1-pyhd8ed1ab_1
info     libmamba Compiling 4 files to pyc
Linking sphinxcontrib-jsmath-1.0.1-pyhd8ed1ab_1
info     libmamba Compiling 2 files to pyc
Linking docutils-0.21.2-pyhd8ed1ab_1
info     libmamba Compiling 128 files to pyc
Linking colorama-0.4.6-pyhd8ed1ab_1
info     libmamba Compiling 13 files to pyc
Linking alabaster-1.0.0-pyhd8ed1ab_1
info     libmamba Compiling 2 files to pyc
Linking textdistance-4.6.3-pyhd8ed1ab_1
info     libmamba Compiling 14 files to pyc
Linking snowballstemmer-2.2.0-pyhd8ed1ab_0
info     libmamba Compiling 32 files to pyc
Linking pyuca-1.2-pyhd8ed1ab_2
info     libmamba Compiling 4 files to pyc
Linking pylint-venv-3.0.4-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking pygments-2.18.0-pyhd8ed1ab_1
info     libmamba Compiling 327 files to pyc
Linking pickleshare-0.7.5-pyhd8ed1ab_1004
info     libmamba Compiling 1 files to pyc
Linking parso-0.8.4-pyhd8ed1ab_1
info     libmamba Compiling 21 files to pyc
Linking diff-match-patch-20241021-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking atomicwrites-1.4.1-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking pyxdg-0.28-pyhd8ed1ab_0
info     libmamba Compiling 13 files to pyc
Linking wurlitzer-3.1.1-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking cloudpickle-3.1.0-pyhd8ed1ab_2
info     libmamba Compiling 3 files to pyc
Linking toml-0.10.2-pyhd8ed1ab_1
info     libmamba Compiling 5 files to pyc
Linking packaging-24.2-pyhd8ed1ab_2
info     libmamba Compiling 16 files to pyc
Linking h2-4.1.0-pyhd8ed1ab_1
info     libmamba Compiling 11 files to pyc
Linking markdown-it-py-3.0.0-pyhd8ed1ab_1
info     libmamba Compiling 66 files to pyc
Linking prompt-toolkit-3.0.48-pyha770c72_1
info     libmamba Compiling 144 files to pyc
Linking python-slugify-8.0.4-pyhd8ed1ab_1
info     libmamba Compiling 5 files to pyc
Linking stack_data-0.6.3-pyhd8ed1ab_1
info     libmamba Compiling 6 files to pyc
Linking python-dateutil-2.9.0.post0-pyhff2d567_1
info     libmamba Compiling 18 files to pyc
Linking babel-2.16.0-pyhd8ed1ab_1
info     libmamba Compiling 27 files to pyc
Linking backports.tarfile-1.2.0-pyhd8ed1ab_1
info     libmamba Compiling 4 files to pyc
Linking beautifulsoup4-4.12.3-pyha770c72_1
info     libmamba Compiling 27 files to pyc
Linking bleach-6.2.0-pyhd8ed1ab_3
info     libmamba Compiling 43 files to pyc
Linking tinycss2-1.4.0-pyhd8ed1ab_0
info     libmamba Compiling 9 files to pyc
Linking importlib_resources-6.4.5-pyhd8ed1ab_1
info     libmamba Compiling 30 files to pyc
Linking importlib-metadata-8.5.0-pyha770c72_1
info     libmamba Compiling 12 files to pyc
Linking intervaltree-3.1.0-pyhd8ed1ab_1
info     libmamba Compiling 4 files to pyc
Linking jaraco.functools-4.1.0-pyhd8ed1ab_0
info     libmamba Compiling 1 files to pyc
Linking jaraco.classes-3.4.0-pyhd8ed1ab_2
info     libmamba Compiling 4 files to pyc
Linking comm-0.2.2-pyhd8ed1ab_1
info     libmamba Compiling 2 files to pyc
Linking matplotlib-inline-0.1.7-pyhd8ed1ab_1
info     libmamba Compiling 3 files to pyc
Linking pexpect-4.9.0-pyhd8ed1ab_1
info     libmamba Compiling 18 files to pyc
Linking mistune-3.1.0-pyhd8ed1ab_0
info     libmamba Compiling 35 files to pyc
Linking typing-extensions-4.12.2-hd8ed1ab_1
Linking jupyter_core-5.7.2-pyh31011fe_1
info     libmamba Compiling 10 files to pyc
Linking flake8-7.1.1-pyhd8ed1ab_1
info     libmamba Compiling 33 files to pyc
Linking pydocstyle-6.3.0-pyhd8ed1ab_1
info     libmamba Compiling 10 files to pyc
Linking jupyterlab_pygments-0.3.0-pyhd8ed1ab_2
info     libmamba Compiling 3 files to pyc
Linking jedi-0.19.2-pyhd8ed1ab_1
info     libmamba Compiling 84 files to pyc
Linking three-merge-0.1.1-pyhd8ed1ab_1
info     libmamba Compiling 2 files to pyc
Linking qtpy-2.4.2-pyhd8ed1ab_1
info     libmamba Compiling 137 files to pyc
Linking autopep8-2.0.4-pyhd8ed1ab_0
info     libmamba Compiling 1 files to pyc
Linking rich-13.9.4-pyhd8ed1ab_1
info     libmamba Compiling 78 files to pyc
Linking arrow-1.3.0-pyhd8ed1ab_1
info     libmamba Compiling 10 files to pyc
Linking jaraco.context-6.0.1-pyhd8ed1ab_0
info     libmamba Compiling 1 files to pyc
Linking qstylizer-0.2.4-pyhff2d567_0
info     libmamba Compiling 10 files to pyc
Linking yapf-0.40.1-pyhd8ed1ab_1
info     libmamba Compiling 71 files to pyc
Linking pytoolconfig-1.2.5-pyhd8ed1ab_1
info     libmamba Compiling 14 files to pyc
Linking ipython-8.31.0-pyh707e725_0
info     libmamba Compiling 275 files to pyc
Linking qtawesome-1.3.1-pyh9208f05_1
info     libmamba Compiling 8 files to pyc
Linking qdarkstyle-3.2.3-pyhd8ed1ab_1
info     libmamba Compiling 17 files to pyc
Linking keyring-25.6.0-pyh534df25_0
info     libmamba Compiling 29 files to pyc
Linking rope-1.13.0-pyhd8ed1ab_1
info     libmamba Compiling 97 files to pyc
Linking brotli-python-1.1.0-py312h5861a67_2
Linking frozenlist-1.5.0-py312h3d0f464_0
Linking multidict-6.1.0-py312h6f3313d_1
Linking pyobjc-core-10.3.2-py312h2365019_0
Linking pyyaml-6.0.2-py312hb553811_1
Linking wrapt-1.17.0-py312h01d7ebd_0
Linking debugpy-1.8.11-py312haafddd8_0
Linking rpds-py-0.22.3-py312h0d0de52_0
Linking tornado-6.4.2-py312h01d7ebd_0
Linking markupsafe-3.0.2-py312h3520af0_1
Linking ujson-5.10.0-py312h5861a67_1
Linking propcache-0.2.1-py312h01d7ebd_0
Linking rtree-1.3.0-py312hf2eabd5_3
Linking python.app-1.4-py312hb553811_4

Linking psutil-6.1.1-py312h01d7ebd_0
Linking jellyfish-1.1.3-py312h0d0de52_0
Linking chardet-5.2.0-py312hb401068_2
Linking astroid-3.3.8-py312hb401068_0
Linking pyzmq-26.2.0-py312h1060d5c_3
Linking cffi-1.17.1-py312hf857d28_0
Linking python-gssapi-1.9.0-py312h0919e98_1
Linking black-24.10.0-py312hb401068_0
Linking sip-6.7.12-py312h444b7ae_0
Linking glib-2.82.2-hbe7352d_0
Linking pyobjc-framework-cocoa-10.3.2-py312h2365019_0
Linking watchdog-6.0.0-py312h01d7ebd_0
Linking yarl-1.18.3-py312h01d7ebd_0
Linking zstandard-0.23.0-py312h7122b0e_1
Linking cryptography-44.0.0-py312h0995e51_0
Linking pynacl-1.5.0-py312hb553811_4
Linking pyqt5-sip-12.12.2-py312he36337a_5
Linking gstreamer-1.24.7-h3271b85_0
Linking pyobjc-framework-fsevents-10.3.2-py312hb401068_0
Linking gst-plugins-base-1.24.7-h0ee1d58_0
Linking pyobjc-framework-coreservices-10.3.2-py312h01d7ebd_0
Linking qt-main-5.15.15-h30a8c49_2
Linking qt-webengine-5.15.15-h46887bd_1
Linking pyqt-5.15.9-py312hd74d816_5
Linking pyqtwebengine-5.15.9-py312ha74f711_5
Linking aiosignal-1.3.2-pyhd8ed1ab_0
info     libmamba Compiling 1 files to pyc
Linking deprecated-1.2.15-pyhd8ed1ab_1
info     libmamba Compiling 3 files to pyc
Linking referencing-0.35.1-pyhd8ed1ab_1
info     libmamba Compiling 13 files to pyc
Linking jinja2-3.1.5-pyhd8ed1ab_0
info     libmamba Compiling 25 files to pyc
Linking python-lsp-jsonrpc-1.1.2-pyhff2d567_1
info     libmamba Compiling 6 files to pyc
Linking binaryornot-0.4.4-pyhd8ed1ab_2
info     libmamba Compiling 3 files to pyc
Linking pylint-3.3.3-pyhd8ed1ab_0
info     libmamba Compiling 175 files to pyc
Linking jupyter_client-8.6.3-pyhd8ed1ab_1
info     libmamba Compiling 38 files to pyc
Linking urllib3-2.3.0-pyhd8ed1ab_0
info     libmamba Compiling 36 files to pyc
Linking pyopenssl-24.3.0-pyhd8ed1ab_0
info     libmamba Compiling 7 files to pyc
Linking applaunchservices-0.3.0-pyh534df25_4
info     libmamba Compiling 3 files to pyc
Linking jsonschema-specifications-2024.10.1-pyhd8ed1ab_1
info     libmamba Compiling 4 files to pyc
Linking python-lsp-server-base-1.12.0-pyhd8ed1ab_1
info     libmamba Compiling 38 files to pyc
Linking ipykernel-6.29.5-pyh57ce528_0
info     libmamba Compiling 43 files to pyc
Linking requests-2.32.3-pyhd8ed1ab_1
info     libmamba Compiling 18 files to pyc
Linking asyncssh-2.19.0-pyhd8ed1ab_1
info     libmamba Compiling 66 files to pyc
Linking jsonschema-4.23.0-pyhd8ed1ab_1
info     libmamba Compiling 34 files to pyc
Linking python-lsp-server-1.12.0-pyhff2d567_1
Linking qtconsole-base-5.6.1-pyha770c72_1
info     libmamba Compiling 43 files to pyc
Linking spyder-kernels-3.0.2-unix_pyh707e725_0
info     libmamba Compiling 30 files to pyc
Linking pyconify-0.2-pyhd8ed1ab_0
info     libmamba Compiling 5 files to pyc
Linking sphinx-8.1.3-pyhd8ed1ab_1
info     libmamba Compiling 202 files to pyc
Linking sphinxcontrib-serializinghtml-1.1.10-pyhd8ed1ab_1
info     libmamba Compiling 2 files to pyc
Linking pygithub-2.5.0-pyhd8ed1ab_0
info     libmamba Compiling 155 files to pyc
Linking cookiecutter-2.6.0-pyhd8ed1ab_1
info     libmamba Compiling 18 files to pyc
Linking nbformat-5.10.4-pyhd8ed1ab_1
info     libmamba Compiling 40 files to pyc
Linking python-lsp-black-2.0.0-pyhff2d567_1
info     libmamba Compiling 2 files to pyc
Linking pyls-spyder-0.4.0-pyhd8ed1ab_1
info     libmamba Compiling 3 files to pyc
Linking qtconsole-5.6.1-pyhd8ed1ab_1
Linking superqt-0.7.0-pyhb6d5dde_0
info     libmamba Compiling 46 files to pyc
Linking sphinxcontrib-applehelp-2.0.0-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking nbclient-0.10.2-pyhd8ed1ab_0
info     libmamba Compiling 8 files to pyc
Linking sphinxcontrib-devhelp-2.0.0-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking nbconvert-core-7.16.5-pyhd8ed1ab_0
info     libmamba Compiling 72 files to pyc
Linking sphinxcontrib-htmlhelp-2.1.0-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking nbconvert-pandoc-7.16.5-hd8ed1ab_0
Linking sphinxcontrib-qthelp-2.0.0-pyhd8ed1ab_1
info     libmamba Compiling 1 files to pyc
Linking nbconvert-7.16.5-hd8ed1ab_0
Linking numpydoc-1.8.0-pyhd8ed1ab_1
info     libmamba Compiling 20 files to pyc
Linking aiohttp-3.11.11-py312h3520af0_0
Linking spyder-6.0.3-osx_pyh1a5313d_1
info     libmamba Compiling 488 files to pyc

info     libmamba Waiting for pyc compilation to finish

Transaction finished

To activate this environment, use:

    micromamba activate test

Or to execute a single command in this environment, use:

    micromamba run -n test mycommand

info     libmamba Opening history file: "/Users/rclary/.conda/envs/test/conda-meta/history"
>>
```
</details>

### environment.yml

_No response_

### ~/.condarc

```yaml
channels:
  - conda-forge
  - conda-forge/label/spyder_rc
  - conda-forge/label/spyder_kernels_rc
  - /Users/rclary/.conda/conda-bld
  - defaults
channel_priority: flexible
auto_activate_base: false
show_channel_urls: true
envs_dirs:
  - ~/.conda/envs
conda_build:
  root-dir: /Users/rclary/.conda/conda-bld
  pkg_format: '2'
  zstd_compression_level: '19'
bld_path: /Users/rclary/.conda/conda-bld
```

### PR DESCRIPTION
**Pull request by Hind-M**
Fix #3729

### CODE REVIEW

**Comment by Hind-M** [comment]
In `mamba/micromamba`, `menuinst` shortcuts are only implemented for windows.
`menuinst` schema changes in v2 were not taken into account in `mamba/micromamba` indeed.
This PR fixes the issue with the new items in `name`, i.e:
```
"name": {
    "target_environment_is_base": "Reset Spyder __PKG_MAJOR_VER__ ({{ DISTRIBUTION_NAME }}) to default settings",
    "target_environment_is_not_base": "Reset Spyder __PKG_MAJOR_VER__ ({{ ENV_NAME }}) to default settings"
}
```
but not sure this is enough in general.
@mrclary @ericpre I would be really interested if you can provide other packages schemas with additional keys and/or use cases with corresponding expectations to be sure we're covering everything in the tests.
Thanks!

**Comment by mrclary** [comment]
Spyder uses a post-link script to make changes to the json file depending on install-time factors (`menuinst` version and environment type).
https://github.com/conda-forge/spyder-feedstock/blob/main/recipe/spyder-menu-unix.json
https://github.com/conda-forge/spyder-feedstock/blob/main/recipe/spyder-menu-win.json
https://github.com/conda-forge/spyder-feedstock/blob/main/recipe/spyder-menu-v1.json

**Comment by Hind-M** [comment]
>  https://github.com/conda-forge/mne-feedstock/blob/main/recipe/meta.yaml#L122

Interesting to see that in [mne](https://github.com/conda-forge/mne-feedstock/blob/08355b8a5cd76fec2ae7d4e3d16245fdc754da5a/recipe/menu/menu.json#L2-L3), `"$schema"` and `"$id"` keys are both present but the name is still a string and not an object, which contradicts what's specified in the [CEP](https://github.com/conda/ceps/blob/3da0fb0ece/cep-11.md#backwards-compatibility). I'm wondering if this should be fixed in `mne`.

**Review by JohanMabille — APPROVED** [review]

File: libmamba/src/core/menuinst.cpp [hunk 1]
```diff
@@ -333,56 +339,85 @@ namespace mamba
...
                 }
-                else
+                else  // MenuInstVersion::Version2
                 {
-                    LOG_ERROR << "Unknown shortcut type found in " << json_file;
-                    throw std::runtime_error("Unknown shortcut type.");
+                    // `item["name"]` should be an object containing items with
+                    // "target_environment_is_base" and "target_environment_is_not_base"(default)
+                    // as keys
+                    name = item["name"]["target_environment_is_not_base"];
```
Comment (jaimergp) [inline libmamba/src/core/menuinst.cpp:409]: This is not totally correct. It could also be a string. See schema at https://conda.github.io/menuinst/reference/#menuinst._schema.MenuItem.name.
