### PR TITLE
Fix VersionSpec globs

### LINKED ISSUE #3601: Inconsistencies with globs in `MatchSpec` parsing
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

matchspec glob

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I have detected some parsing / roundtrip issues with libmamba `MatchSpec` objects:

This should be valid (although it's a redundant version glob):

```python
>>> print(MatchSpec.parse("name *,*.* build*"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
libmambapy.bindings.specs.ParseError: Found invalid version predicate in "*.*"
>>> print(MatchSpecConda("name *,*.* build*"))
name[version='*,*.*',build=build*]
```

Also, when passing this spec to the solver, the error message is lossy. Note how the trailing `*` is lost in the build string:

```python
 {
  "Install": [
    "accelerate[version=\"=*,=*\",build=\"np17py27*\"]"
  ]
}
```

```
Could not solve for environment specs
The following package could not be installed
└─ accelerate =*,=* np17py27 does not exist (perhaps a typo or a missing channel).
```

### mamba info / micromamba info

```shell
libmamba version : 2.0.3
          mamba version : 2.0.3
           curl version : libcurl/8.10.1 OpenSSL/3.4.0 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /root/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /root/.mambarc
 populated config files : /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
```

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by AntoinePrv**
@jaimergp @jdblischak this should solve a number of cases. I'm happy to add more test cases if you have some to suggest.
Fix #3601 

Note that full regex on versions are **not** implemented.

### CODE REVIEW

File: libmamba/src/specs/version_spec.cpp [hunk 1]
```diff
@@ -65,6 +68,91 @@ namespace mamba::specs
...
+                if (pat_it == pat_last)
+                {
+                    break;
+                }
+
+                // Find the end of the sub pattern, i.e. to the start of the next glob.
+                // This is required to avoid greedily matching on the first similar character.
+                const auto pat_sub_last = std::find_if(pat_sub_first, pat_last, is_glob_part);
+
+                // At this cand we have a required pattern.
```
Comment (jjerphan) [inline libmamba/src/specs/version_spec.cpp:109]: What do you mean by `cand`? Candidate?

File: libmamba/tests/src/specs/test_version_spec.cpp [hunk 2]
```diff
@@ -108,13 +108,74 @@ namespace
...
+        REQUIRE(g7.str() == "2.*.1.1.*");
+
+        const auto predicates = std::array{
+            free, eq, ne, lt, le, gt, ge, sw, cp2, cp3, g1, g2, g3, g4, g5, g6, g7,
+        };
+        REQUIRE("*.0"_v != "*.0.*"_v);
         for (std::size_t i = 0; i < predicates.size(); ++i)
         {
-            REQUIRE(predicates[i] == predicates[i]);
+            CAPTURE(i);
```
Comment (jjerphan) [inline libmamba/tests/src/specs/test_version_spec.cpp:173]:
```suggestion
```

File: libmamba/tests/src/specs/test_version_spec.cpp [hunk 3]
```diff
@@ -108,13 +108,74 @@ namespace
...
+            CHECK(predicates[i] == predicates[i]);
             for (std::size_t j = i + 1; j < predicates.size(); ++j)
             {
-                REQUIRE(predicates[i] != predicates[j]);
+                CAPTURE(j);
```
Comment (jjerphan) [inline libmamba/tests/src/specs/test_version_spec.cpp:177]:
```suggestion
```

**Review by jjerphan — APPROVED** [review]
LGTM.

I have a few questions and suggestions.

File: libmamba/src/specs/version_spec.cpp (hunk 1 above)
Comment (AntoinePrv) [reply libmamba/src/specs/version_spec.cpp:109]: candidate, yes. This was a brute find-replace

**Comment by jdblischak** [comment]
@AntoinePrv how can I locally test this branch? I couldn't find any developer docs on how to setup a local development environment (eg I checked [`CONTRIBUTING.rst`](https://github.com/mamba-org/mamba/blob/64a620a2aa046d7508a302a06d63f49425b48b7b/CONTRIBUTING.rst).

I tried following the instructions to [build micromamba from source](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html#build-from-source), but I assume I did something wrong because `micromamba` built from this PR behaved exactly the same as `micromamba` built from main (64a620a2aa046d7508a302a06d63f49425b48b7b).


<details><summary>Details of attempt to test behavior with source build of micromamba</summary>
<p>


```sh
# Setup
docker run --rm -it condaforge/miniforge3 bash
mamba init
source ~/.bashrc
git clone https://github.com/mamba-org/mamba.git
cd mamba/
mamba env create -n mamba-from-source --file dev/environment-micromamba-static.yml
mamba activate mamba-from-source

# Build latest from main
git log -n 1 --pretty=reference
## 64a620a2 (ci: Adapt code coverage workflow (#3890), 2025-04-11)
cmake -B build-main/ \
    -G Ninja \
    ${CMAKE_ARGS} \
    -D CMAKE_INSTALL_PREFIX="${CONDA_PREFIX}" \
    -D CMAKE_BUILD_TYPE="Release" \
    -D BUILD_LIBMAMBA=ON \
    -D BUILD_STATIC=ON \
    -D BUILD_MICROMAMBA=ON
cmake --build build-main/ --parallel
./build-main/micromamba/micromamba --version
## 2.1.0

# Trailing glob works
./build-main/micromamba/micromamba create -n test --dry-run 'python=3.*'
## + python               3.13.3  hf636f53_100_cp313  conda-forge      33MB
# Internal glob fails
./build-main/micromamba/micromamba create -n test --dry-run 'python=3.*.1'
## error    libmamba Could not solve for environment specs
##     The following package could not be installed
##     └─ python =3.0*.1 * does not exist (perhaps a typo or a missing channel).
## critical libmamba Could not solve for environment specs
# Leading glob fails
./build-main/micromamba/micromamba create -n test --dry-run 'python=*.13.3'
## error    libmamba Could not solve for environment specs
##     The following package could not be installed
##     └─ python =0*.13.3 * does not exist (perhaps a typo or a missing channel).
## critical libmamba Could not solve for environment specs

# Build from PR 3889
git remote add AntoinePrv https://github.com/AntoinePrv/fork-mamba-org-mamba.git
git fetch AntoinePrv
git checkout -t AntoinePrv/fix-version-spec
git log -n 1 --pretty=reference
## fab70f0f (Cleanup, 2025-04-14)
cmake -B build-pr3889/ \
    -G Ninja \
    ${CMAKE_ARGS} \
    -D CMAKE_INSTALL_PREFIX="${CONDA_PREFIX}" \
    -D CMAKE_BUILD_TYPE="Release" \
    -D BUILD_LIBMAMBA=ON \
    -D BUILD_STATIC=ON \
    -D BUILD_MICROMAMBA=ON
cmake --build build-pr3889/ --parallel
./build-pr3889/micromamba/micromamba --version
## 2.1.0
# Trailing glob works
./build-pr3889/micromamba/micromamba create -n test --dry-run 'python=3.*'
## + python               3.13.3  hf636f53_100_cp313  conda-forge      33MB
# Internal glob fails
./build-pr3889/micromamba/micromamba create -n test --dry-run 'python=3.*.1'
## error    libmamba Could not solve for environment specs
##     The following package could not be installed
##     └─ python =3.0*.1 * does not exist (perhaps a typo or a missing channel).
## critical libmamba Could not solve for environment specs
# Leading glob fails
./build-pr3889/micromamba/micromamba create -n test --dry-run 'python=*.13.3'
## error    libmamba Could not solve for environment specs
##     The following package could not be installed
##     └─ python =0*.13.3 * does not exist (perhaps a typo or a missing channel).
## critical libmamba Could not solve for environment specs
```


</p>
</details>

**Comment by AntoinePrv** [comment]
@jdblischak we have [doc on dev environment](https://mamba.readthedocs.io/en/latest/developer_zone/dev_environment.html) but I guess you have everything right.

I believe that I have not anticipated this case. `python=3.*.1` get split into `python` + `=3.*.1` and the leading `=` in the version prevents it from being treated as a glob (we see `=3.0*.1` meaning it is treated as a `0*`). If you try `python 3.*.1` I think it would work. I think we should handle `python=3.*.1` as glob, but I am not sure about precedent here. @jaimergp ? @jjerphan ?

**Comment by jjerphan** [comment]
> I think we should handle `python=3.*.1` as glob, but I am not sure about precedent here.

I think this also must be handled, yes.

File: libmamba/src/specs/version_spec.cpp [hunk 4]
```diff
@@ -311,6 +438,28 @@ namespace mamba::specs
...
+        if (expression_size() == 0)
+        {
+            return false;
+        }
+
+        auto found = false;
+        m_tree.infix_for_each(
+            [&found](const auto& elem)
+            {
+                using Elem = std::remove_cv_t<std::remove_reference_t<decltype(elem)>>;
```
Comment (jjerphan) [inline libmamba/src/specs/version_spec.cpp:452]: Would this work?
```suggestion
                using Elem = std::decay_t<decltype(elem)>;
```

File: libmamba/src/specs/version_spec.cpp [hunk 5]
```diff
@@ -172,7 +290,13 @@ namespace mamba::specs
 
     auto operator==(const VersionPredicate& lhs, const VersionPredicate& rhs) -> bool
     {
-        return (lhs.m_operator == rhs.m_operator) && (lhs.m_version == rhs.m_version);
+        return (lhs.m_operator == rhs.m_operator)  //
+               && (lhs.m_version == rhs.m_version)
+               // In version_glob, the version is not understood purely as a version since ``*``
+               // has different meaning, as explicit trailing zeros.
+               // Versions should be made part of this variant internal and handled there.
```
Comment (jjerphan) [inline libmamba/src/specs/version_spec.cpp:297]: Is it worth referencing https://github.com/conda/ceps/pull/60 here?

```suggestion
               // Versions should be made part of this variant internal and handled there.
               // On the different meanings of ``*``, see this CEP: https://github.com/conda/ceps/pull/60
```

File: libmamba/tests/src/specs/test_match_spec.cpp [hunk 6]
```diff
@@ -1205,9 +1226,96 @@ namespace
...
+                /* .build_number= */ 0,
+                /* .md5= */ "lemd5",
+                /* .sha256= */ "somesha256",
+                /* .license= */ "some-license",
+                /* .platform= */ "linux-64",
+                /* .track_features =*/{},
+            }));
+        }
+
+        SECTION("python=3.*.1")
```
Comment (jjerphan) [inline libmamba/tests/src/specs/test_match_spec.cpp:1259]: FYI, @jdblischak.

**Review by jjerphan — APPROVED** [review]
Thank you, @AntoinePrv.

**Comment by jdblischak** [comment]
> we have [doc on dev environment](https://mamba.readthedocs.io/en/latest/developer_zone/dev_environment.html) but I guess you have everything right.

Thanks! I'm embarrassed I miss these instructions. Using a combination of these docs on [Development Environment](https://mamba.readthedocs.io/en/latest/developer_zone/dev_environment.html) and [Micromamba Installation](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html#umamba-install) (to initialize micromamba to use `micromamba activate`), I was able to install libmamba and libmambapy.

In case it could be useful to other contributors, here is the code I ran in a Docker container to test this PR:

```sh
docker run --rm -it ubuntu:24.04 bash
apt-get update
apt-get install --yes bzip2 curl git tar
curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
./bin/micromamba shell init -s bash -r ~/micromamba
source ~/.bashrc
micromamba --version
## 2.1.0

git clone https://github.com/mamba-org/mamba.git
cd mamba/
git remote add AntoinePrv https://github.com/AntoinePrv/fork-mamba-org-mamba.git
git fetch AntoinePrv
git checkout -t AntoinePrv/fix-version-spec
git log -n 1 --pretty=reference
## d5346f1b (Nit fixes, 2025-04-17)

micromamba create --yes -n mamba -c conda-forge \
  -f dev/environment-dev.yml -f dev/environment-dev-extra.yml
micromamba activate mamba

cmake -B build/ -G Ninja --preset mamba-unix-shared-debug-dev
cmake --build build/ --parallel
./build/libmamba/tests/test_libmamba
cmake --install build/ --prefix "${CONDA_PREFIX}"
python -m pip install --no-deps --no-build-isolation libmambapy/
python -m pytest libmambapy/tests
```

**Comment by jdblischak** [comment]
Also, I ran the same Python test code as I did with libmambapy 2.0.4 in https://github.com/mamba-org/mamba/issues/3601#issuecomment-2518353107 to confirm that internal and leading version globs now behave as I expect:

```python
import libmambapy

libmambapy.version.version_info
## ('2', '1', '0')

import libmambapy.specs as specs

specs.VersionSpec.parse("0.0.*")
specs.VersionSpec.parse("0.*.0")
specs.VersionSpec.parse("*.0.0")

# Trailing glob works as expected
specs.VersionSpec.parse("0.0.*").contains(specs.Version.parse("0.0.1"))
## True
specs.VersionSpec.parse("0.0.*").contains(specs.Version.parse("1.0.0"))
## False

# Internal glob now works as expected
specs.VersionSpec.parse("0.*.0").contains(specs.Version.parse("0.1.0"))
## True
specs.VersionSpec.parse("0.*.0").contains(specs.Version.parse("1.0.0"))
## False

# Leading glob now works as expected
specs.VersionSpec.parse("*.0.0").contains(specs.Version.parse("1.0.0"))
## True
specs.VersionSpec.parse("*.0.0").contains(specs.Version.parse("0.0.1"))
## False
```

**Review by jdblischak — APPROVED** [review]
Thanks @AntoinePrv!
