### PR TITLE
fix: Parse `remote_connect_timeout_secs` as a double

### LINKED ISSUE #2934: Micromamba does not parse remote_connect_timeout_secs in condarc correctly
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

remote_connect_timeout_secs

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

In the [latest conda configuration documentation](https://docs.conda.io/projects/conda/en/latest/configuration.html), the `remote_connect_timeout_secs` variable is specified as a float:

```bash
# # remote_connect_timeout_secs (float)
# #   The number seconds conda will wait for your client to establish a
# #   connection to a remote url resource.
# # 
# remote_connect_timeout_secs: 9.15
```
When using this in the `condarc` with micromamba, an error is thrown:

```bash
error    libmamba Bad conversion of configurable 'remote_connect_timeout_secs' from source '~/.condarc' : yaml-cpp: error at line 1, column 30: bad conversion
error    libmamba Bad conversion of configurable 'remote_connect_timeout_secs' from source '~/.condarc' : yaml-cpp: error at line 1, column 30: bad conversion
```

If I change the value to an integer, the error no longer occurs. So it seems like micromamba does not parse this value correctly.

### mamba info / micromamba info

```shell
libmamba version : 1.5.1
     micromamba version : 1.5.1
           curl version : libcurl/7.88.1 OpenSSL/3.1.2 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files : /home/mambauser/.condarc
       virtual packages : __unix=0=0
                          __linux=6.4.16=0
                          __glibc=2.36=0
                          __archspec=1=x86_64
               channels : 
       base environment : /opt/conda
               platform : linux-64
```

### Logs

```shell
error    libmamba Bad conversion of configurable 'remote_connect_timeout_secs' from source '~/.condarc' : yaml-cpp: error at line 1, column 30: bad conversion
error    libmamba Bad conversion of configurable 'remote_connect_timeout_secs' from source '~/.condarc' : yaml-cpp: error at line 1, column 30: bad conversion
```

### environment.yml

_No response_

### ~/.condarc

```yaml
remote_connect_timeout_secs: 9.15
```

### PR DESCRIPTION
**Pull request by jjerphan**
Fix #2934.

### CODE REVIEW

**Review by AntoinePrv — APPROVED** [review]

File: libmamba/tests/src/core/test_configuration.cpp [hunk 1]
```diff
@@ -158,6 +158,17 @@ namespace mamba
                 CHECK_EQ(config.dump(MAMBA_SHOW_CONFIG_VALUES | MAMBA_SHOW_CONFIG_SRCS), "");
             }
 
+            // Regression test for https://github.com/mamba-org/mamba/issues/2934
+            TEST_CASE_FIXTURE(Configuration, "parse_condarc")
+            {
+                std::vector<fs::u8path> possible_rc_paths = {
+                    test_data_dir / "config/.condarc
```
Comment (JohanMabille) [inline libmamba/tests/src/core/test_configuration.cpp:165]:
```suggestion
                    test_data_dir / "config"/.condarc
```

**Comment by AntoinePrv** [comment]
@jjerphan how easy would it be to backport to `1.x` branch?

**Comment by jjerphan** [comment]
Easy, just a few `.pyi` files to change.
