### PR TITLE
Fixed create/install requiring pip install failing when the prefix have whitespaces on Windows

### LINKED ISSUE #1805: [micromamba] micromamba create fails to install pip dependencies if prefix contains whitespace (Windows)
I have a very simple environment.yml looking something like this:
```
name: test_env
channels:
- conda-forge
dependencies:
- python=3.9
- pip
- pip:
  - pydantic
```

Creating an environment with this yml works fine if there are no whitespaces in the prefix: `micromamba create -p "C:/tmp/micromamba_envs/env" --file "C:/tmp/environment.yml"`.
However, if I have a whitespace in the prefix: `micromamba create -p "C:/tmp/micromamba envs/env` --file "C:/tmp/environment.yml"` the installation of the pip dependencies fails with the following error:
```
Installing pip packages: typing-extensions === 4.3.0, pydantic === 1.9.1
failed to create process.
```

Note that this happens on a Windows 10 machine with micromamba 0.24.0.

### PR DESCRIPTION
**Pull request by Klaim**
Also adds tests checking this issue in the first commit. They fail for me on Windows 11 without the fix provided in the second commit.

I believe this should fix #1805  which was re-opened after #1828 re-introduced the issue.

### CODE REVIEW

File: libmamba/src/api/install.cpp [hunk 1]
```diff
@@ -106,10 +115,11 @@ namespace mamba
             specs_f << d.c_str() << '\n';
         specs_f.close();
 
-        replace_all(install_instructions, "{0}", specs.path());
+        for (auto& arg : install_instructions)
```
Comment (Klaim) [inline libmamba/src/api/install.cpp:118]: I'm not totally sure this is the right way to do this replacement. Would it be ok to just replace the whole string it it is equal to `"{0}"`, or other simpler mechanism?
Maybe it would simpler to pass the value into `get_other_pkg_mgr_install_instructions` so that the instructions already contain the path.

**Comment by Klaim** [comment]
@chaubold pinged you as this should fix #1805 that was a regression from #1828

**Comment by chaubold** [comment]
Preventing the argument splitting by creating a `vector<string>` right away makes a lot of sense to me, thanks.

I have built it locally and tried the same use case that gave rise to my [comment](https://github.com/mamba-org/mamba/pull/1828#issuecomment-1206198657) in #1828 and to reopening the issue. With the changes in this PR, everything works fine 👍 Nice one!

File: micromamba/tests/test_create.py [hunk 2]
```diff
@@ -641,3 +641,17 @@ def test_pyc_compilation(self, version, build, cache_tag):
...
         assert (site_packages / pyc_fn).exists()
         assert pyc_fn.name in six_meta
+
+    test_env_requires_pip_install_path = os.path.join(
+        Path(__file__).parent.resolve(), "env-requires-pip-install.yaml"
+    )
+
+    def test_requires_pip_install(self):
+        prefix = Path(TestCreate.prefix)
+        cmd = ["-p", f"{prefix}", "-f", self.test_env_requires_pip_install_path]
```
Comment (jonashaag) [inline micromamba/tests/test_create.py:651]:
```suggestion
        cmd = ["-p", prefix, "-f", self.test_env_requires_pip_install_path]
```

File: micromamba/tests/test_create.py [hunk 3]
```diff
@@ -641,3 +641,17 @@ def test_pyc_compilation(self, version, build, cache_tag):
...
+        create(*cmd)
+
+    def test_requires_pip_install_prefix_spaces(self):
+        prefix = Path(f"{TestCreate.prefix} with space")
+        cmd = ["-p", f"{prefix}", "-f", self.test_env_requires_pip_install_path]
```
Comment (jonashaag) [inline micromamba/tests/test_create.py:656]:
```suggestion
        cmd = ["-p", prefix, "-f", self.test_env_requires_pip_install_path]
```

**Review by jonashaag — APPROVED** [review]

**Comment by jonashaag** [comment]
Does this also apply if we have a environment name with a space in `environment.yml`? (Is that even allowed?) If yes, shall we add a test as well?

**Comment by Klaim** [comment]
> Does this also apply if we have a environment name with a space in `environment.yml`? (Is that even allowed?) If yes, shall we add a test as well?

I didn't consider that case, I'll add a test.

**Comment by Klaim** [comment]
@jonashaag For some unclear reason your changes don't pass for me (windows 11) because the type of `prefix` is `WindowsPath('...')` and can't be passed as is to that function so `f"{prefix}"` is used as a conversion to string. I'm not sure why it passes on CI, but maybe it's a python version mismatch.

**Comment by Klaim** [comment]
The initial fix should cover any prefix value provided (as long as it have been correctly parsed before reaching that part of the code). I added the test.

**Comment by wolfv** [comment]
Thanks @Klaim !

**Comment by jonashaag** [comment]
> @jonashaag For some unclear reason your changes don't pass for me (windows 11) because the type of `prefix` is `WindowsPath('...')` and can't be passed as is to that function so `f"{prefix}"` is used as a conversion to string. I'm not sure why it passes on CI, but maybe it's a python version mismatch.

The proper way would be to use str.

**Comment by chaubold** [comment]
Are there any plans to build a 0.25.2 release with this fix?
