### PR TITLE
Fix #2271

### LINKED ISSUE #2271: `micromamba shell -n myenv` broken in 1.3.0
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

/

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

```
⋊> ~ micromamba shell -n base
critical libmamba The given prefix does not exist: "base"
⋊> ~ micromamba run -n base ls
...works fine...
```

Curious why this isn't covered by a test

### mamba info / micromamba info

_No response_

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by jonashaag**
Attempt to fix https://github.com/mamba-org/mamba/issues/2271 (introduced in #2257, cc @Hind-M)

- Adds a test
- Makes exit codes identical to `run` and `conda run`
- Doesn't actually fix the bug, because I wasn't sure where — @Hind-M any insights?

### CODE REVIEW

File: libmamba/src/core/run.cpp [hunk 1]
```diff
@@ -391,7 +391,7 @@ namespace mamba
             if (ec)
             {
                 std::cerr << ec.message() << '\n';
-                return 1;
```
Comment (jonashaag) [inline libmamba/src/core/run.cpp:394]: Not sure about this.

**Comment by Hind-M** [comment]
Oh I see, that's because `micromamba shell` doesn't go through `configuration` where the `target_prefix` is set:
https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/configuration.cpp#L447-L465
So adding something like this piece of code could do the trick:

```
if (prefix.empty() || prefix == "base") // could be only base depending of the behavior that we want
    Context::instance().target_prefix = env::home_directory() / "micromamba";
else
    Context::instance().target_prefix = env::home_directory() / "micromamba/envs/" / prefix;
```
as a replacement of https://github.com/mamba-org/mamba/blob/main/micromamba/src/shell.cpp#L89

**Comment by Hind-M** [comment]
I am not sure though if we should do it this way in case using the shell isn't meant to manipulate/handle the prefix... If so, maybe checking that the `target_prefix` got in `run_in_environment` is a path before checking its existence...
But I suspect that there was already a bug in shell since nothing was checked nor tested?...

**Comment by Hind-M** [comment]
Yes, I meant hidden bugs or special cases since the prefix is not checked.

**Comment by wolfv** [comment]
Planning to do a bugfix release today. Do you think we can finish this one?

**Comment by Hind-M** [comment]
The snippet I posted seems to work on my side, but I don't think I have the rights to push here.

**Comment by jonashaag** [comment]
We are hardcoding the root prefix here though...

**Comment by Hind-M** [comment]
> Also, does the name `base` have special meaning in Micromamba?

Well It seems to be the name referring to the root prefix as in the following files:

https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/shell.cpp#L95-L112
https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/shell.cpp#L137-L144
https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/configuration.cpp#L450-L457

but maybe it shouldn't...

**Comment by Hind-M** [comment]
> We are hardcoding the root prefix here though...

Yes, but I am actually wondering why we don't have access to the root prefix in the configuration when using the shell this way...

File: libmamba/src/core/run.cpp (hunk 1 above)
Comment (wolfv) [reply libmamba/src/core/run.cpp]: sorry, I reverted this change. I didn't get the motivation. Is that what conda does?

**Comment by jonashaag** [comment]
Why do we even need a special case for setting up the prefix here? I’m not familiar with the prefix code but this looks weird

**Comment by wolfv** [comment]
It's because shell is also used for shell init etc where the normal way of finding root prefix/target prefix might not work yet

**Comment by jonashaag** [comment]
Ok! The test I added still fails for some reason

**Comment by wolfv** [comment]
I think the file is not executable

**Comment by wolfv** [comment]
hmm there was something else going on on linux with the file being busy or so. I think I fixed that in a clean way. Let's get this merged and release! :)
