### PR TITLE
Fix segfault in error messages

### LINKED ISSUE #3874: Segfault with sudoku problem
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

segfault

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

@jjhelmus reported [this issue](https://github.com/conda/conda-libmamba-solver/issues/334#issuecomment-2752674110) in conda-libmamba-solver:

> I've been seeing segfaults on linux and `pointer being freed was not allocated` errors on macOS with the following command which could be related
> 
> ```
> conda create -p ./blah --override-channel -c jjhelmus/label/sudoku --file requirements.in
> ```
> 
> The `requirements.in` file contains
> ```
> sudoku_0_0 == 5
> sudoku_1_0 == 3
> sudoku_4_0 == 7
> sudoku_0_1 == 6
> sudoku_3_1 == 1
> sudoku_4_1 == 9
> sudoku_5_1 == 5
> sudoku_1_2 == 9
> sudoku_2_2 == 8
> sudoku_7_2 == 6
> sudoku_0_3 == 8
> sudoku_4_3 == 6
> sudoku_8_3 == 3
> sudoku_0_4 == 4
> sudoku_3_4 == 8
> sudoku_5_4 == 3
> sudoku_8_4 == 1
> sudoku_0_5 == 7
> sudoku_4_5 == 2
> sudoku_8_5 == 6
> sudoku_1_6 == 6
> sudoku_6_6 == 2
> sudoku_7_6 == 8
> sudoku_3_7 == 4
> sudoku_4_7 == 1
> sudoku_5_7 == 9
> sudoku_8_7 == 5
> sudoku_4_8 == 8
> sudoku_7_8 == 7
> sudoku_8_8 == 9
> ```

---

This reproduces with mamba 2.0.8 too:

```
mamba create --dry-run -p ./blah -c jjhelmus/label/sudoku --file requirements.in --override-channels -vv
```

### mamba info / micromamba info

```shell
libmamba version : 2.0.8
          mamba version : 2.0.8
           curl version : libcurl/8.12.1 OpenSSL/3.4.1 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.1 nghttp2/1.64.0
     libarchive version : libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /root/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /root/.mambarc
 populated config files : /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-aarch64
```

### Logs

```shell
$ gdb -ex r --args mamba create --dry-run -p ./blah -c jjhelmus/label/sudoku --file requirements.in --override-channels -vv
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mamba...
Starting program: /opt/conda/bin/mamba create --dry-run -p ./blah -c jjhelmus/label/sudoku --file requirements.in --override-channels -vv
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xffffae8269e0 (LWP 7469)]
debug    libmamba Loading configuration
debug    libmamba 128 configurables computed
debug    libmamba Checking if '/opt/conda/pkgs' is writable
debug    libmamba '/opt/conda/pkgs' writable
info     libmamba Searching index cache file for repo 'jjhelmus/label/sudoku/linux-aarch64'
debug    libmamba Locking directory '/opt/conda/pkgs/cache'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
debug    libmamba Using SOLV cache
debug    libmamba Unlocking '/opt/conda/pkgs/cache'
jjhelmus/label/sudoku/linux-aarch64                         Using cache
info     libmamba Searching index cache file for repo 'jjhelmus/label/sudoku/noarch'
debug    libmamba Locking directory '/opt/conda/pkgs/cache'
debug    libmamba Successfully locked
debug    libmamba Using JSON cache
debug    libmamba Using SOLV cache
debug    libmamba Unlocking '/opt/conda/pkgs/cache'
jjhelmus/label/sudoku/noarch                                Using cache
info     libmamba Checking for CA certificates at the root prefix: "/opt/conda/ssl/cacert.pem"
info     libmamba Using CA certificates from `conda-forge::ca-certificates` installed in the root prefix (i.e "/opt/conda/ssl/cacert.pem")
[New Thread 0xffffaddb89e0 (LWP 7470)]
[Thread 0xffffaddb89e0 (LWP 7470) exited]
[New Thread 0xffffad5b79e0 (LWP 7471)]
[Thread 0xffffad5b79e0 (LWP 7471) exited]
info     libmamba Attempting to read libsolv solv file "/opt/conda/pkgs/cache/a0b96848.solv" for repo https://conda.anaconda.org/jjhelmus/label/sudoku/linux-aarch64
info     libmamba Expecting solv metadata : {"etag":"","mod":"Tue, 25 Mar 2025 22:05:46 GMT","tool_version":"2.0_0.7.30","url":"https://conda.anaconda.org/jjhelmus/label/sudoku/linux-aarch64"}
debug    libmamba Locking file '/opt/conda/pkgs/cache/a0b96848.solv'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"","mod":"Tue, 25 Mar 2025 22:05:46 GMT","tool_version":"2.0_0.7.30","url":"https://conda.anaconda.org/jjhelmus/label/sudoku/linux-aarch64"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/opt/conda/pkgs/cache/a0b96848.solv'
info     libmamba Attempting to read libsolv solv file "/opt/conda/pkgs/cache/1dd7a605.solv" for repo https://conda.anaconda.org/jjhelmus/label/sudoku/noarch
info     libmamba Expecting solv metadata : {"etag":"","mod":"Tue, 25 Mar 2025 22:05:46 GMT","tool_version":"2.0_0.7.30","url":"https://conda.anaconda.org/jjhelmus/label/sudoku/noarch"}
debug    libmamba Locking file '/opt/conda/pkgs/cache/1dd7a605.solv'
debug    libmamba Successfully locked
info     libmamba Loaded solv metadata : {"etag":"","mod":"Tue, 25 Mar 2025 22:05:46 GMT","tool_version":"2.0_0.7.30","url":"https://conda.anaconda.org/jjhelmus/label/sudoku/noarch"}
info     libmamba Metadata from solv are valid, loading successful
debug    libmamba Unlocking '/opt/conda/pkgs/cache/1dd7a605.solv'
info     libmamba Loading site packages
debug    libmamba `pip` not found
debug    libmamba Loading virtual packages
debug    libmamba Loading distribution virtual packages
debug    libmamba Loading CUDA virtual package
debug    libmamba CUDA version file not found: /usr/local/cuda/version.json
debug    libmamba Trying to find CUDA version by running `nvidia-smi --query -u -x`
[Detaching after fork from child process 7472]
debug    libmamba CUDA not found


Thread 1 "mamba" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x61) at malloc.c:3102
3102    malloc.c: No such file or directory.
```

### environment.yml

```yaml
sudoku_0_0 == 5
sudoku_1_0 == 3
sudoku_4_0 == 7
sudoku_0_1 == 6
sudoku_3_1 == 1
sudoku_4_1 == 9
sudoku_5_1 == 5
sudoku_1_2 == 9
sudoku_2_2 == 8
sudoku_7_2 == 6
sudoku_0_3 == 8
sudoku_4_3 == 6
sudoku_8_3 == 3
sudoku_0_4 == 4
sudoku_3_4 == 8
sudoku_5_4 == 3
sudoku_8_4 == 1
sudoku_0_5 == 7
sudoku_4_5 == 2
sudoku_8_5 == 6
sudoku_1_6 == 6
sudoku_6_6 == 2
sudoku_7_6 == 8
sudoku_3_7 == 4
sudoku_4_7 == 1
sudoku_5_7 == 9
sudoku_8_7 == 5
sudoku_4_8 == 8
sudoku_7_8 == 7
sudoku_8_8 == 9
```

### ~/.condarc

```yaml
N/A
```

### PR DESCRIPTION
**Pull request by AntoinePrv**
Fix #3874 

- **Add tag to problem_graph tests**
- **Fix segfault**
- **Fix pin error messages**
- **Fix test loop**
- **Fix error message test**

### CODE REVIEW

File: libmamba/tests/src/solver/test_problems_graph.cpp [hunk 1]
```diff
@@ -534,6 +534,39 @@ namespace
         );
     }
 
+    auto create_sudoku(Context&, ChannelContext& channel_context)
+    {
+        auto db = solver::libsolv::Database{ channel_context.params() };
+        const auto xpt = db.add_repo_from_repodata_json(
+            mambatests::test_data_dir / "repodata/sudoku.json",
```
Comment (jjerphan) [inline libmamba/tests/src/solver/test_problems_graph.cpp:541]: I guess it is fine if we cannot support fetching remote files.

**Review by jjerphan — APPROVED** [review]
Thank you, @AntoinePrv.

File: libmamba/tests/src/solver/test_problems_graph.cpp (hunk 1 above)
Comment (AntoinePrv) [reply libmamba/tests/src/solver/test_problems_graph.cpp:541]: This is a reasonably small (30'000l) file that I committed it to the repo. It's also nice to keep the test independent from the rest of Mamba.
