### PR TITLE
fix: Add `x86_64` archspec support for Windows

### LINKED ISSUE #3795: Archspec not implemented for Windows
### Troubleshooting docs

- [x] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [x] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

archspec, x86_64, microarch

### Latest version of Mamba

- [x] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

`micromamba info -v` always returns `__archspec=1=x86_64` on Windows, x64 machines. The net result is that windows users will never get optimized packages without manually overriding the archspec

This is due to [get_archspec_x86_64](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/virtual_packages.cpp#L215) only working for GCC and clang builds. However, the release micromamba binary from [conda-forge](https://github.com/conda-forge/mamba-feedstock/blob/4ee032c8d331371d3e1e53a533e3684d1428b318/.ci_support/win_64_.yaml#L8) uses [MSVC] (Microsoft Visual C compiler)

which causes this ifdef to evaluate to false: `#if (defined(__GNUC__) || defined(__clang__)) && __x86_64__`
It's not as simple as just changing the ifdef, because `__builtin_cpu_supports` is gcc specific. Instead, on MSVC, you'll need to use `__cpuid` instead for that compiler

### mamba info / micromamba info

```shell
(Sensitive paths stripped)


       libmamba version : 2.0.5
     micromamba version : 2.0.5
           curl version : libcurl/8.8.0-DEV Schannel zlib/1.3.1
     libarchive version : libarchive 3.7.2 zlib/1.3.1 liblzma/5.6.2 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.6
   
            environment : base
    
       virtual packages : __win=10.0.22631=0
                          __archspec=1=x86_64
                          __cuda=12.7=0
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
               platform : win-64
```

### Logs

```shell

```

### environment.yml

```yaml

```

### ~/.condarc

```yaml

```

### PR DESCRIPTION
**Pull request by jjerphan**
Fix #3795.

### CODE REVIEW

File: libmamba/src/core/virtual_packages.cpp [hunk 1]
```diff
@@ -236,7 +236,52 @@ namespace mamba
...
+            // position of the required feature.
+            //
+            // See those sources to understand bitshifts:
+            // https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-160
+            // https://en.wikipedia.org/wiki/CPUID#EAX=7,_ECX=0:_Extended_Features
+
+            int cpu_info[4];
+            int eax_value = 7;
+            int ecx_value = 0;
+            __cpuidex(cpu_info, eax_value, ecx_value);
```
Comment (jjerphan) [inline libmamba/src/core/virtual_packages.cpp:252]: Note to reviewers: I am wondering whether more checks are needed to check that `7` and `0` are valid value for `eax_value` and `ecx_value` (AKA `leaf` and `subleaf` in Intel's terminology).

**Comment by jjerphan** [comment]
@intentionally-left-nil: we need someone to test and review it, ideally on several Windows machines with different architectures.

We welcome your feedback greatly! 🙂

File: libmamba/src/core/virtual_packages.cpp [hunk 2]
```diff
@@ -236,7 +236,52 @@ namespace mamba
...
             }
+#elif defined(_MSC_VER) && defined(_M_X64)
+            // We apply boolean masks to the results of the cpuid instruction
+            // to determine if the CPU supports the required instruction sets.
+            // The masks are generated by shifting 1 to the left by the bit
+            // position of the required feature.
+            //
+            // See those sources to understand bitshifts:
+            // https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-160
+            // https://en.wikipedia.org/wiki/CPUID#EAX=7,_ECX=0:_Extended_Features
```
Comment (JohanMabille) [inline libmamba/src/core/virtual_packages.cpp:247]: I think a link to https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels might be worth too (for the version spec of x86_64)

File: libmamba/src/core/virtual_packages.cpp [hunk 3]
```diff
@@ -236,7 +236,52 @@ namespace mamba
...
+            int eax_value = 7;
+            int ecx_value = 0;
+            __cpuidex(cpu_info, eax_value, ecx_value);
+
+            bool avx512f = cpu_info[1] & (1 << 16);
+            bool avx512dq = cpu_info[1] & (1 << 17);
+            bool avx512cd = cpu_info[1] & (1 << 28);
+            bool avx512bw = cpu_info[1] & (1 << 30);
+            bool avx512vl = cpu_info[1] & (1 << 31);
+            if (avx512f && avx512dq && avx512cd && avx512bw && avx512vl)
```
Comment (JohanMabille) [inline libmamba/src/core/virtual_packages.cpp:259]: Nitpicking: avx512 dq/cd/bw/vl are all implemented on top of avx512f, so no need to check for this value.

File: libmamba/src/core/virtual_packages.cpp [hunk 4]
```diff
@@ -236,7 +236,52 @@ namespace mamba
...
+            {
+                return "x86_64_v4";
+            }
+
+            bool bmi = cpu_info[1] & (1 << 3);
+            bool avx2 = cpu_info[1] & (1 << 5);
+            bool bmi2 = cpu_info[1] & (1 << 8);
+            bool fma_ = cpu_info[1] & (1 << 12);
+            bool avx = cpu_info[1] & (1 << 28);
+            if (bmi && avx2 && bmi2 && fma_ && avx)
```
Comment (JohanMabille) [inline libmamba/src/core/virtual_packages.cpp:269]: Similar remark here: avx2 is implmeented on top of avx, so no need to check for avx.

File: libmamba/src/core/virtual_packages.cpp [hunk 5]
```diff
@@ -236,7 +236,52 @@ namespace mamba
...
+            {
+                return "x86_64_v3";
+            }
+
+            bool sse3 = cpu_info[1] & (1 << 0);
+            bool ssse3 = cpu_info[1] & (1 << 9);
+            bool sse41 = cpu_info[1] & (1 << 19);
+            bool sse42 = cpu_info[1] & (1 << 20);
+            bool popcnt = cpu_info[1] & (1 << 23);
+            if (sse3 && ssse3 && sse41 && sse42 && popcnt)
```
Comment (JohanMabille) [inline libmamba/src/core/virtual_packages.cpp:279]: Similar remark here: sse42 implies sse41 which implies ssse3 which implies sse3,so checking sse42 should be enough (I haven't checked for popcnt).

**Review by JohanMabille — APPROVED** [review]
LGTM although having feedback from people who can test it would be nice. 

The nitpicking comments can be ignored if you prefer to keep the exhaustive check list for each version of x86_64.

File: libmamba/src/core/virtual_packages.cpp (hunk 3 above)
Comment (jjerphan) [reply libmamba/src/core/virtual_packages.cpp:259]: I agree, but I propose to keep the logic in line with the one for unix system as currently implemented a few lines above because it is cheap and it does not make assumption (also, I would take time to make sure that the above is correctly implemented, because more instructions seem to be present for each architecture).

**Comment by Klaim** [comment]
I tested on my Windows machine, it has an [AMD Ryzen 9 5900X](https://www.techpowerup.com/cpu-specs/ryzen-9-5900x.c2363) , running Windows 11.

I built this branch locally using Visual Studio (preview) `v17.13.0-pre.2.1`, compiler version `19.43.34618 for x64`.
I obtained:
```
mamba info -v

       libmamba version : 2.0.6
          mamba version : 2.0.6
           curl version : libcurl/8.11.1 Schannel zlib/1.3.1 libssh2/1.11.1
     libarchive version : libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : C:\Users\Klaim\micromamba\envs
          package cache : C:\Users\Klaim\micromamba\pkgs
                          C:\Users\Klaim\.mamba\pkgs
                          C:\Users\Klaim\AppData\Roaming\.mamba\pkgs
            environment : mamba-pr-testing (active)
           env location : C:\Users\Klaim\micromamba\envs\mamba-pr-testing
      user config files : C:\Users\Klaim\.mambarc
 populated config files :
       virtual packages : __win=10.0.22631=0
                          __archspec=1=x86_64_v2
                          __cuda=12.7=0
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
       base environment : C:\Users\Klaim\micromamba
               platform : win-64
```

I was told `__archspec` should be `v3` for this case? (I have no idea what is the correct value for this cpu)

**Comment by nbeerbower** [comment]
Perhaps I compiled something wrong but my results on Windows 11 with an i9-13950HX:
```

       libmamba version : 2.0.6.rc2
          mamba version : 2.0.6.rc2
           curl version : libcurl/8.11.1 Schannel zlib/1.3.1 libssh2/1.11.1
     libarchive version : libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : C:\Users\Nick\.local\share\mamba\envs
          package cache : C:\Users\Nick\.local\share\mamba\pkgs
                          C:\Users\Nick\.mamba\pkgs
                          C:\Users\Nick\AppData\Roaming\.mamba\pkgs
            environment : build_env (active)
           env location : C:\Users\Nick\.local\share\mamba\envs\build_env
      user config files : C:\Users\Nick\.mambarc
 populated config files :
       virtual packages : __win=10.0.26100=0
                          __archspec=1=x86_64
                          __cuda=12.4=0
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
       base environment : C:\Users\Nick\.local\share\mamba
               platform : win-64
```
Compiler: `Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64`

**Comment by JohanMabille** [comment]
@nbeerbower I think you're testing the wrong binary, the output version is 2.0.6.rc2, while it should be 2.0.6.

**Comment by nbeerbower** [comment]
My bad! I cloned the fork repo but didn't checkout the PR branch.

```
       libmamba version : 2.0.6
          mamba version : 2.0.6
           curl version : libcurl/8.11.1 Schannel zlib/1.3.1 libssh2/1.11.1
     libarchive version : libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : C:\Users\Nick\.local\share\mamba\envs
          package cache : C:\Users\Nick\.local\share\mamba\pkgs
                          C:\Users\Nick\.mamba\pkgs
                          C:\Users\Nick\AppData\Roaming\.mamba\pkgs
            environment : build_env (active)
           env location : C:\Users\Nick\.local\share\mamba\envs\build_env
      user config files : C:\Users\Nick\.mambarc
 populated config files :
       virtual packages : __win=10.0.26100=0
                          __archspec=1=x86_64_v3
                          __cuda=12.4=0
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
       base environment : C:\Users\Nick\.local\share\mamba
               platform : win-64
```

Looks like it works perfectly now! Let me know if you'd like me to test anything else.

**Comment by jjerphan** [comment]
Thank you for testing, @nbeerbower.

I would at least wait for another review from Joël who also uses Windows (it might take some time because this PR is not the most urgent one regarding work on Windows).

**Comment by jjerphan** [comment]
> If my understanding is correct this is the expected output? You'll have to confirm as I dont know much on the cpu capability flags subjects.

Yes, it is correct.
