### PR TITLE
Fix dependency and `subdir` in repoquery `whoneeds`

### LINKED ISSUE #3717: repoquery whoneeds no longer lists package version dependency
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

repoquery whoneeds

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

When using the `repoquery whoneeds` function, mamba used to return the required version(s) of the specified package.  There is still a column labeled "Depends" in the output.  However, nothing appears in this column.  It also appears that the outputs for the next 2 columns ("Channel" and "Subdir") are shifted left by 1 column, as they appear under the "Depends" and "Channel" column headings.

### mamba info / micromamba info

```shell
libmamba version : 2.0.5
          mamba version : 2.0.5
           curl version : libcurl/8.11.1 Schannel zlib/1.3.1 libssh2/1.11.1
     libarchive version : libarchive 3.7.7 zlib/1.3.1 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : C:\Users\manow\miniconda3\envs
                          C:\Users\manow\.conda\envs
                          C:\Users\manow\AppData\Local\conda\conda\envs
                          C:\Users\manow\miniconda3\Library\envs
          package cache : C:\Users\manow\miniconda3\pkgs
                          C:\Users\manow\.conda\pkgs
                          C:\Users\manow\AppData\Local\conda\conda\pkgs
                          C:\Users\manow\miniconda3\Library\pkgs
                          C:\Users\manow\.mamba\pkgs
                          C:\Users\manow\AppData\Roaming\.mamba\pkgs
            environment : C:\Users\manow\miniconda3 (active)
           env location : C:\Users\manow\miniconda3
      user config files : C:\Users\manow\.mambarc
 populated config files : C:\Users\manow\.mambarc
                          C:\Users\manow\.condarc
       virtual packages : __win=10.0.19045=0
                          __archspec=1=x86_64
                          __cuda=12.7=0
               channels : https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pyg/noarch
                          https://conda.anaconda.org/pyg/win-64
                          https://conda.anaconda.org/nvidia/label/cuda-11.3.1/noarch
                          https://conda.anaconda.org/nvidia/label/cuda-11.3.1/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://software.repos.intel.com/python/conda/noarch
                          https://software.repos.intel.com/python/conda/win-64
       base environment : C:\Users\manow\miniconda3\Library
               platform : win-64
```

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by Hind-M**
- [x] Fix subdir in repoquery
- [x] Fix #3717

### CODE REVIEW

File: libmamba/src/core/query.cpp [hunk 1]
```diff
@@ -599,7 +592,7 @@ namespace mamba
         }
 
         std::vector<mamba::printers::FormattedString> headers;
-        std::vector<std::string_view> cmds, args;
+        std::vector<std::string> cmds, args;
```
Comment (Hind-M) [inline libmamba/src/core/query.cpp:595]: This is the bug as `cmds` and `args` were refering to [sfmt](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/query.cpp#L627-L633) after it was out of scope, and this was only appearing in osx and windows...

File: micromamba/tests/test_repoquery.py [hunk 2]
```diff
@@ -168,6 +162,20 @@ def test_whoneeds_not_installed_with_channel(yaml_env: Path, with_platform):
...
+def test_whoneeds_not_installed_with_channel_no_json(yaml_env: Path, spec):
+    res = helpers.umamba_repoquery("whoneeds", "-c", "conda-forge", spec, "--platform", "osx-64")
+    assert "Name Version Build Depends Channel Subdir" in helpers.remove_whitespaces(res)
+    if spec == "xtensor=0.24.5":  # `Depends` column is empty here (bug?)
+        assert "cascade 0.1.1 py38h5ce3968_0 conda-forge osx-64" in helpers.remove_whitespaces(res)
+    else:
+        assert (
+            "cascade 0.1.1 py38h5ce3968_0 xtensor conda-forge osx-64"
+            in helpers.remove_whitespaces(res)
+        )
```
Comment (jjerphan) [inline micromamba/tests/test_repoquery.py:176]: How about?

```suggestion
    # Non-regression test for: https://github.com/mamba-org/mamba/issues/3717
    res = helpers.umamba_repoquery("whoneeds", "-c", "conda-forge", spec, "--platform", "osx-64")
    res = helpers.remove_whitespaces(res)
    assert "Name Version Build Depends Channel Subdir" in res
    if spec == "xtensor=0.24.5":  # `Depends` column is empty here (bug?)
        assert "cascade 0.1.1 py38h5ce3968_0 conda-forge osx-64" in res
    else:
        assert (
            "cascade 0.1.1 py38h5ce3968_0 xtensor conda-forge osx-64"
            in res
        )
```

File: libmamba/src/core/query.cpp [hunk 3]
```diff
@@ -621,7 +614,7 @@ namespace mamba
             else if (col.find_first_of(":") == col.npos)
             {
                 headers.emplace_back(col);
```
Comment (jjerphan) [inline libmamba/src/core/query.cpp:616]: Could the current code have problem as well? How about?
```suggestion
                headers.emplace_back(std::string(col));
```

File: micromamba/tests/test_repoquery.py [hunk 4]
```diff
@@ -168,6 +162,20 @@ def test_whoneeds_not_installed_with_channel(yaml_env: Path, with_platform):
     assert any(x["name"] == "qpot" for x in pkgs)
 
 
+@pytest.mark.parametrize("shared_pkgs_dirs", [True], indirect=True)
+@pytest.mark.parametrize("spec", ("xtensor", "xtensor=0.24.5"))
+def test_whoneeds_not_installed_with_channel_no_json(yaml_env: Path, spec):
+    res = helpers.umamba_repoquery("whoneeds", "-c", "conda-forge", spec, "--platform", "osx-64")
+    assert "Name Version Build Depends Channel Subdir" in helpers.remove_whitespaces(res)
+    if spec == "xtensor=0.24.5":  # `Depends` column is empty here (bug?)
+        assert "cascade 0.1.1 py38h5ce3968_0 conda-forge osx-64" in helpers.remove_whitespaces(res)
```
[the remark this answers is not in the document]
Comment (jjerphan) [reply micromamba/tests/test_repoquery.py:171]: The first builds of `cascade` (i.e. the ones of `0.1.1`) depend on `xtensor`, but not on `xtensor==0.24.5`.

Yet they might have been built against them, here is one of their `index.json`:

```json
{
  "arch": "x86_64",
  "build": "py310ha6c322b_0",
  "build_number": 0,
  "depends": [
    "boost-cpp >=1.78.0,<1.79.0a0",
    "fmt >=9.1.0,<10.0a0",
    "hdf5 >=1.12.2,<1.12.3.0a0",
    "heyoka >=0.21.0",
    "heyoka >=0.21.0,<0.22.0a0",
    "heyoka.py >=0.21.0",
    "libcxx >=14.0.6",
    "numpy",
    "pybind11-abi 4",
    "python >=3.10,<3.11.0a0",
    "python_abi 3.10.* *_cp310",
    "spdlog >=1.11.0,<1.12.0a0",
    "tbb >=2021.8.0",
    "xtensor",
    "xtensor-blas"
  ],
  "license": "MPL-2.0",
  "name": "cascade",
  "platform": "osx",
  "subdir": "osx-64",
  "timestamp": 1677367283346,
  "version": "0.1.1"
}
```

I think `xtensor` should be reported in this case, as it is the case with:

```
micromamba repoquery whoneeds xtensor -c conda-forge --platform osx-64 | grep cascade
```

```
 cascade                           0.1.1   py38h5ce3968_0               xtensor                       conda-forge conda-forge
 cascade                           0.1.1   py310ha6c322b_0              xtensor                       conda-forge conda-forge
 cascade                           0.1.1   py39hb1d9d96_0               xtensor                       conda-forge conda-forge
```

What do you think?

File: libmamba/src/core/query.cpp (hunk 3 above)
Comment (Hind-M) [reply libmamba/src/core/query.cpp:616]: Converting `col` to `std::string` in `cmds.push_back(std::string(col));` is due to changing `cmds` to `std::vector<std::string>` (instead of `std::vector<std::string_view>`).
But it's not needed in `headers.emplace_back(col);` as `headers`(`std::vector<mamba::printers::FormattedString>`) already have a constructor accepting `std::string_view`.

Comment (jjerphan) [reply libmamba/src/core/query.cpp:616]: Sorry, my remark was not clear.

I was wondering whether we could also have this problem for all vectors referencing `std::string_view`s directly or indirectly, i.e. could we have the problem with `headers` again here if the original `std::string` of `std::string_view` are freed?

Comment (Hind-M) [reply libmamba/src/core/query.cpp:616]: Since `headers` is a vector of a struct (`FormattedString`) containing a `string` and not a `string_view`, it should be okay.
The only `string_view`s pointing to a local `string` being out of scope later (`sfmt`) were `cmds` and `args` which were modified to `string` now.
So seems ok so far.

File: micromamba/tests/test_repoquery.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (Hind-M) [reply micromamba/tests/test_repoquery.py]: Yep, after thinking about it, it seems redundant as we already know what `Depends` should be set to (the spec already in the command), but let's do it [this way](https://github.com/mamba-org/mamba/pull/3743/commits/05b65a48f27931867ac565b9b8ea53258a383f3a) to be consistent with the case where no constraints are given.

**Review by jjerphan — APPROVED** [review]
